#927-improve-layout-of-form-fields
Northeastern-Electric-Racing/FinishLine pull request #1002
Opened 2023-03-16 01:09 UTC by MWalve

## Changes

Changed the layout of the form for the Work packages, such that it was no longer skinny, and the fields were beside each other

## Notes

Still think it looks a bit off, width and height wise, and the title Activate's font size still seems small compared to the layout

## Screenshots

![image](https://user-images.githubusercontent.com/97235276/225483610-47e5f208-af5e-4548-9f2f-bdd66d904c4e.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #927

2023-03-16 01:51 UTC, Peyton-McKee requested changes
Looks Good! Looks like u added an extra line but other than that looks good!

2023-03-16 01:51 UTC, Peyton-McKee commented on src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx
> +
delete line pls

2023-03-17 21:41 UTC, Peyton-McKee approved these changes
looks good

2023-03-17 22:00 UTC, RChandler234 approved these changes
LGTM

2023-03-17 22:06 UTC, merged