#975: links open in different tabs
Northeastern-Electric-Racing/FinishLine pull request #1005
Opened 2023-03-16 04:16 UTC by ryanhowe28

## Changes

links on project details page open in a new tab 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #975

2023-03-16 17:24 UTC, nezamj03 requested changes

2023-03-16 17:24 UTC, nezamj03 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
this doesn't work for me. clicking the links does nothing

2023-03-16 17:28 UTC, nezamj03 approved these changes

2023-03-17 20:40 UTC, RChandler234 approved these changes
LGTM

2023-03-17 20:40 UTC, merged