#337 timeline status should be displayed better
Northeastern-Electric-Racing/FinishLine pull request #1014
Opened 2023-03-21 01:05 UTC by Sybaru

## Changes

Created a pipe to translate timeline status into a more readable format

## Screenshots

![image](https://user-images.githubusercontent.com/55457750/226496896-150b1f53-1643-4091-8dab-4001849f0882.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #337

2023-03-21 02:59 UTC, z-roth requested changes

2023-03-21 02:59 UTC, z-roth commented on src/frontend/src/utils/pipes.ts
> +  res = res.toLowerCase();
looks like a redundant call to `.toLowerCase()` here

2023-03-21 02:59 UTC, z-roth commented on src/frontend/src/utils/pipes.ts
> +  return res;
you could instead do: 
`res
.toLowerCase()
.split('_')
.map((s) => s.charAt(0).toUpperCase() +s.substring(1))
.join(' ')`

2023-03-28 00:57 UTC, z-roth approved these changes
LGTM - great work!

2023-03-28 01:38 UTC, RChandler234 approved these changes
LGTM!

2023-03-28 01:38 UTC, merged