#711: removed any type from projects-get-all
Northeastern-Electric-Racing/FinishLine pull request #1052
Opened 2023-03-23 21:42 UTC by sewardwi

## Changes

removed the any type on line 20 and replaced it with a WP array

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # 711

2023-03-23 22:18 UTC, callmejim1226 commented on src/shared/src/backend-supports/projects-get-all.ts
> +  startDate: any;
The goal for this ticket is to remove **any** type in projects-get-all.ts. Can you replace the data type of startDate with the correct type? (Srry if this confused you last night, I just wrote **any** for this field on your laptop to quickly show you an property example we need for the work package)

2023-03-23 22:23 UTC, callmejim1226 commented on src/shared/src/backend-supports/projects-get-all.ts
> +interface WP {
Can we rename this interface as **WorkPackageDurationProps** to give more details for the code readers? I'm unsure if Reid or Anthony will have a different opinion on naming this type.

2023-03-23 22:28 UTC, callmejim1226 commented on src/shared/src/backend-supports/projects-get-all.ts
> +interface WP {
Also, can we locate this interface before the calculateEndDate function? For our file formatting, we wanna place the interface in the beginning after the imports.

2023-03-23 22:29 UTC, callmejim1226 requested changes
Great start!!

I commented few changes to improve our code for this ticket. Lmk if you need anything for this!

2023-04-03 21:02 UTC, callmejim1226 approved these changes
The code looks good to me! Great work! (Idk why prettier test is failing, but make sure your prettier extension is enabled on your VScode)

2023-04-05 22:14 UTC, anthonybernardi approved these changes
nice, dont forget the "#" in teh branch name

2023-04-05 22:14 UTC, merged