#924 improve layout form fields
Northeastern-Electric-Racing/FinishLine pull request #1056
Opened 2023-03-25 21:59 UTC by Aaryan1203

Repositioned the fields and breadcrumbed the project name. I originally had the dependencies being added horizontally but it didn't look too good so I kept them vertical and instead just added some margin between each of them.

<img width="1420" alt="Screenshot 2023-03-25 at 5 58 45 PM" src="https://user-images.githubusercontent.com/76594216/227744290-f82f4ff1-4f08-4a3c-94fb-4e89bcc67ec3.png">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2023-03-25 22:26 UTC, Peyton-McKee requested changes
good start, make sure to test all the different widths it could be because at certain points the label text wraps and it doesnt look great because theyre not all inline, you should just be able to add the nowrap prop to those things i believe, also when its small duration doesnt take up the entire screen when it should

2023-03-25 22:26 UTC, Peyton-McKee commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx
> +          <FormControl sx={{ width: '95%' }}>
i would make these all full width and then add spacing between the grid items

2023-03-25 22:26 UTC, Peyton-McKee commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx
> +              sx={{ width: '140%' }}
huh? why 140% width

2023-03-26 21:52 UTC, Peyton-McKee requested changes
for the start date wrapping look up css ways to nowrap and truncate form labels in mui

2023-03-27 23:41 UTC, Peyton-McKee approved these changes
LGTM

2023-03-27 23:44 UTC, anthonybernardi approved these changes

2023-03-27 23:44 UTC, merged