#963 Alert if no Slack id
Northeastern-Electric-Racing/FinishLine pull request #1065
Opened 2023-03-28 14:37 UTC by Ray-kong

## Changes

Added a very annoying alert that tells users to set their slack ID which will show up whenever they open homepage.

## Notes

Also made minor changes to AppPublic.tsx

## Test Cases

- Logged in as Damien Wayne(has no slack ID set initially) and checked if there's an alert on the homepage.
- set up Damien Wayne's slack ID locally and went back to the homepage to see if it still gives an alert.
<img width="1351" alt="스크린샷 2023-03-28 오전 10 35 56" src="https://user-images.githubusercontent.com/58490052/228273375-2e0ed0f3-541e-4d2f-8230-7a75c3bb2827.png">
<img width="1463" alt="스크린샷 2023-03-28 오전 10 36 07" src="https://user-images.githubusercontent.com/58490052/228273412-8924560a-be60-4628-bef2-b07c2a699400.png">

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #963

2023-03-30 00:49 UTC, jamescd18 requested changes

2023-03-30 00:49 UTC, jamescd18 commented on src/frontend/src/app/AppPublic.tsx
> +    // otherwise, the user needs to login tmanually
```suggestion
    // otherwise, the user needs to login manually
```

2023-04-04 00:02 UTC, Peyton-McKee requested changes
W

2023-04-04 00:03 UTC, acd124 requested changes

2023-04-05 22:03 UTC, merged