#1025 heads
Northeastern-Electric-Racing/FinishLine pull request #1070
Opened 2023-03-29 23:41 UTC by nezamj03

## Changes

1. added heads role
2. changed file name to include all user utils
3. changed all instanced of user.role === X to use helpers
4. added HEAD seed data
5. changed some testing data roles
6. added some custom exceptions specific to making role exceptions (messages are easier too)

## Notes

did not add tests because essentially no role restrictions actually changed (only one instance but we test an extreme anyway)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ x] All commits are tagged with the ticket number
- [ x] No linting errors / newline at end of file warnings
- [ x] All code follows repository-configured prettier formatting
- [ x] No merge conflicts
- [ x] All checks passing
- [ x] Screenshots of UI changes (see Screenshots section)
- [ x] Remove any non-applicable sections of this template
- [ x] Assign the PR to yourself
- [ x] No `yarn.lock` changes (unless dependencies have changed)
- [ x] Request reviewers & ping on Slack
- [ x] PR is linked to the ticket (fill in the closes line below)

Closes # 1025

2023-03-30 01:18 UTC, anthonybernardi requested changes
pretty epic ngl

2023-03-30 01:18 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionsList.tsx
> +      {crReviewed === undefined && (auth.user ? !isGuest(auth.user.role) : false) ? (
what if we just made all these functions possibly take in undefined and if it's undefined it returns false or whatever

2023-03-30 01:18 UTC, anthonybernardi commented on src/backend/src/utils/errors.utils.ts
> +export class AccessDeniedAdminException extends AccessDeniedException {
I think calling this `AccessDeniedAdminOnlyException` would make more sense and be in line with the other ones

2023-03-30 05:01 UTC, nezamj03 commented on src/shared/src/user-utils.ts
> +  return isAtMostRank(role, 2);
clever

2023-04-06 00:16 UTC, anthonybernardi approved these changes
W

2023-04-08 21:45 UTC, anthonybernardi approved these changes

2023-04-08 21:45 UTC, merged