#992 projects page revamped
Northeastern-Electric-Racing/FinishLine pull request #1110
Opened 2023-04-21 03:00 UTC by nezamj03

## Changes

Added 3 pages - favorites, lead by, and in team. Only leadership or better has this view

## Notes

u gotta make the cards have consistent width / height because some of them are shorter and some are longer

## Screenshots
<img width="1440" alt="Screen Shot 2023-04-20 at 10 58 59 PM" src="https://user-images.githubusercontent.com/87815804/233530146-a0fde61f-d00c-4cab-b571-0213ec9f2abd.png">
<img width="439" alt="Screen Shot 2023-04-20 at 10 59 10 PM" src="https://user-images.githubusercontent.com/87815804/233530167-7ae7e120-fa71-4665-8e23-441ea30a4aa7.png">

<img width="470" alt="Screen Shot 2023-04-20 at 10 59 20 PM" src="https://user-images.githubusercontent.com/87815804/233530182-3050b2a5-768e-4a0c-8e89-353316e9820d.png">

<img width="327" alt="Screen Shot 2023-04-20 at 10 59 31 PM" src="https://user-images.githubusercontent.com/87815804/233530213-a6d4c4e3-c0a2-4c58-9702-7b1dcd4b008d.png">
<img width="1337" alt="Screen Shot 2023-04-20 at 11 00 00 PM" src="https://user-images.githubusercontent.com/87815804/233530261-adba67e5-a828-4b51-a838-3bcf4a42ec61.png">
<img width="1340" alt="Screen Shot 2023-04-20 at 11 00 14 PM" src="https://user-images.githubusercontent.com/87815804/233530285-03518ce3-c1c0-45c7-bd91-f4abf8a33790.png">

## To Do

look at notes

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x ] All commits are tagged with the ticket number
- [ x] No linting errors / newline at end of file warnings
- [ x] All code follows repository-configured prettier formatting
- [ x] No merge conflicts
- [ x] All checks passing
- [ x] Screenshots of UI changes (see Screenshots section)
- [ x] Remove any non-applicable sections of this template
- [ x] Assign the PR to yourself
- [ x] No `yarn.lock` changes (unless dependencies have changed)
- [ x] Request reviewers & ping on Slack
- [ x] PR is linked to the ticket (fill in the closes line below)

Closes # 992

2023-04-21 04:30 UTC, Peyton-McKee requested changes
I think we want these to be seperate sections on the same page so only two tabs with overview and all and then on overview we have three sections of favorited, as lead, and my teams projects or something

2023-04-21 04:30 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsFavorited.tsx
> +  const auth = useAuth();
useCurrentUser

2023-04-21 04:30 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsInTeam.tsx
> +  const auth = useAuth();
useCurrentUser

2023-04-21 04:30 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsInTeam.tsx
> +  const inTeamProjects = data?.filter((project) =>
this shouldnt be optional

2023-04-21 04:30 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsLeadOrManager.tsx
> +  const auth = useAuth();
useCurrentUser

2023-04-21 04:30 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsLeadOrManager.tsx
> +  const projectLeadOrManagerProjects = data?.filter(
this shouldnt be optional

2023-04-21 04:30 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsPage.tsx
> +  const auth = useAuth();
useCurrentUser

2023-04-21 04:30 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
> +    <Grid container xs={12}>
why does this need a grid container for one thing

2023-04-22 00:23 UTC, anthonybernardi requested changes
we're gonna want the tabs to be links too I think, see reid's pr for that

2023-04-22 00:23 UTC, anthonybernardi commented on src/frontend/src/pages/ProjectsPage/ProjectsPage.tsx
> +  return <>{isLeadership(auth.user.role) ? permissionView : noPermissionsView}</>;
i know the ticket says to but i think we should definitely not restrict this by role, everyone should see this but for guests the default tab should be the table (i think members can/should have favorites too)

2023-04-23 08:31 UTC, nezamj03 commented
> we're gonna want the tabs to be links too I think, see reid's pr for that

defo gonna be a tmr issue

2023-04-23 15:35 UTC, RChandler234 requested changes

2023-04-23 15:35 UTC, RChandler234 commented on src/frontend/src/pages/ProjectsPage/ProjectsPage.tsx
> +        </Grid>
Sorry, I think the ticket on this one was kind of unclear, we want all 3 of these sections to be displayed on the overview page like it is on the CR overview page that Sean just did

2023-04-24 02:54 UTC, anthonybernardi approved these changes
yurrrrrrr

2023-04-24 02:55 UTC, merged