#1126 Create Reimbursement Request Endpoint
Northeastern-Electric-Racing/FinishLine pull request #1141
Opened 2023-05-05 18:11 UTC by Peyton-McKee

## Changes

Made the create reimbursement endpoint

## Notes

No way to test because we need to make create vendor and create expense type which i can throw together in this PR if youd like

## Test Cases
<img width="1676" alt="Screen Shot 2023-05-05 at 2 07 20 PM" src="https://user-images.githubusercontent.com/113635669/236535450-cdeace68-4c9a-4e3c-96dc-67320a1299fb.png">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1126  (issue #)

2023-05-11 01:56 UTC, RChandler234 requested changes
Anthony + Reid wombo combo review

2023-05-11 01:56 UTC, RChandler234 commented on src/backend/src/utils/reimbursement-requests.utils.ts
> +    }
see if you can make these two checks any simpler

2023-05-11 13:02 UTC, Peyton-McKee commented on src/backend/src/controllers/reimbursement-requests.controllers.ts
> +import { NextFunction, Request, Response } from 'express';
none of these files have license statements

2023-05-11 13:03 UTC, Peyton-McKee commented on src/backend/src/controllers/reimbursement-requests.controllers.ts
> +      const createdReimbursementRequestId = await ReimbursementRequestService.createReimbursementRequest(
wym? instead of the Id?

2023-05-11 13:04 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +   * @param receiptPictures the links to the s3 buckets to retrieve the pictures
well what is this actually going to represent then?

2023-05-11 13:12 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +    receiptPictures: string[],
wym? this is a parameter?

2023-05-14 23:28 UTC, RChandler234 commented on src/backend/src/controllers/reimbursement-requests.controllers.ts
> +import { NextFunction, Request, Response } from 'express';
they should all have license statements 💀

2023-05-14 23:56 UTC, Peyton-McKee commented on src/backend/src/controllers/reimbursement-requests.controllers.ts
> +import { NextFunction, Request, Response } from 'express';
lol the entire backend does not have license statements it seems

2023-05-15 00:16 UTC, RChandler234 submitted a review, later dismissed

2023-05-15 00:16 UTC, RChandler234 commented on src/backend/src/routes/reimbursement-requests.routes.ts
> +  nonEmptyString(body('reimbursementProducts.*.name')),
you should verify reimbursementProducts is an array. Right now you can forget to pass it in the body, and the endpoint doesn't complain but it throws an uncaught exception in the backend when you try to validate the reimbursement products. 

Also, should we allow a reimbursement request to be submitted that has no associated reimbursement products? (aka an empty array for reimbursementProducts), probably not right?

2023-05-15 00:59 UTC, RChandler234 approved these changes
LGTM 🔥

2023-05-15 00:59 UTC, merged