#1124-wp-detail-revamp-changes-tab
Northeastern-Electric-Racing/FinishLine pull request #1159
Opened 2023-05-15 00:35 UTC by LOTaher

## Changes

Added the (soon to come) changes tab's content

## Notes

Removed everything else from the wp detail page. The content will just be put into the Changes tab

I did edit `ChangesList.tsx`, I do not think that should cause any problems though.

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/86690869/8b11db03-4012-43e9-8312-e4566ee0d09a)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/86690869/a8b20afb-175d-4732-9e60-505bccd30cdd)

## To Do

- [ ] Implement the tab content onto the actual tab once it's created

## Checklist

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #1124)

2023-05-15 01:45 UTC, LOTaher commented
Not sure how to properly fix lines 45-47 linting errors. If I delete those lines altogether, how should I go about changing the methods.

2023-05-15 01:48 UTC, LOTaher commented
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/86690869/25e2d969-5eae-4ae7-9563-e56506c8b71f)
Because I am using the ChangesList component with BulletList, there is still a title above the bullet points.

2023-05-15 01:56 UTC, Peyton-McKee requested changes
nice work! You dont need to delete the other stuff, once reids PR is merged all that stuff will still be used. Im also not sure what were gonna do about the header. I think well wait and see what it looks like with the tab and then adjust from there

2023-05-15 01:56 UTC, Peyton-McKee commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
> -      <WorkPackageDetails workPackage={workPackage} />
you should undo all the changes you made to this file I think...

2023-05-17 04:09 UTC, RChandler234 requested changes

2023-05-17 04:09 UTC, RChandler234 commented on src/frontend/src/components/BulletList.tsx
> +      <Typography variant="h3" sx={{ fontFamily: 'Oswald,sans-serif' }}>
I don't think you need this fontFamilty stuff, typography on its own should set the font correctly

2023-05-17 04:09 UTC, RChandler234 commented on src/frontend/src/components/BulletList.tsx
> +import { fontFamily } from '@mui/system';
remove unused imports

2023-05-17 04:09 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
>  import { isGuest, WbsElementStatus, WorkPackage } from 'shared';
remove unused import

2023-05-18 21:15 UTC, LOTaher commented
A new PR will be made under a branch that's base has the tabs implemented

2023-05-18 21:15 UTC, closed without merging