#1128 my reimbursement requests endpoint
Northeastern-Electric-Racing/FinishLine pull request #1193
Opened 2023-06-04 18:07 UTC by jonathan-chen10

## Changes

Add endpoint `/reimbursement-requests/me` to fetch all reimbursement requests whose recipientId matches the current user's.

## Test Cases

### Jest tests

- Test that the appropriate Prisma function has been called with the desired inputs.

### Postman tests

Did not write seed data, instead I manually made the reimbursement requests like so.
![Screen Shot 2023-06-04 at 1 47 31 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/23add209-d716-4ce3-899a-82db07eb8ee3)
![Screen Shot 2023-06-04 at 1 50 45 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/45a3a704-9556-406b-8aca-6940dd0c1731)
![Screen Shot 2023-06-04 at 1 52 47 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/d5805e60-1eab-4f3d-ae0f-8863c4d10288)

Database after inserting new reimbursement:
![Screen Shot 2023-06-04 at 2 03 14 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/b5b62b16-9fbd-4edc-9092-faaa01ffc307)

- TEST CASE 1: Calling endpoint when Authorization = 1 (match found)
![Screen Shot 2023-06-04 at 1 53 27 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/2fd98c51-0130-4cd5-a8bf-66daae0d41fd)
- TEST CASE 2: Calling endpoint when Authorization = 2 (match not found)
![Screen Shot 2023-06-04 at 1 53 39 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/f1006c89-e220-4de8-9e5b-c18200aee7d4)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1128

2023-06-05 01:48 UTC, Peyton-McKee requested changes
Looks Great! Lmk if you have any questions about merging megans PR, also depending on when you want to work on it next we may be able to merge her PR first

2023-06-05 01:48 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +  static async getUserReimbursementRequests(recipient: User): Promise<Reimbursement_Request[]> {
this should return a shared reimbursement request, you may need to merge megans branch into yours to get some of the shared types

2023-06-05 01:48 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +    return userReimbursementRequests;
your gonna have to use the transformer here

2023-06-05 04:57 UTC, RChandler234 requested changes

2023-06-05 04:57 UTC, RChandler234 commented on src/backend/src/routes/reimbursement-requests.routes.ts
> +reimbursementRequestsRouter.get('/me', ReimbursementRequestController.getUserReimbursementRequests);
let's do '/current-user' instead

2023-06-05 04:57 UTC, RChandler234 commented on src/backend/src/controllers/reimbursement-requests.controllers.ts
> +  static async getUserReimbursementRequests(_req: Request, res: Response, next: NextFunction) {
rename to getCurrentUserReimbursementRequests

2023-06-05 04:57 UTC, RChandler234 commented on src/backend/src/services/reimbursement-requests.services.ts
> +   * Returns all reimbursement requests in the database that are created by a user.
reword to 'created by the given user'

2023-06-05 04:57 UTC, RChandler234 commented on src/backend/src/services/reimbursement-requests.services.ts
> +  static async getUserReimbursementRequests(recipient: User): Promise<Reimbursement_Request[]> {
rename to getCurrentUserReimbursementRequests

2023-06-09 12:56 UTC, Peyton-McKee requested changes
looks great after that one change it should be good and then we might merge this into megans and then merge megans @RChandler234 ?

2023-06-09 12:56 UTC, Peyton-McKee commented on src/backend/tests/test-data/reimbursement-requests.test-data.ts
> +  account: Club_Accounts.CASH,
can you just cahnge the test data to be ClubAccount

2023-06-09 14:13 UTC, Peyton-McKee commented on src/backend/tests/test-data/reimbursement-requests.test-data.ts
> +  account: Club_Accounts.CASH,
nvm

2023-06-09 14:13 UTC, Peyton-McKee approved these changes
lgtm

2023-06-10 18:05 UTC, RChandler234 commented
> looks great after that one change it should be good and then we might merge this into megans and then merge megans @RChandler234 ?

yur

2023-06-10 18:17 UTC, merged