#1161 promote to member
Northeastern-Electric-Racing/FinishLine pull request #1204
Opened 2023-06-07 23:24 UTC by nezamj03

## Changes

changed updateUserRole to work for leadership

## Test Cases

- still need to write tests :'(

## Screenshots

<img width="829" alt="Screen Shot 2023-06-07 at 7 23 37 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/87815804/e0b2f914-aa76-41b7-a177-45a3912b1a4e">
<img width="831" alt="Screen Shot 2023-06-07 at 7 23 51 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/87815804/6526b75c-c886-4a39-b1bd-5f023dbc0134">

<img width="850" alt="Screen Shot 2023-06-07 at 7 22 15 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/87815804/7f6b591b-259c-4b1a-8a7b-56a617af1305">

## To Do

test but like it works....

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1161

2023-06-14 17:29 UTC, Peyton-McKee requested changes
Looks good just some organizational stuff

2023-06-14 17:29 UTC, Peyton-McKee commented on src/backend/src/services/users.services.ts
> +    if (user.role === RoleEnum.HEAD) {
make this one if statement and make the error be heads can only promote to leadership

2023-06-14 17:29 UTC, Peyton-McKee commented on src/backend/src/services/users.services.ts
> +      targetUser = await prisma.user.update({
delete

2023-06-14 17:29 UTC, Peyton-McKee commented on src/backend/src/services/users.services.ts
> +      targetUser = await prisma.user.update({
take this out of if statement because u do it regardless

2023-06-14 17:29 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx
> +            {!isAdmin(currentUser.role)
why not get rid of the ! and then flip the ternary order so that its not like a double negative

2023-07-11 01:14 UTC, RChandler234 approved these changes
LGTM

2023-07-11 01:14 UTC, merged