#1145 get all expense types
Northeastern-Electric-Racing/FinishLine pull request #1209
Opened 2023-06-11 17:07 UTC by Peyton-McKee

## Changes

Get All Expense Types Endpoint

## Screenshots

<img width="729" alt="Screen Shot 2023-06-11 at 1 06 54 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/113635669/5dc62306-85db-4ffb-aded-edc0e8dfc375">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1145 (issue #)

2023-06-11 23:21 UTC, ryanhowe28 submitted a review, later dismissed
Looks good to me

2023-06-13 05:24 UTC, RChandler234 requested changes
code looks good, will approve after this

2023-06-13 05:24 UTC, RChandler234 commented on src/backend/src/services/reimbursement-requests.services.ts
> +   * gets all the expense types in the database
ultra nitpick: Gets*

2023-06-14 19:43 UTC, RChandler234 approved these changes

2023-06-14 19:43 UTC, merged