#1133 - add approve reimbursement request endpoint
Northeastern-Electric-Racing/FinishLine pull request #1211
Opened 2023-06-12 04:51 UTC by RChandler234

## Changes

Add Approve Reimbursement Request Endpoint

## Notes

Not sure how to do tests since we're checking an environment variable when we check that a user is on the finance team (seems like that's why we don't have unit tests for send pending advisor list or add sabo number as well). Will look into this more later

## To Do

_Any remaining things that need to get done_

- [ ] tests?

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2023-06-12 12:02 UTC, Peyton-McKee requested changes
Looks prety good a couple small things that i noticed just browsing through the code

2023-06-13 14:27 UTC, Peyton-McKee requested changes
couple more things

2023-06-13 14:27 UTC, Peyton-McKee commented on src/backend/src/controllers/reimbursement-requests.controllers.ts
> +      const reimbursementStatus = await ReimbursementRequestService.approveReimbursementRequest(requestId, user);
you want to return the status not the request?

2023-06-13 14:27 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
>              type: 'PENDING_FINANCE',
Cant we do ReimbursementStatuses.Pending_Finance?

2023-06-13 14:27 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +   * @returns the reimbursement request with the sabo number
this conflicts with what your doing

2023-06-13 14:27 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +        type: 'SABO_SUBMITTED',
can we ReimbursementStatsusTpe.Sabo_Submitted here?

2023-06-13 14:27 UTC, Peyton-McKee commented on src/backend/tests/reimbursement-requests.test.ts
> +    });
successful test?

2023-06-21 23:30 UTC, anthonybernardi reviewed
awesome

2023-06-21 23:30 UTC, anthonybernardi commented on src/backend/src/prisma/schema.prisma
> +  reimbursementStatuses  Reimbursement_Status[]
the sql file says renamed without changes but this should probs cause a change right

2023-06-24 22:07 UTC, merged