#1049 wp create make blocked by autocomplete
Northeastern-Electric-Racing/FinishLine pull request #1235
Opened 2023-06-30 03:28 UTC by tigerhippo

## Changes

In the CreateWorkPackageForm file:
- Copy pasted code relating to the wbsNum from Mihir's PR

In the CreateWorkPackageFormView file:
- Updated code to account for the wbsNum passed in from the CreateWorkPackageForm file 
- Copy pasted FormControl section from Peyton's PR 
- Obtained the project with given wbsNum and then obtained the work packages for the project
- Made function blockedByToAutocompleteOption which shows how each work package option should be displayed in the autocomplete

## To Do

- Fix error (it doesn't seem to be occurring anymore, not sure why)
- yarn test:backend + frontend
- manually test on FinishLine
- Get rid of any comments
- Abstract common features between multiple autocompletes into an NERMultipleAutocomplete

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2023-06-30 04:35 UTC, RChandler234 requested changes

2023-06-30 04:35 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageForm.tsx
> +  wbsNum: string | null;
switch this to just string (my b)

2023-06-30 04:35 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +      wbsNum: null,
you can set the default value to the wbsNum that's being passed in as a prop

2023-06-30 04:54 UTC, RChandler234 requested changes

2023-06-30 04:54 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageForm.tsx
> +  const [wbsNum, setWbsNum] = useState(query.get('wbsNum') || '');
change this to query.get('wbs') (not your bad)

2023-07-02 14:11 UTC, RChandler234 requested changes

2023-07-02 14:11 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +  const { data: project } = useSingleProject(validateWBS(query.get('wbs') || ''));
replace query.get('wbs') || '' with wbsNum

2023-07-05 22:59 UTC, Peyton-McKee commented
other PR for this

2023-07-05 22:59 UTC, closed without merging