#1188 leads array and head added to team
Northeastern-Electric-Racing/FinishLine pull request #1237
Opened 2023-07-03 03:08 UTC by walker-sean

## Changes
Schema updated and codebase refactored so that teams have a head (in place of a single lead) and an array of leads

## Checklist
- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1188

2023-07-05 18:54 UTC, Peyton-McKee requested changes
just looked through this, @RChandler234 Idk if we want to do the lead validation stuff in this ticket or a different one

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/prisma/schema.prisma
> +  teamsAsLead               Team[]                  @relation(name: "teamsAsLead")
move this up with the other team relations, like just literally cut and paste it so that theyre all together

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/services/teams.services.ts
>      const newHeadTeam = await prisma.team.findFirst({
this is kinda confusing im realizing, can you put a comment before this saying, checking to see if any teams have the new head as their current head

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/utils/reimbursement-requests.utils.ts
> +export type UserWithTeam = User & { teamsAsMember: Team[] };
ugh im now realizing were gonna have to change all the checks to also include the teams leads on top of the members

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/utils/reimbursement-requests.utils.ts
> +    !user.teamsAsMember.some((team) => team.teamId === process.env.FINANCE_TEAM_ID) &&
for example here youd have to add && !userr.teamsAsLead.some(...)

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/utils/teams.utils.ts
> +  const members: number[] = team.members.map((user) => user.userId).concat(team.headId);
and here ud have to ad leads too

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/utils/teams.utils.ts
>   * @returns true or false
also the comment above should be or the team head

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/utils/teams.utils.ts
>   * Returns true if the user is the team lead or a team member
team head

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/utils/teams.utils.ts
> +  return team.headId === user.userId || team.members.map((user) => user.userId).includes(user.userId);
include team.leads here too

2023-07-05 18:54 UTC, Peyton-McKee commented on src/backend/src/utils/auth.utils.ts
> +  const user = await prisma.user.findUnique({ where: { userId }, include: { teamsAsMember: true } });
and here id include teamsAsLead as well

2023-07-07 15:07 UTC, Peyton-McKee requested changes
looks great this should be all the updated checks

2023-07-07 15:07 UTC, Peyton-McKee commented on src/backend/src/utils/reimbursement-requests.utils.ts
> +  if (
replace this with userOnTeam function

2023-07-07 15:07 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListComponents.tsx
> +    .concat(team.head)
concat team leads

2023-07-07 15:07 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListComponents.tsx
> +    const teamMembers = team.members.concat(team.head);
make a function that gets all the users on the team and then use it here and above.

2023-07-07 15:07 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListComponents.tsx
> +    .concat(team.head)
aka here

2023-07-07 15:07 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListNotesModal.tsx
> +        .concat(team.head)
also use it here

2023-07-07 15:07 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectsPage/ProjectsOverview.tsx
>        project.team?.members.map((member) => member.userId).includes(user.userId)
account for leads here

2023-07-07 15:07 UTC, Peyton-McKee commented on src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx
> +    .filter((user) => user.userId !== team.head.userId)
filter out leads as well

2023-07-10 17:29 UTC, Peyton-McKee requested changes
looking dope

2023-07-12 23:40 UTC, Peyton-McKee reviewed
can you see if you can just remove the UserWithTeam type and have everything use a normal user

2023-07-13 00:03 UTC, Peyton-McKee submitted a review, later dismissed
lgtm

2023-07-14 06:06 UTC, RChandler234 requested changes
I feel like a decent bit of this permissions stuff we might just have to tweak as the semester goes on and we get actual user data about who should have access to do what with our new role system

2023-07-14 06:06 UTC, RChandler234 commented on src/backend/src/utils/tasks.utils.ts
> +  if (task.wbsElement.project?.team?.headId === user.userId) return true;
I feel like it makes sense for leads to be able to edit tasks as well

2023-07-14 06:06 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
> +      await mutateAsyncSetProjectTeam(teamAsHeadId);
we could probably just switch the team to be checked in the backend in the future

2023-07-14 06:06 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskList.tsx
> +    project.team?.head.userId === user.userId;
same leads permissions comment as above

2023-07-14 06:06 UTC, RChandler234 commented on src/frontend/src/pages/ProjectsPage/ProjectsOverview.tsx
> +      project.team?.leads.map((lead) => lead.userId).includes(user.userId)
should probably make this a helper method

2023-07-14 21:37 UTC, Peyton-McKee commented on src/backend/tests/test-data/teams.test-data.ts
> +  leads: [batman, flash]
No same way a lead csnt be a member and a head cant be a member

2023-07-14 21:38 UTC, RChandler234 commented on src/backend/tests/test-data/teams.test-data.ts
> +  leads: [batman, flash]
Aight bet let's reinforce that as well then @walker-sean

2023-07-14 21:42 UTC, Peyton-McKee commented on src/backend/src/services/teams.services.ts
> +    if (team.leads.map((lead) => lead.userId).some((leadId) => userIds.includes(leadId)))
Yes

2023-07-14 21:42 UTC, Peyton-McKee commented on src/backend/src/services/teams.services.ts
> +    // checking to see if any teams have the new head as their current head
Yes they can be

2023-07-14 21:44 UTC, Peyton-McKee commented on src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx
> +      (project.team && project.team.teamId === user.teamAsHeadId) ||
Yeah can u make this that function we have sean

2023-07-14 21:45 UTC, Peyton-McKee commented on src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx
> +      (project.team && project.team.teamId === user.teamAsHeadId) ||
Oh wait except this should only he leads and heads

2023-07-16 23:19 UTC, RChandler234 approved these changes

2023-07-16 23:47 UTC, merged