1049: pulled newest changes from develop
Northeastern-Electric-Racing/FinishLine pull request #1239
Opened 2023-07-05 20:19 UTC by tigerhippo

## Changes

Pulled up to date code from develop and added my changes back in

## Test Cases

FinishLine starts up + yarn test:frontend and backend

## To Do

Manually test on FinishLine

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1049

2023-07-05 23:58 UTC, Peyton-McKee requested changes
Looks Great! just a couple cleanup things, I think you forgot to delete the wbsNum from the form, once thats finished it should be good

2023-07-05 23:58 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +  const { data: project } = useSingleProject(validateWBS(wbsNum));
add isLoading, isError and error and then validate all of that.

2023-07-05 23:58 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageForm.tsx
> +  wbsNum: string | null;
why did u add this

2023-07-05 23:58 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageForm.tsx
> +        const blockedWbsNum = validateWBS(blocker);
you can replace with with just validateWBS, so like blockedBy.map(validateWBS)

2023-07-05 23:58 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +      wbsNum: wbsNum,
why is this here

2023-07-05 23:58 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +  const workPackages = project ? project.workPackages : [];
check if !project return <LoadingIndicator/> plus check if isError error page and isLoading loading indicator

2023-07-08 14:22 UTC, anthonybernardi requested changes

2023-07-08 14:22 UTC, anthonybernardi commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +              console.log(option, value);
delete (and then the function can just be `(option, value) => option.id === value.id`

2023-07-08 14:22 UTC, anthonybernardi commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +              let change = blockedByOptions.find((o) => o.id === v);
const

2023-07-14 23:54 UTC, RChandler234 requested changes
when you have work packages selected, and then change the project, it crashes the frontend rn, I think you'll need to somehow clear the selected blocked bys whenever the project is changed.

2023-07-14 23:54 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +              const change = blockedByOptions.find((o) => o.id === v);
rename these variable from o and v, the name's or so vague that it's confusing

2023-07-14 23:54 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> -      <FormLabel>Blocked By</FormLabel>
add this back in, looks weird without it

2023-07-20 01:32 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +              const change = blockedByOptions.find((option) => option.id === value);
quick thing just delete the change thing to just be blockedByOptions.find...! and then delete the curly braces

2023-07-20 01:32 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +    setValue('blockedBy', [] as string[]);
dont you have to put this before setting the wbsNum

2023-07-21 05:33 UTC, RChandler234 approved these changes

2023-07-21 05:33 UTC, merged