#1216 edit reimbursement request
Northeastern-Electric-Racing/FinishLine pull request #1240
Opened 2023-07-08 04:25 UTC by Peyton-McKee

## Changes

Edit Reimbursement Request

## Notes

Looks Identical to create reimbursement request

## Screenshots
<img width="1728" alt="Screen Shot 2023-07-08 at 12 25 12 AM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/113635669/e1ca6fb0-259e-454f-959c-af1d9cc8733f">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1216  (issue #)

2023-07-15 05:03 UTC, RChandler234 requested changes
this stuff looks awesome, love how the form is abstracted, imo we should try to do that for the other forms where possible.

2023-07-17 02:48 UTC, Peyton-McKee commented on src/frontend/src/components/ActionsMenu.tsx
> +const ActionsMenu: React.FC<ActionsMenuProps> = ({ buttons }) => {
mm true

2023-07-17 02:49 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/EditReimbursementRequest.tsx
> +          name: `${fullNamePipe(reimbursementRequest.recipient)} - ${datePipe(
lmao thats what i had first

2023-07-17 02:49 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/EditReimbursementRequest.tsx
> +    console.log(filesToKeep);
oop

2023-07-17 02:50 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/EditReimbursementRequest.tsx
> +          dateOfExpense: new Date(reimbursementRequest.dateOfExpense),
true tbh before i did this i forgot frontend transformers were a thing

2023-07-17 02:51 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
> +  submitText: string;
uhhhh yes.... but i feel like thats kind of confusing?

2023-07-17 02:51 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> -        e.preventDefault();
i dont think it was doing anything

2023-07-17 02:58 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
> +  submitText: string;
Hrmm, maybe make submit text a boolean like isEdit or make it accept an enumeration with a set set of values. It's j weird to me to have a submit text prop that can take any string when a form will only ever be create or edit

2023-07-21 13:52 UTC, Peyton-McKee commented on src/frontend/src/apis/finance.api.ts
> +export const editReimbursementRequest = (id: string, formData: ReimbursementRequestEditArgs) => {
this is a shared type

2023-07-21 13:52 UTC, Peyton-McKee commented on src/frontend/src/apis/finance.api.ts
> +export const editReimbursementRequest = (id: string, formData: ReimbursementRequestEditArgs) => {
oh wait nvm

2023-07-21 14:58 UTC, Peyton-McKee commented on src/backend/src/utils/reimbursement-requests.utils.ts
> -export interface ReimbursementReceiptCreateArgs {
why make two identical props for frontend and backend when theyre the same thing

2023-07-21 15:09 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
>              <Stack key={receiptFile.file.name} direction="row" justifyContent="space-between">
huh? change what?

2023-07-21 15:11 UTC, Peyton-McKee commented on src/shared/src/types/reimbursement-requests-types.ts
> +export interface ReimbursementReceiptUploadArgs extends ReimbursementReceiptCreateArgs {
Im personally against renaming them from args to payload since theyre also used in the backend and they are all technically arguments

2023-07-21 18:22 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
>              <Stack key={receiptFile.file.name} direction="row" justifyContent="space-between">
change receiptFile.file.name to be receiptFile.name

2023-07-23 23:53 UTC, RChandler234 approved these changes

2023-07-23 23:53 UTC, merged