#1218 Finance Config
Northeastern-Electric-Racing/FinishLine pull request #1264
Opened 2023-07-27 02:44 UTC by walker-sean

## Changes

The frontend stuff is set up

## Notes

Need some endpoints done to add create/edit functionality

## Screenshots

<img width="1440" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/114596410/a48ecfd8-b17f-4a66-93ff-758cff0384e5">
<img width="666" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/114596410/92474d04-950e-4b2d-a458-f897ea5e2034">

## To Do

- [ ] Endpoints for editing vendors and expense types
- [ ] All hooks
- [ ] Integrating edit and create functionality

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1218

2023-07-27 03:47 UTC, callmejim1226 commented
I will be working on the expense type edit endpoint and push the work on this PR by tmr or soon.

2023-07-27 22:41 UTC, RChandler234 requested changes
<img width="432" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/29521172/0149be1f-cba3-4ab5-9d0d-ff0558a69364">
fix the gaps in the corners

2023-07-27 22:41 UTC, RChandler234 commented on src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx
> +      <AdminToolsFinanceConfig />
let's restrict this so only admins can see it

2023-07-27 22:41 UTC, RChandler234 commented on src/frontend/src/pages/AdminToolsPage/AdminToolsFinanceConfig.tsx
> +        {registeredVendors}
you can put the vendors table and the accountCodes table in their own files

2023-07-27 22:41 UTC, RChandler234 commented on src/frontend/src/pages/AdminToolsPage/AdminToolsFinanceConfig.tsx
> +            {newVendorRow}
this is tricky cause we need to be able to create new expense types, new account codes, and be able to edit account codes. I think doing it inline will be pretty tricky, for the mvp, I'd suggest making a modal pop up when you click on a row and then allow the user to make edits in there. 

Same for creating, I think buttons right under both of the tables that pops open a modal for creating a vendor or account code with inputs for all the data a user is inputting will be easier

Lmk if you have questions ab any of that

2023-07-30 00:05 UTC, callmejim1226 commented on src/frontend/src/pages/AdminToolsPage/EditAccountCodeView.tsx
> +  accountCode
I'm having an issue with updating accountCode.code variable after the user submits this modal with a new code variable. I wonder if we should use useState hook to get updated account code. Let me know if we have other way to get a new account number after user clicks submit button in the modal.

2023-07-31 01:22 UTC, RChandler234 approved these changes

2023-07-31 01:22 UTC, merged