#1146 resolve all CRs before making Activation or Stage Gate CR
Northeastern-Electric-Racing/FinishLine pull request #1273
Opened 2023-08-04 03:20 UTC by tigerhippo

## Changes

Added a check in the createActivationChangeRequest function in the change requests services file which throws an error if there are any change requests within this change request's work package that have not been reviewed yet. Added the same check in the createStageGateChangeRequest function in the services file.

## Test Cases

- Yarn test:backend + frontend all pass
- Yarn start works fine

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1146

2023-08-04 17:45 UTC, Peyton-McKee requested changes
looks good megan just some cleaning up

2023-08-04 17:45 UTC, Peyton-McKee commented on src/backend/src/services/change-requests.services.ts
> +      if (changeRequests[i].dateReviewed === undefined) {
u can just say if !changeRequests[i].dateReviewed)

2023-08-04 17:45 UTC, Peyton-McKee commented on src/backend/src/services/change-requests.services.ts
> +        throw new HttpException(400, 'please resolve all related change requests before proceeding');
capitalize please

2023-08-04 17:45 UTC, Peyton-McKee commented on src/backend/src/services/change-requests.services.ts
> +    const { changeRequests } = wbsElement;
this code is copy and pasted please make it a util function and use it in both places

2023-08-07 19:18 UTC, Peyton-McKee commented on src/backend/src/utils/change-requests.utils.ts
> +  for (let i = 0; i < changeRequests.length; i++) {
just return changeRequests.every((changeRequest) => changeRequest.dateReviewed))

2023-08-08 18:49 UTC, RChandler234 requested changes

2023-08-08 18:49 UTC, RChandler234 commented on src/backend/src/utils/change-requests.utils.ts
> + * Determines whether all the change requests for a work package have been resolved or not
Change this comment to be more accurate: Determines whether all the change requests in the array have been reviewed

2023-08-08 18:49 UTC, RChandler234 commented on src/backend/src/utils/change-requests.utils.ts
> + * @param wbsElement represents the given work package
update this too

2023-08-08 18:49 UTC, RChandler234 commented on src/backend/src/services/change-requests.services.ts
> +    if (!allChangeRequestsReviewed(changeRequests)) {
we should only check this for change requests that haven't been deleted yet (in both places). If a CR is deleted, it's basically in a resolved state

2023-08-11 05:51 UTC, RChandler234 requested changes
can you also wrap the mutateAsync call in the frontend in the activate wp modal with a try catch (like we do for stage gate rn), so it'll actually show a toast with the error when this error is thrown

2023-08-11 05:51 UTC, RChandler234 commented on src/backend/src/services/change-requests.services.ts
> +    changeRequests.filter((changeRequest) => !changeRequest.dateDeleted);
filter doesn't actually mutate the original array, it just returns an updated array, so you'll need to make a new variable and then call that in the if statement

2023-08-11 05:51 UTC, RChandler234 commented on src/backend/src/services/change-requests.services.ts
> +    changeRequests.filter((changeRequest) => !changeRequest.dateDeleted);
same here

2023-08-15 03:00 UTC, RChandler234 requested changes

2023-08-15 03:00 UTC, RChandler234 commented on src/backend/src/services/change-requests.services.ts
> +      throw new HttpException(400, 'Please resolve all related change requests before proceeding');
ok last change I promise. Can you make the error message have the wbsNum and name as well, so the error is very explicit. Would look like this:
<img width="530" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/29521172/174d9417-6605-42c2-b171-24ca38f2caa0">

2023-08-16 03:39 UTC, RChandler234 requested changes

2023-08-16 03:39 UTC, RChandler234 commented on src/backend/src/services/change-requests.services.ts
> +        `Please resolve all change requests related to ${carNumber}.${projectNumber}.${workPackageNumber} - ${wbsElement.name} before proceeding`
use wbsPipe here intead of individually pulling out each number (same below)

2023-08-16 22:15 UTC, RChandler234 requested changes

2023-08-16 22:15 UTC, RChandler234 commented on src/backend/src/services/change-requests.services.ts
> +        `Please resolve all change requests related to ${carNumber}.${projectNumber}.${workPackageNumber} - ${wbsElement.name} before proceeding`
u forgot to add the wbsPipe here as well

2023-08-16 23:17 UTC, RChandler234 approved these changes
LGTM !

2023-08-16 23:17 UTC, merged