#1306 - Add Date Delivered Box to RR Detail Page
Northeastern-Electric-Racing/FinishLine pull request #1311
Opened 2023-08-28 02:56 UTC by jonathan-chen10

## Changes

Add box to RR page.

## Notes

It's all alone on the left side, MUI Grid doesn't naturally allow for it to be centered but maybe there's a trick idk

## Test Cases

See screenshots.
- No Sabo (placeholder)
- Before delivery but after Sabo: (displays placeholder ---, I forgot to take screenshot but trust me)
- After delivery (date shows up)

## Screenshots

![Screen Shot 2023-08-27 at 10 51 10 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/4cde6879-7ea8-4880-899f-fe81b11b040a)
![Screen Shot 2023-08-27 at 10 51 18 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/7406fcd4-e6ea-45e9-babe-0ab9c7c2502a)
![Screen Shot 2023-08-27 at 10 54 23 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/59806366/b91de343-73cf-4b1e-86b1-894acfce9e27)

## To Do

- [ ] testing??? (why are there no finance frontend tests)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [ ] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1306

2023-08-28 03:27 UTC, Peyton-McKee requested changes
Nicee

2023-08-28 03:27 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
> +                  : '----'
This should be a function as we use it twice now

2023-08-30 00:01 UTC, RChandler234 requested changes

2023-08-30 21:44 UTC, RChandler234 approved these changes

2023-08-30 21:44 UTC, merged