#1287: Vender and Account Code Forms Enabled Submit Buttons
Northeastern-Electric-Racing/FinishLine pull request #1416
Opened 2023-09-14 16:49 UTC by sharonyang16

## Changes

Removed "disabled" props for the elements being returned in AccountCodeFormModal.tsx and CreateVendorModal.tsx and removed unnecessary variable (isValid) in both files.

## Notes

- Error pop ups and "if there's a problem with any for the form fields, the modal doesn't close" seems to be already implemented; once I deleted the disabled props and tried submitting an invalid form, they seemed to work as intended without any further implementation. 
- New Change Request form had it so the error would only pop up on the first field that was invalid (i.e. there is only one error that pops up even if there's multiple sections that aren't filled out) and it is the same case with the Create and Edit Account Code Forms. I left it as is so there's consistency, but if there should be an error under every invalid field, I can look into that.
- While testing the Edit Account Code Form, I noticed a bug; if the Edit Account Code Form is successfully submitted, when you click on it again, the form is autofilled with the old Account Code information (ex: if Account Code information X is what is currently there and you change successfully change it to Account Code information Y, when you click on it again, the Edit Account Code Form fields are auto-populated with information X instead of Y. Let me know if this was intended, if we should open a new ticket for this, etc.

## Screenshots
Tested the ways an error popup can be produced for each of the changed forms.

Create Vendor Form:
<img width="280" alt="New Vendor Submit Enabled" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/1004ecf2-dcaf-4c20-8fb7-8f358fae381c">
<img width="280" alt="New Vendor Error Popup" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/c2067b03-d3a9-4195-a384-46929df1b632">

Create Account Code Form:
<img width="540" alt="Create Account Code Submit Enabled" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/0ad9d295-99e5-46e6-8162-1a5fc08d88a3">
<img width="540" alt="Create Account Code Error 1" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/2fd85a05-b916-4412-b248-bd1fdb092c27">
<img width="540" alt="Create Account Code Error 2" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/a15f4157-f3af-4114-866a-6bd2944876c3">
<img width="540" alt="Create Account Code Error Popup 3" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/dd906de8-9d4c-4289-be62-2034d9553e02">

Edit Account Code Form:
<img width="540" alt="Edit Account Code Submit Enabled" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/7b04ec42-11ab-481e-b72c-373e77ad05ce">
<img width="540" alt="Edit Account Code Error Popup 1" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/b88a343a-46d6-4512-9ff7-a2337a3bbce3">
<img width="540" alt="Edit Account Code Error Popup 2" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/e754495e-0fb2-41e7-86ab-0e96f09ddf8d">
<img width="540" alt="Edit Account Code Error Popup 3" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/35514add-9548-4bad-83e2-3a397f23405e">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ x ] All commits are tagged with the ticket number
- [ x ] No linting errors / newline at end of file warnings
- [ x ] All code follows repository-configured prettier formatting
- [ x ] No merge conflicts
- [ x ] All checks passing
- [ x ] Screenshots of UI changes (see Screenshots section)
- [ x ] Remove any non-applicable sections of this template
- [ x ] Assign the PR to yourself
- [ x ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ x ] PR is linked to the ticket (fill in the closes line below)

Closes #1287

2023-09-16 15:28 UTC, tigerhippo reviewed
Great work on this Sharon! I think your code is correct, and you didn't need to write code for the errors because it was already there (so you're right about that). I don't think any of the bugs that you mentioned are due to your code, I think they've already existed. I'm going to check in with Reid about this and see if we should incorporate any into this ticket or if we should make new tickets for them.

2023-09-17 00:04 UTC, RChandler234 requested changes

2023-09-17 19:53 UTC, sharonyang16 commented on src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodeFormModal.tsx
> +  const { handleSubmit, control, reset } = useForm({
Thanks! Very helpful. I just pushed, it should produce error messages similar to the Reimbursement Request form now.

2023-09-18 19:43 UTC, RChandler234 requested changes

2023-09-18 19:43 UTC, RChandler234 commented on src/frontend/src/pages/AdminToolsPage/FinanceConfig/CreateVendorModal.tsx
>      resolver: yupResolver(schema),
can you update the schema in this file so that the error name is 'Vendor Name is Required' instead of 'Account Name is Required'

2023-09-18 19:54 UTC, RChandler234 approved these changes

2023-09-18 19:54 UTC, merged