536 cr creation sort the wbs dropdown
Northeastern-Electric-Racing/FinishLine pull request #1420
Opened 2023-09-14 18:42 UTC by superhvarn

## Changes

Added functionality for the CR create page to sort its dropdown for projects by wbs number

## Screenshots
<img width="626" alt="Screen Shot 2023-09-11 at 9 46 59 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/56454934/38952690-95a2-4f69-b71a-c7ba913e6ecc">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.

Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #536)

2023-09-14 19:00 UTC, RChandler234 requested changes

2023-09-15 04:21 UTC, z-roth commented on src/shared/src/validate-wbs.ts
> +export const wbsNumComparator = (wbsNum1: any, wbsNum2: any) => {
let's avoid using the `any` type here

2023-09-15 04:24 UTC, z-roth commented
@RChandler234 thoughts on including tests for the comparator?

2023-09-15 04:27 UTC, RChandler234 requested changes

2023-09-15 04:27 UTC, RChandler234 commented on src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
> +  wbsDropdownOptions.sort(wbsNumComparator);
You need to pass in a method into sort like this: .sort((a,b) => comparator(a.id, b.id) so you don't have to take out the ids in the comparator

2023-09-15 04:29 UTC, RChandler234 commented
> @RChandler234 thoughts on including tests for the comparator?

Ooo like unit testing our util methods, that's a good idea (would make a lot of good tickets as well)

2023-09-15 04:31 UTC, z-roth commented
@superhvarn lets add a test here for the comparator as well

2023-09-15 04:32 UTC, z-roth commented
@superhvarn lets add a test for the comparator here as well

2023-09-15 18:17 UTC, RChandler234 requested changes

2023-09-15 18:17 UTC, RChandler234 commented on src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
> +  wbsDropdownOptions.sort((a, b) => wbsNumComparator(a.id, b.id));
we should also rename these from a and b to wbsNum1, wbsNum2 to be more precise/accurate

2023-09-19 16:29 UTC, z-roth requested changes

2023-09-19 16:29 UTC, z-roth commented on src/frontend/src/tests/utils/validate-wbs.test.ts
> +    expect(wbsNumComparator('1.3.4', '1.1.3')).toBe(1);
can we add a case for differing car numbers? (the first digit)

2023-09-19 21:43 UTC, z-roth approved these changes

2023-09-19 21:43 UTC, z-roth commented
looks good to me! 💸

2023-09-20 02:20 UTC, walker-sean approved these changes
LGTM 🔥

2023-09-20 03:46 UTC, RChandler234 requested changes

2023-09-22 03:15 UTC, walker-sean submitted a review, later dismissed

2023-09-22 03:15 UTC, walker-sean commented on src/shared/src/validate-wbs.ts
> + * Compares two wbs numbers
Add that it's used to sort WBS nums in ascending order to make it extra clear

2023-09-22 23:17 UTC, RChandler234 approved these changes

2023-09-22 23:17 UTC, merged