"#1187": Heads can now edit project tasks
Northeastern-Electric-Racing/FinishLine pull request #1423
Opened 2023-09-15 03:14 UTC by TeeChenxing

## Changes

**Frontend:** Went into `src\frontend\src\pages\ProjectDetailPage\ProjectViewContainer\TaskList\TaskListTabPanel.tsx` and add `auth.user.role == 'HEAD' ||` on line 126. 

**Backend:** Went into `src\backend\src\services\tasks.services.ts` and added "heads," to the AccessDeniedException message "'Only admins, app admins, heads, task creators, project leads, project managers, or project assignees can edit a task'"

**Test:** Went into `src\backend\tests\tasks.test.ts` and changed the test on line 291 so that the test for the backend AccessDeniedException message passes. 

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/119642092/45a0b1b2-d215-4992-a47f-c6ebdea2802f)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/119642092/ec7e8c1e-821f-4881-9cef-95f2154d6eb6)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1187 (issue #)

2023-09-15 16:51 UTC, callmejim1226 commented on src/backend/src/services/tasks.services.ts
Good job on updating the message on the AccessDenidedException error in editTaskAssigness function. 

Can we also update the AccessDenidedException message in editTask and editTaskStatus functions since those are also task edit functions?

2023-09-15 16:53 UTC, callmejim1226 requested changes
Great job on resolving the issue and documenting your work in this PR!

I left one minor comment. Re-request another review after you resolve the comment :)

2023-09-16 17:32 UTC, callmejim1226 approved these changes
LGTM!

2023-09-17 00:30 UTC, RChandler234 requested changes
for some reason it's saying something about you adding a submodule in the PR? not sure what caused that you might have to close this PR, and make a new branch, remake the changes, and make a new PR to fix it

2023-09-17 02:07 UTC, closed without merging