#1289 change expense type to autocomplete
Northeastern-Electric-Racing/FinishLine pull request #1439
Opened 2023-09-17 19:54 UTC by haderie

## Changes

the create/edit reimbursement request form is now an autocomplete select
The create and edit forms functionality should be unaffected
## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots
<img width="513" alt="expenseTypeSmall" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/126923741/c53887b0-0c46-43dc-bcf8-00ab40e4675c">
<img width="1439" alt="expenseTypeLarge" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/126923741/3b4334ec-7299-4844-8e85-7ef6afb853ae">
## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1289

2023-09-18 23:35 UTC, ryanhowe28 approved these changes
Looks great!

2023-09-20 04:00 UTC, RChandler234 requested changes

2023-09-20 04:00 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                    <Autocomplete
ok so, you should use the NERAutocomplete component, but like lowkey, I like the way this one looks better 💀 . If you're cool with this ticket getting a lil more involved, could you change the NERAutocomplete to look like this then use it in this spot instead

2023-09-21 00:12 UTC, ryanhowe28 reviewed
Also try and see how it looks without the double "expense type" words when selecting. Don't know if the smaller red one is necessary.

2023-09-25 04:39 UTC, RChandler234 requested changes
Could you also make the NERAutocomplete look like the autocomplete with the native select you were using originally? I think it fits a lot better with the components we usually use than the way NERAutocomplete looks now

2023-09-25 04:39 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                        options={allExpenseTypes.map(expenseTypesToAutocomplete)}
because you call `allExpenseTypes.map(expenseTypesToAutocomplete)`, can you make it a variable and then call it in both places you use it?

2023-09-25 04:39 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                        onChange={(_event, newValue) => {
you can use a ternary operator inside a call of onChange to simplify this method.

2023-09-25 04:39 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                            onChange(newValue.label);
also you'll wanna use .id, not .label here

2023-09-25 04:39 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +    return { label: expense.name, id: expense.toString() };
should be expense.expenseTypeId

2023-09-25 04:39 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +  const expenseTypesToAutocomplete = (expense: ExpenseType): { label: string; id: string } => {
this variable name should be expenseType, not expense

2023-09-25 04:39 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                        size={undefined}
set this to small/medium and see how it looks, but I wouldn't set it as undefined like this

2023-09-28 00:06 UTC, ryanhowe28 submitted a review, later dismissed
Looks great! I think all the other auto completes look like they fit much better.

2023-09-30 02:29 UTC, RChandler234 approved these changes

2023-09-30 02:30 UTC, merged