#1310 enforce secure settings on create rr form
Northeastern-Electric-Racing/FinishLine pull request #1453
Opened 2023-09-19 15:48 UTC by sharonyang16

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2023-09-22 02:39 UTC, tigerhippo reviewed
This is phenomenal work Sharon! It looks good to me, keep it up!

2023-09-24 20:50 UTC, RChandler234 requested changes

2023-09-24 20:50 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +            <Link component={RouterLink} to={routes.SETTINGS}>
Let's make this link blue so it has better contrast against the orange. It's particularly hard to see in light mode: 
<img width="657" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/29521172/d5dedb02-6ea6-4316-837a-565b95542229">

2023-09-24 23:07 UTC, RChandler234 approved these changes
LGTM 🔥

2023-09-24 23:07 UTC, merged