#1195 Can only activate on mondays
Northeastern-Electric-Racing/FinishLine pull request #1454
Opened 2023-09-19 20:37 UTC by willturner106

## Changes

The work package activation form needed to only allow work package activation on Monday. I copied over the logic from work package creation form to disallow users from selecting any date that is not a Monday. Work package activation had previously stored the date as a string, so I changed the String to a date object to make it easier to work with. 

## Test Cases

I ran the website locally and tested submitting a work package activation, and verified that I was only allowed to select Monday dates. I also verified that changing the Date from a string to a Date object did not mess up form submissions.

## Screenshots

Its not super easy to tell in the screenshots but every date that isn't a monday is greyed out

![1195_1](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/e7e0a0e8-91ec-4643-89ff-d925fcce3cd0)
![1195_2](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/ce95e4d5-0039-473e-b694-3bb79e6d0722)
![1195_4](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/b03e9e2d-4932-4c71-b79e-da17a22ae50a)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1195

2023-09-22 03:07 UTC, tigerhippo requested changes
This looks great! Awesome job Jack, keep it up!

2023-09-23 02:59 UTC, tigerhippo reviewed
Looks great, one tiny change and you're good!

2023-09-23 02:59 UTC, tigerhippo commented on src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx
You can probably get rid of the defaultValues on line 64 and on line 71, do defaultValues: { confirmDetails: false, startDate: startDate } to simplify the code.

2023-09-24 23:02 UTC, RChandler234 requested changes
Looking good!

2023-09-24 23:02 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx
> +  const disableStartDate = (startDate: Date) => {
rename to isStartDateDisabled, it's a little more precise

2023-09-26 06:26 UTC, RChandler234 requested changes

2023-09-26 06:26 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModal.tsx
> +    defaultValues: defaultValues
you can shorten this to just defaultValues, typescript knows to match up the attribute name and the const you've declared in this file

2023-09-26 22:29 UTC, RChandler234 approved these changes

2023-09-26 22:30 UTC, merged