#1277 only proj reimbursement
Northeastern-Electric-Racing/FinishLine pull request #1477
Opened 2023-09-21 04:51 UTC by ScarlettBlaize

## Changes

Changed placeholder to "Select a Project" and a form label to "Project" in the reimbursement product table file

Removed the allWbsElements constant. Created a new constant, projectDropdown, to only show projects and not work packages in the dropdown menu

## Screenshots

![Screenshot 2023-09-21 004726](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/121060929/22c6fb09-8073-413e-b492-423054fa67c4)

![Screenshot 2023-09-21 004710](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/121060929/79a84338-98a3-4233-927f-0c7fc2c971e0)

<img width="554" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/34677361/40d2e54d-b280-4943-b6e7-fa045b02f35e">

Closes #1277

2023-09-23 22:12 UTC, ninest commented
Great work! Can you run `yarn lint` and make sure to make any changes required? The linting check is failing

2023-09-23 22:13 UTC, ninest commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Remove unsused imports. Seems like 

```
import { ClubAccount, ReimbursementProductCreateArgs, ReimbursementReceiptUploadArgs, WbsNumber } from 'shared';
```

can be changed to

```
import { ClubAccount, ReimbursementProductCreateArgs, ReimbursementReceiptUploadArgs } from 'shared';
```

2023-09-23 22:14 UTC, ninest commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
> +  const projectDropdown = allProjects.map((proj) => {
Can you rename this to something like `allProjectWbsElements` to keep it consistent with what was there previously?

2023-09-23 22:15 UTC, ninest requested changes
Everything looks good! Just a few small changes

2023-09-25 19:50 UTC, ninest approved these changes

2023-09-25 19:55 UTC, ninest approved these changes

2023-09-26 06:19 UTC, RChandler234 approved these changes
LGTM 🔥

2023-09-26 06:20 UTC, merged