#98 - Implement try/catch responses in controllers
Northeastern-Electric-Racing/FinishLine pull request #148
Opened 2022-08-27 02:23 UTC by jonathan-chen10

## Changes

There are two places `TypeError` shows up:

1. In functions like `createWorkPackage(req, res)` that have Express responses. In these cases the fix is straightforward: replace `TypeError` with the appropriate `res.status(40X)`. This is done in commit https://github.com/Northeastern-Electric-Racing/FinishLine/commit/dad227a34e7d0191fdc6273d8ab15cb3468a554c
1. In transformers like `userTransformer(user)` that return JSON data representing the user. This is either embedded within other transformers or sent to a controller that returns a `res`ponse. So our course of action is to **track all transformers** that rely at some point on `userTransformer` (the other problematics `teamTransformer` and `projectTransformer` also rely on `userTransformer`) and **try/catch `TypeError`s to return the appropriate response**.

## Notes

What if we treated all transformers as risky and not just the ones with `userTransformer`? This would make things more robust. All transformers except `authenticatedUserTransformer` rely on (and propagate errors from) `userTransformer` anyway. (`authenticatedUserTransformer` is only ever used in `logUserIn(req, res)`, so you can add the 400 error in there if you want).

We did not touch the transformers in `src/frontend/src/apis`, as they do not `throw new TypeError`.

## Test Cases

No tests yet. :( (Merging to working branch)

## To Do

Not sure how necessary these are. None of them are required for this fix to work.

- [ ] abstract out a helper function `tryUserTransformer(res, succResCode, failResCode)`
- [ ] decide on a standard for `res.status` vs `return res.status`, which is currently inconsistent (find and replace `try { res` vs `try { return res`)
- [ ] as in the Notes, be extra careful and add the try/catch to `authenticatedUserTransformer` too.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors
- [ ] No newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (if applicable)
- [ ] Remove any not-applicable sections
- [ ] Assign the PR to yourself
- [ ] PR is linked to the ticket
- [ ] No `package-lock.json` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack

2022-08-27 02:33 UTC, jamescd18 commented
I would agree with treating all back-end transformers as risky and try catching them. Front-end transformers are different tho so I think those should probably be left alone

2022-08-27 02:34 UTC, jamescd18 commented
The front-end transformers could also perhaps be renamed to "hydration" functions or something like that, since I believe that's their primary purpose, to "rehydrate" string data from JSON which primarily is dates

2022-08-27 03:05 UTC, jamescd18 reviewed
there isn't anything inherently wrong with this ticket, but I'd say yes to reducing copy pasted code and I've also noted a couple key things with this sorta exception handling.

2022-08-27 03:05 UTC, jamescd18 commented on src/backend/src/controllers/change-requests.controllers.ts
> +      return res.status(400).json({ message: e.message });
I don't think 400 is necessarily the appropriate code

2022-08-27 03:05 UTC, jamescd18 commented on src/backend/src/controllers/change-requests.controllers.ts
> +    if (e instanceof TypeError) {
I'm not so sure about the usage of TypeError. If you look up the docs it doesn't quite fit. If we think back to Java from fundies/OOD What we're missing is the different kinds of errors like illegal state, etc. Technically I think the ideal way is we subclass the Error object and make our own or something like that

2022-08-27 03:05 UTC, jamescd18 commented on src/backend/src/controllers/change-requests.controllers.ts
> +      return res.status(400).json({ message: e.message });
400 indicates client error, but I don't super recall precisely what error states are possible

2022-08-27 16:57 UTC, anthonybernardi commented
Why do the transformers check for null at all? As can be seen below, it doesn't even let you pass something that could be null into the transformers. We don't need the try catches at all, you can just delete the type errors in the transformers. I don't know why they were there to begin with.

![image](https://user-images.githubusercontent.com/63663597/187040243-c11befef-1509-4a06-a085-04cf12cc4753.png)

2022-08-27 16:59 UTC, anthonybernardi requested changes
no try catches, just delete the throws in the transformers. Other stuff is good though

2022-08-28 02:11 UTC, jonathan-chen10 commented
We decided to cancel this PR because we decided not to go the try/catch route. Instead, because the transformers can never accept `null` inputs, we will assume that Prisma will always pass good payloads to the transformers. We remove the `if (payload === null) throw new TypeError()` lines of the transformers in https://github.com/Northeastern-Electric-Racing/FinishLine/commit/cc42b46ef5df3870102070ba02586e8ad31d040c.

2022-08-28 02:11 UTC, closed without merging