#1300 Added error text to start date in work package edit
Northeastern-Electric-Racing/FinishLine pull request #1508
Opened 2023-09-22 01:57 UTC by naakjgf

## Changes

Added a user-friendly error message which pops up when a non-valid date is entered into the start date field of work package edit.

## Screenshots

![Uploading Screen Shot 2023-09-21 at 9.37.07 PM.png…]()
<img width="1728" alt="Screen Shot 2023-09-21 at 9 36 22 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/61c016f0-8d8b-42ca-b88b-1cfd9c26cb2c">
<img width="265" alt="Screen Shot 2023-09-21 at 9 27 27 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/a55b4549-acd8-4b5f-a1c5-55c7ef07b8b9">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1300 (issue #)

2023-09-22 03:05 UTC, walker-sean requested changes
Nice job so far!

2023-09-22 03:05 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx
> +                            ? 'Please enter a valid date (YYYY-MM-DD)'
You could include that detail in this message, but it would probably be better to make a new case

2023-10-02 20:52 UTC, naakjgf commented
What my 2nd commit looks like while working:
<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 32 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/9b508cf9-ab77-43fd-ac34-c2a83c89219e">

<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 24 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/ad4eae69-1ceb-4edb-b2d5-ff220f8ac2a7">

<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 14 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/8194dcf5-1563-42ef-926e-7227a4a6c86b">

<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 10 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/e89d1e4c-7881-4416-92bc-dd17bd24b1ba">

2023-10-02 20:53 UTC, naakjgf commented
What my 2nd commit looks like on the finishline website:

<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 32 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/1be4a49f-7bfd-4164-8450-1ef7e7d8ba78">

<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 24 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/3138f374-6564-45ad-b8e6-d828ebd82086">

<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 14 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/94aac9e4-d763-4a22-96d0-94e36f4b1988">

<img width="1728" alt="Screen Shot 2023-10-02 at 4 44 10 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120525697/e88b3502-edb3-458d-86b4-1ded98d48fb0">

2023-10-07 00:25 UTC, walker-sean requested changes
One small thing

2024-01-05 01:22 UTC, closed without merging