#1515 changed pageSize in TaskListDataGrid to a default value of 25, …
Northeastern-Electric-Racing/FinishLine pull request #1539
Opened 2023-09-23 17:28 UTC by kaiyangzheng

…also added 25 for to rowsPerPageOptions

## Changes

Show 25 tasks for TaskList table by default.

## Notes

Added 25 to rowsPerPageOptions

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/44937958/4d7db0e4-9025-4e07-a340-19a9b9984016)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/44937958/6d042c6d-e1e8-4ba7-b1b0-b34d78c40fcb)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1515

2023-09-24 23:51 UTC, ryanhowe28 approved these changes
Looks great!

2023-09-25 01:44 UTC, RChandler234 requested changes

2023-09-25 01:44 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListDataGrid.tsx
> -  const [pageSize, setPageSize] = useState(Number(localStorage.getItem(tableRowCount)));
So you shouldn't change this here, bc this doesn't save whatever choice they choose in localstorage like it did before. Instead you should change what this item is set to in localStorage to '25' when it hasn't been set yet in TaskListTabPanel

2023-09-26 06:08 UTC, RChandler234 approved these changes
LGTM  🔥

2023-09-26 06:09 UTC, merged