#965 Added team name to project page
Northeastern-Electric-Racing/FinishLine pull request #1540
Opened 2023-09-24 00:08 UTC by AShyamkumar19

## Changes
Added team name to the project page. 

_Explanation of changes goes here_
There are multiple teams in the Finishline data base that created projects. So every project is tagged with the creator of project
which is the team. 

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

![WIth title](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/88903298/4a4e1b3d-2532-487b-b9db-59eee52cc0a5)

![Screenshot 2023-09-23 160908](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/88903298/c4934db1-2ca2-4add-84b0-10d2b98d12dd)

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (#965 )

2023-09-24 21:59 UTC, zmar234 requested changes
Hey Aarav, projects can have multiple teams so the way it currently is can get really messy with multiple teams. Due to this, we think the teams should go into the details section. I think the best way to go about this is to have a **Teams:** like the other data points with all the teams listed under the Details header but above the grid with all the data. (It'll go where the blue arrow is)

![270138249-c4934db1-2ca2-4add-84b0-10d2b98d12dd](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/120137306/f0883f6d-fa4a-4635-9d70-6ede90a55ca5)

2023-09-24 22:28 UTC, walker-sean requested changes
Nice job so far! 
Your prettier (style) check is failing, so make sure to fix that for your next commit. This is usually fixed by doing ctrl/cmd + S if you have the Prettier extension on VSCode. 
As for your failing test, this is because the test is looking for a specific title, which you have changed, so this is a case where you need to update the test.

2023-09-24 22:28 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
> +    teamName = project.teams[0].teamName;
Make sure you display all teams, not just the first one.

2023-09-24 22:28 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
> +    teamName = project.teams[0].teamName;
Take a look at some examples in the codebase of how to construct a list from an array separated by commas

2023-09-27 17:48 UTC, zmar234 submitted a review, later dismissed
Looks good to me design-wise, great job!

2023-09-28 17:46 UTC, walker-sean requested changes
Nice work!

2023-09-28 17:46 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
> +            <DetailDisplay label="Teams" content={getProjectTeamsName(project)} paddingRight={1} />
Change the label to `"Team"` when the project has exactly one team

2023-09-30 19:57 UTC, walker-sean requested changes
Looks good, just one more thing

2023-09-30 19:57 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
> +              label={getProjectTeamsName(project).split(', ').length > 1 ? 'Teams' : 'Team'}
Use `project.teams.length` to get the number of teams

2023-10-01 17:07 UTC, walker-sean approved these changes
LGTM!

2023-10-04 18:56 UTC, merged