#1417 - get many work packages endpoint
Northeastern-Electric-Racing/FinishLine pull request #1548
Opened 2023-09-25 14:43 UTC by LOTaher

## Changes

Created a new work packages endpoint.

## Notes

Having trouble testing the endpoint. Still not too sure if the code works properly.

## To Do

- [ ] Write tests
- [ ] Test endpoints using Postman

## Checklist

- [x ] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #1417 )

2023-09-30 16:41 UTC, ryanhowe28 reviewed
Here is a video for how to use postman to check if your code is doing what its supposed to. https://www.youtube.com/watch?v=CgFTb_hKdEo
This looks good so far, I would recommend looking at the getManyTeams or Projects endpoints that are similar if you are having any trouble.

2023-10-13 21:06 UTC, RChandler234 requested changes

2023-11-11 23:28 UTC, RChandler234 requested changes

2023-11-11 23:28 UTC, RChandler234 commented on src/backend/src/services/work-packages.services.ts
> +    for (const wbsNum of wbsNums) {
you can do wbsNums.forEach() here, it's a bit cleaner

2023-11-11 23:28 UTC, RChandler234 commented on src/backend/src/services/work-packages.services.ts
> +      console.log(workPackage);
remove

2023-11-11 23:28 UTC, RChandler234 commented on src/backend/src/routes/work-packages.routes.ts
> +  body('wbsNums').exists().isArray(),
you shouldn't need .exists here

2023-11-11 23:54 UTC, RChandler234 approved these changes
LGTM 🔥

2023-11-11 23:54 UTC, merged