#1480: Shortened title on smaller screens
Northeastern-Electric-Racing/FinishLine pull request #1549
Opened 2023-09-25 18:21 UTC by mattrwang

## Changes

Got rid of "by NER" in the title when on mobile/smaller windows.

## Screenshots

<img width="301" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/26651751/cfb2d01b-a000-4093-ac2f-1a43306ce0b1">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1480

2023-09-26 03:05 UTC, walker-sean reviewed
Looks good!

@RChandler234 do we want this to be responsive or is it good this way?

2023-09-26 03:27 UTC, walker-sean requested changes
Can you make this responsive - as in, when the browser changes size, the title will change?

Also, that 550 is a "magic constant"/"magic number" which makes code harder to understand. Try to figure out a way to avoid using this number. If needed, give this constant a name so it's clear what the number is.

2023-09-26 23:20 UTC, walker-sean requested changes
Looks great! Love having it reactive like this. Just a few things to fix up

2023-09-26 23:20 UTC, walker-sean commented on src/frontend/src/layouts/NavTopBar/NavTopBar.tsx
> +    function handleResize() {
Make this an arrow function (using `=>`) inside the call to `addEventListener`

2023-09-26 23:20 UTC, walker-sean commented on src/frontend/src/layouts/NavTopBar/NavTopBar.tsx
> +import React from 'react';
Change to `import { useEffect, useState } from 'react';`

2023-09-26 23:20 UTC, walker-sean commented on src/frontend/src/layouts/NavTopBar/NavTopBar.tsx
> +  React.useEffect(() => {
Remove `React.`

2023-09-26 23:20 UTC, walker-sean commented on src/frontend/src/layouts/NavTopBar/NavTopBar.tsx
> +  const [width, setWidth] = React.useState(window.innerWidth);
Remove `React.`

2023-09-27 00:24 UTC, walker-sean submitted a review, later dismissed
LGTM!

2023-09-27 02:04 UTC, RChandler234 requested changes

2023-09-27 19:41 UTC, RChandler234 approved these changes
LGTM 🔥

2023-09-27 19:41 UTC, merged