#1489 remove any keyword from finance.hooks.ts
Northeastern-Electric-Racing/FinishLine pull request #1553
Opened 2023-09-26 00:36 UTC by UckTay

## Changes

Replaced the any keyword in src/frontend/src/hooks/finance.hooks.ts

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1489

2023-09-29 16:34 UTC, ninest submitted a review, later dismissed

2023-09-30 01:39 UTC, RChandler234 requested changes

2023-09-30 01:39 UTC, RChandler234 commented on src/frontend/src/hooks/finance.hooks.ts
> +  return useMutation<{ message: string }, Error, { name: string }>(
the first <{message: string}> should actually be a Vendor, the code here before was technically wrong

2023-10-02 15:19 UTC, ninest requested changes
Can you run prettier and fix the style issues?

2023-11-03 20:04 UTC, RChandler234 approved these changes
LGTM 🔥

2023-11-03 20:04 UTC, merged