#955: right-aligned actions menu on workpackages and change requests,…
Northeastern-Electric-Racing/FinishLine pull request #1557
Opened 2023-09-28 01:08 UTC by stephanie-xu

## Changes

Trash icon added to change requests page, added line between delete and other buttons in actions dropdown menus (on project page and workpackages page) and rightaligned dropdown menus for work packages and change requests page.

## Notes
Changed actions menu, which is also used by reimbursment request actions. Screenshots attached for new behavior of its dropdown menu (only change is right-alignment of actions menu).

## Screenshots
<img width="1280" alt="Screenshot 2023-09-27 at 8 41 40 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/000f0298-a2d3-459a-b5ed-693aff0f260b">
<img width="447" alt="Screenshot 2023-09-27 at 8 42 03 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/941be3b4-0288-47f2-bf6b-28d8f94dea50">
<img width="1280" alt="Screenshot 2023-09-27 at 8 42 23 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/3a0183aa-15ff-49db-a721-d997bfe29b59">
<img width="444" alt="Screenshot 2023-09-27 at 8 42 45 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/cda316d6-5434-42ee-b706-500d59253b98">
<img width="1280" alt="Screenshot 2023-09-27 at 8 43 34 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/072c5777-a1cd-497f-ba06-a260173bfdb1">
<img width="450" alt="Screenshot 2023-09-27 at 8 43 50 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/47b367e2-d191-42d2-babb-3419e2d5f093">
Reimbursement request details:
<img width="1280" alt="Screenshot 2023-09-27 at 9 06 59 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/ec21ddfc-ecc7-4162-960e-1f80e5b65f68">
<img width="449" alt="Screenshot 2023-09-27 at 9 07 29 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76175287/df602f0d-dd3c-4575-a7a3-78a0ae5a4304">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #955

2023-10-01 20:40 UTC, tigerhippo reviewed
This looks great Stephanie, awesome job! I'm gonna check in with Reid about a couple potential fixes, but you're good for now.

2023-10-29 21:27 UTC, ryanhowe28 approved these changes
Looks great!

2023-10-29 22:48 UTC, RChandler234 requested changes
You should also try to switch ProjectViewContainer and WorkPackageViewContainer to use ActionsMenu instead of what they currently use

2023-10-29 22:48 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
> +      <MenuItem onClick={handleAssignToMyTeam} divider={true}>
if the user isn't a head of a team, it doesn't show the divider correctly

2024-01-24 23:29 UTC, closed without merging