#1532 added seed data to orioles
Northeastern-Electric-Racing/FinishLine pull request #1561
Opened 2023-09-28 04:40 UTC by ScarlettBlaize

## Changes

Added 9 more "people" to the users.seed.ts file and then added those people to the orioles team in the seed.ts file

Closes #1532

2023-09-30 21:51 UTC, ninest approved these changes

2023-10-01 01:13 UTC, RChandler234 requested changes

2023-10-01 01:13 UTC, RChandler234 commented on src/backend/src/prisma/seed-data/users.seed.ts
> +  role: Role.ADMIN
members on a team should generally be at minimum a member and at max a head

2023-10-02 03:35 UTC, RChandler234 approved these changes
LGTM 🔥

2023-10-02 03:36 UTC, merged