#954: fixed bug with stage when editing workpackage
Northeastern-Electric-Racing/FinishLine pull request #1563
Opened 2023-09-29 05:16 UTC by meganlai27

## Changes

I edited the createChange function in the changes.utils.ts file, such that when the old value is null, it will not add a null stage when the new value is null. The stage change in workpackage-services file was also changed so that a null new stage will not return 'None'.

## Notes

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/144744548/c18d7dec-6f6a-42d4-8e29-2bdcd6b45a35)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/144744548/29bd5924-641d-4515-990b-15a2d3c13d4d)

When a workpackage is edited and the stage is not changed, it does not alert any changes to the stage.

## To Do

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #954

2023-10-01 19:51 UTC, tigerhippo reviewed
This looks great Megan! I'm gonna check in with Reid about something you might have to change, but for now you're all good.

2023-10-03 02:10 UTC, tigerhippo requested changes
Hi Megan! When an actual stage name is changed to the value 'NONE', the outputted change message should just say 'Deleted stage (stage name)' which would mirror 'Added stage (stage name)'. Everything else looks good.

2023-10-07 01:01 UTC, tigerhippo reviewed
This looks awesome Megan! I think it's good to merge :)

2023-10-08 02:10 UTC, RChandler234 approved these changes

2023-10-08 02:10 UTC, merged