#1328- work package redesign, activities and deliverables
Northeastern-Electric-Racing/FinishLine pull request #1571
Opened 2023-10-01 00:27 UTC by haderie

## Changes

Expected activities and deliverables look like the mock
## Test Cases

- Case A
- Edge case
- ...

## Screenshots
<img width="1440" alt="workPackage large" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/126923741/a8e2589f-b3a0-49a1-a649-c2c6eb82000d">
<img width="530" alt="workpackage small" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/126923741/60a5ff6f-03c2-4810-a818-fa1ce8b4cff4">

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1328

2023-10-05 00:17 UTC, ryanhowe28 approved these changes
Looks great!

2023-10-05 00:33 UTC, ryanhowe28 reviewed
Actually, I didn't realize that the mock had the button next to the title. I like the way you did it better tbh, I will ping in slack with Zack and others and see which way we wanna go.

2023-10-05 01:03 UTC, ryanhowe28 requested changes
see how it looks with an outline on the trash button

2023-10-06 17:07 UTC, ryanhowe28 approved these changes

2023-10-08 02:42 UTC, RChandler234 requested changes
Looking good!

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +  title: string;
title should be renamed to bulletName and be optional

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +      <Typography variant="h5">{title}</Typography>
We should handle adding the title in whatever form we call this component in, so can you remove this line

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +      <Grid item sx={{ my: 1, display: 'flex', flexDirection: 'row', flexWrap: 'wrap' }}>
ok so the way grids work are you have a <Grid container> with multiple <Grid item> components inside it. Each <Grid container> has 12 columns basically and you can set how many columns each <Grid item> takes up using <Grid item xs={12}> (this means that this item will take up 12 columns when the screen is xtrasmall size). Another example <Grid item xs={12} md={6}> (will take up 6 columns when the screen is medium size or bigger, and 12 columns if the screen size is xtrasmall)

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +        + Add {title}
you should just display 'New Bullet' if bulletName is undefined

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
> +        <ReactHookEditableList
you shouldn't edit this file, it's getting updated in another PR

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +      <Grid item sx={{ my: 1, display: 'flex', flexDirection: 'row', flexWrap: 'wrap' }}>
so you should be able to make this Grid a container with a columnSpacing prop to define the space between each grid item

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +              <Grid item sx={{ display: 'flex', flexDirection: 'column', marginRight: '20px' }}>
you can delete the fragment component you're using to wrap everything here, and just make this a grid item with these props: xs={12} md={6} lg={4} (shouldn't need any of the styling)

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +                <Grid item sx={{ display: 'flex', alignItems: 'flex-start', marginBottom: '20px' }}>
This should just be a Box, not a Grid

2023-10-08 02:42 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +                    sx={{ width: '340px' }}
This should be width: '100%'

2023-10-15 04:45 UTC, RChandler234 requested changes

2023-10-15 04:45 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
> +          bulletName="Deliverables"
should be "Deliverable"

2023-10-15 04:45 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
> +          bulletName="Expected Activities"
"Expected Activity"

2023-10-15 04:45 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
>        <Button
this should be an NERButton

2023-10-15 04:45 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +                  <DeleteForeverOutlinedIcon />
use the <Delete/> Icon

2023-10-15 04:45 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +          const formattedName = name
you should use the bulletName here instead of the name. 'name' is used to register the elements with the useform

2023-10-15 04:45 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +            <Grid item xs={12} md={6} lg={4}>
each of these grid items should have a unique key (can be made by doing {`${name}-${i}`}

2023-10-16 01:16 UTC, RChandler234 requested changes

2023-10-16 01:16 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +                  sx={{ mx: 1, color: 'red', marginLeft: '15px', borderRadius: '4px', outline: 'solid' }}
can you add a marginTop: '3px' to this sx so that the button is more inline with the textbox

2023-10-16 02:01 UTC, RChandler234 approved these changes
LGTM 🔥

2023-10-16 02:01 UTC, merged