#1479 added bom to schema
Northeastern-Electric-Racing/FinishLine pull request #1590
Opened 2023-10-04 01:44 UTC by walker-sean

## Changes

Added BOM enums and models to the prisma schema

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [ ] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1479

2023-10-04 01:46 UTC, Peyton-McKee commented on src/backend/src/prisma/schema.prisma
> +enum Unit {
I think unit should be a model that they can add to

2023-10-04 20:02 UTC, RChandler234 requested changes
you should delete the two migrations and make one new one that combines the changes from both of them

2023-10-04 20:13 UTC, RChandler234 requested changes

2023-10-04 20:13 UTC, RChandler234 commented on src/backend/src/prisma/schema.prisma
> +  modelId          String          @id @default(uuid())
this should be materialId, that's my b for putting it wrong in the ticket

2023-10-04 20:13 UTC, RChandler234 commented on src/backend/src/prisma/schema.prisma
> +  materialTypeName String
can you put these by the relations that they're for?

2023-10-04 20:13 UTC, RChandler234 commented on src/backend/src/prisma/schema.prisma
> +model Material {
you're missing manufacturerPartNumber on the Material model

2023-10-05 20:16 UTC, RChandler234 approved these changes
LGTM 🔥

2023-10-05 20:17 UTC, merged