#1533 create new team with 12 members
Northeastern-Electric-Racing/FinishLine pull request #1629
Opened 2023-10-12 00:26 UTC by AR619

## Changes
-Created a team in teams.ts in seed data 
-Created 12 users in users.ts in seed data
-Added all the users into the team in seed.ts

Made a team and added 12 users as a seed.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1533

2023-10-18 19:12 UTC, ninest submitted a review, later dismissed

2023-10-21 05:21 UTC, RChandler234 requested changes
Love it!

2023-10-21 05:21 UTC, RChandler234 commented on src/backend/src/prisma/seed-data/users.seed.ts
> +  role: Role.MEMBER
anyone being set as the head of a team should be at least Role.HEAD

2023-10-23 22:29 UTC, RChandler234 requested changes
you shouldn't have the .env file committed in this PR

2023-10-25 22:28 UTC, ninest approved these changes

2023-10-26 01:54 UTC, RChandler234 approved these changes
LGTM 🔥

2023-10-26 01:54 UTC, merged