#1657 Allowed product cost to be less than 1
Northeastern-Electric-Racing/FinishLine pull request #1664
Opened 2023-10-23 20:08 UTC by jessicayzhao

## Changes

Allowed products to be an item worth less than $1 in the create/edit reimbursement request form.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # 1657

2023-10-24 01:37 UTC, callmejim1226 submitted a review, later dismissed
LGTM! Great job!

2023-10-24 02:45 UTC, RChandler234 requested changes

2023-10-24 02:45 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
> +        cost: yup.number().required('Amount is required').moreThan(0, 'Amount must be greater than 0')
nitpicky: this should be .min(.01) because we don't want to allow someone to submit a cost that's less than a cent

2023-10-26 01:41 UTC, RChandler234 approved these changes

2023-10-26 01:41 UTC, merged