#1584 changed 'total owed' to 'currently owed' and fixed owed amount …
Northeastern-Electric-Racing/FinishLine pull request #1665
Opened 2023-10-23 21:51 UTC by qihongw08

## Changes

Changed total owed amount to currently owed amount by changing the const totalOwed to subtract the totalReceived amount. 

Changed the column name to "Currently Owed"

## Screenshots
<img width="1512" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/99198350/1ffe0769-7909-488b-9552-ceef61adb4d5">

<img width="569" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/99198350/99e191b3-183b-428d-8be3-7b4483d80288">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1584

2023-10-25 22:26 UTC, ninest submitted a review, later dismissed

2023-10-26 02:23 UTC, RChandler234 requested changes

2023-10-26 02:23 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +  const totalOwed =
variable name should be currentlyOwed

2023-10-26 22:14 UTC, qihongw08 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +  const totalOwed =
i changed it

2023-10-29 21:58 UTC, RChandler234 approved these changes
LGTM 🔥

2023-10-29 21:58 UTC, merged