#1666 Added error message for cost and description of products on finance form
Northeastern-Electric-Racing/FinishLine pull request #1669
Opened 2023-10-25 23:21 UTC by jessicayzhao

## Changes

Displays error messages below cost and description fields for products in finance form.

## Screenshots

<img width="1469" alt="Screenshot 2023-10-25 at 7 20 03 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/132928939/ed0e6344-d7ca-4087-a5e6-763dc296e381">

<img width="375" alt="Screenshot 2023-10-25 at 7 20 36 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/132928939/475c4124-679f-4288-9840-dbd23ee8ba20">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1666

2023-10-26 21:16 UTC, callmejim1226 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
> +                              {errors.reimbursementProducts?.[product.index]?.cost?.message}
I realized we get the following long non-user-friendly error msg under the cost box when we delete the whole value and try to rewrite the cost value. Can we fix this, so the cost box error msg stays the same as `Amount must be greater than 0`?

<img width="960" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/91857946/17a36d52-9a58-44d9-a02a-49e4eded7ed4">

2023-10-26 21:17 UTC, callmejim1226 requested changes
Great work!!

I left a few comments about the cost box error message and div usage.

2023-10-27 23:23 UTC, callmejim1226 approved these changes
LGTM! Great job 💯

2023-10-29 22:16 UTC, RChandler234 approved these changes
LGTM 🔥

2023-10-29 22:16 UTC, merged