#1580: added "Date Submitted to sabo" to reimbursement section
Northeastern-Electric-Racing/FinishLine pull request #1671
Opened 2023-10-26 00:25 UTC by bderbs30

…ered column

## Changes

Added a new column called Date submitted to sabo to the finance reimbursement request section and removed the date delivered column. Created a new util function to find the .dateCreated of the sabostatus object

## Test Cases
Ran the yarn:frontend test and it passed

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/085b014e-3056-49fd-bfae-b8e48fcc6bae)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/b3d777f9-88f1-4519-b313-e587d72df01f)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/26bf1c3f-5e7f-45db-963f-165ebe3e1ad6)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/230c7130-7d95-4335-8db1-8827166155c3)

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1580

2023-10-26 02:03 UTC, RChandler234 requested changes

2023-10-26 02:03 UTC, RChandler234 commented on src/frontend/src/utils/reimbursement-request.utils.ts
>      dateDelivered: reimbursementRequest.dateDelivered,
remove this line since it's unused now

2023-10-26 19:45 UTC, bderbs30 commented on src/frontend/src/utils/reimbursement-request.utils.ts
>      dateDelivered: reimbursementRequest.dateDelivered,
Committed the suggested changes.

2023-10-29 20:51 UTC, RChandler234 approved these changes
LGTM 🔥

2023-10-29 20:51 UTC, merged