#1641 other CRs from user popup
Northeastern-Electric-Racing/FinishLine pull request #1676
Opened 2023-11-01 17:43 UTC by sharonyang16

## Changes

Added a new component for the Tabs that will go on the bottom of the Change Request Details page and added the tab for other CRs submitted or reviewed by the submitter of the current CR.

## Notes

- Can't scroll through the popup: The seed data doesn't have enough CRs that would require scrolling for the pop up for this ticket's tab, but I tested the popup with cards for each of the seeded CRs and cards get cut off and you can't scroll through them.

## Screenshots

Collapsed - Full Screen
<img width="1440" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/3585033a-ba3b-4df1-9eff-e1fbd22231b2">

Open - Full Screen
<img width="1440" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/fa969118-3ba2-4a65-9c3d-adb1c509ea59">

Collapsed - Little Screen
<img width="490" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/5e12b371-cb90-48e7-af7d-4bd398d21bff">

Open - Little Screen
<img width="490" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/92332953/ddefeffc-fcf2-4e5a-a6fc-b6d9c4550592">

## To Do

_Any remaining things that need to get done_

- [ ] Be able to scroll through the popup window

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1641

2023-11-05 03:09 UTC, callmejim1226 commented on src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
>        )}
After running my local app, I've seen one potential issue with locating the popup tab as the fixed position at the bottom of the CR details page. It is hard for the users to click on `Implemented Changes` dropdown as shown in the screenshot b/c the space between the popup tab and its dropdown is small. 

What do we think bout this? I think we can fix this issue by adding the blank space before the popup tab line, so the user can scroll way down to see a full `Implemented Changes` dropdown section. 

<img width="960" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/91857946/7e4c20c3-5d79-4e97-bc96-b8d4244970c1">

2023-11-05 03:19 UTC, callmejim1226 commented on src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
> +      <Collapse in={tab !== 0}>{tab === 1 && displayCRCards(crFromSameUser || [])}</Collapse>
Good. I think we can keep `tab === 1` here for #1642 ticket work to be continued from this line.

2023-11-05 03:20 UTC, callmejim1226 commented on src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
> +
Let's delete this new line.

2023-11-05 03:21 UTC, callmejim1226 commented on src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
> +  const crFromSameUser = changeRequests?.filter(
Can we change this variable name to `crsFromSubmitter` to be more clear which CRs are these from?

2023-11-05 03:24 UTC, callmejim1226 commented on src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
> +        tab === value && setTab(0);
for a single body line code in the arrow function, we can remove { } and semicolon, ; to reduce the code. 

In other words, let's replace this onClick to the following: `onClick={() => tab === value && setTab(0)}`

2023-11-05 03:42 UTC, callmejim1226 requested changes
This is epic! New cool feature :)

I left a few comments on the details page layout issue and code in the popup tab file.

2023-11-07 21:39 UTC, callmejim1226 commented on src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
>        )}
As addressed in the Slack thread with Sharon, this issue will be resolved in #1639 since the details page redesign is getting rid of the dropdowns.

2023-11-07 21:41 UTC, callmejim1226 approved these changes
Looks good to me. Great job!

2023-11-15 22:32 UTC, RChandler234 requested changes

2023-11-15 22:32 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
> +      value={value}
can you make the tops of these tabs rounded using: `      sx={{ borderRadius: '16px 16px 0 0' }}`, I think it'll look a little better

2023-11-15 22:32 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
> +        {displayTab(1, `Other CR's from ${changeRequest.submitter.firstName} ${changeRequest.submitter.lastName}`)}
you can use the fullNamePipe here instead of pulling each name out individually

2023-11-15 22:32 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
> +  const crsFromSubmitter = changeRequests?.filter(
can you sort these by dateSubmitted, so the most recent CRs show up first

2023-11-18 19:40 UTC, RChandler234 approved these changes
LGTM 🔥

2023-11-18 19:40 UTC, merged