#1610 Added deny reimbursement request endpoint
Northeastern-Electric-Racing/FinishLine pull request #1686
Opened 2023-11-03 07:32 UTC by jessicayzhao

## Changes

Added a denied reimbursement status type and endpoint to allow someone from the finance team to mark a reimbursement request as denied.

## Test Cases

- Deny Reimbursement Request fails if Submitter not on Finance Team
- Deny Reimbursement Request fails if Finance Team does not exist
- Deny Reimbursement Request fails if the Request does not exist
- Deny Reimbursement Request fails if the Request has been deleted
- Deny Reimbursement Request fails if the request has already been denied
- Deny Reimbursement Request fails if the request has already been reimbursed
- Deny Reimbursement Request success

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1610

2023-11-05 04:07 UTC, callmejim1226 commented on src/backend/src/services/reimbursement-requests.services.ts
> +   * @param submitter the user who is approving the reimbursement request
Whoops, a typo here. `approving` --> `denying`

2023-11-05 04:41 UTC, callmejim1226 commented on src/frontend/src/utils/reimbursement-request.utils.ts
> +    case ReimbursementStatusType.DENIED: {
Nice catch here!

2023-11-05 04:46 UTC, callmejim1226 submitted a review, later dismissed
Awesome work on this new endpoint! 💯👍

2023-11-09 05:56 UTC, RChandler234 requested changes

2023-11-11 21:51 UTC, RChandler234 approved these changes
LGTM 🔥 Really good job

2023-11-11 21:51 UTC, merged