#1448 benjamin zhu add ability to edit vendors
Northeastern-Electric-Racing/FinishLine pull request #1688
Opened 2023-11-04 20:28 UTC by Bennyzhu1

## Changes

Added a "edit vendors" endpoint that allows a user to edit the name of their vendor

## Notes

One of the tests is not working, labeled. "Successfuly changes Vendors name"

## Test Cases

- User does not have sufficient privileges to edit
- the name that User wants to change already exists
- Name successfully changed
## To Do

- [ ] Fix Test

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1448

2023-11-09 17:17 UTC, callmejim1226 commented on src/backend/src/routes/reimbursement-requests.routes.ts
> +reimbursementRequestsRouter.post('/edit-vendors', nonEmptyString(body('name')), ReimbursementRequestController.editVendor);
We want to add the `validateInputs` function here when there's at least one input from this endpoint payload. The `validateInputs` function makes sure there is no error from the endpoint request.

2023-11-09 17:22 UTC, callmejim1226 commented on src/backend/src/routes/reimbursement-requests.routes.ts
> +reimbursementRequestsRouter.post('/edit-vendors', nonEmptyString(body('name')), ReimbursementRequestController.editVendor);
Also, let's update the endpoint path to `/:vendorId/vendors/edit` so we can get vendorId from `req.params` in the edit vendor controller function.

2023-11-09 17:29 UTC, callmejim1226 commented on src/backend/src/services/reimbursement-requests.services.ts
> +    console.log(vendorExists);
Whoops, don't forget to remove all consoles.log statement after debugging :)

2023-11-09 17:33 UTC, callmejim1226 commented on src/backend/src/services/reimbursement-requests.services.ts
> +    return vendor;
When we return the vendor object to the front end, we want to transform the type of it from `Prisma` to `Shared` type. To do this, we can wrap this vendor variable with `vendorTransformer`.

2023-11-09 17:34 UTC, callmejim1226 commented on src/backend/tests/test-data/reimbursement-requests.test-data.ts
> +  name: 'kfc'
I wanna have KFC. It's been a while ngl lol

2023-11-09 17:38 UTC, callmejim1226 requested changes
Great start!! Nice endpoint. 

I left some comments on service function documentation and route definition. 
Also, let's test this endpoint manually through `Postman` and provide a screenshot of the endpoint's successful case. Lmk if you have any questions about using `Postman`.

2023-11-21 02:39 UTC, callmejim1226 commented on src/backend/src/services/reimbursement-requests.services.ts
> +    if (!isAdmin(submitter.role)) throw new AccessDeniedAdminOnlyException('only Admins can edit vendors');
When I read the [ticket](https://github.com/Northeastern-Electric-Racing/FinishLine/issues/1448), it says the finance leads and heads can also edit vendors. Can we add this permission on this line?

2023-11-21 02:45 UTC, callmejim1226 commented on src/backend/tests/reimbursement-requests.test.ts
> +      expect(vendor.name).toBe('kfc');
Can we also add an expected line where it checks the Prisma.vendor.update has been called 1 time? This is a way we test if our endpoint works as we expected by using Prisma ORM.

For example, we can refer to `toggles successfully` test case in projects.tests.ts

2023-11-21 02:46 UTC, callmejim1226 commented on src/backend/tests/reimbursement-requests.test.ts
> +    test('Throws error if user isnt an admin', async () => {
Let's update this test name after we update the permission in the service function.

2023-11-21 02:48 UTC, callmejim1226 commented on src/backend/tests/reimbursement-requests.test.ts
> +    test('Vendor Name already exists', async () => {
Small thing, but let's change this test name to 'Throws error if the vendor name already exists', so we can have consistent test names

2023-11-21 02:49 UTC, callmejim1226 requested changes
Great work! Left a few comments on the service function and tests. Almost there! 👍

2023-11-22 03:08 UTC, callmejim1226 commented on src/backend/src/services/reimbursement-requests.services.ts
> +    if (!isHead(submitter.role)) throw new AccessDeniedAdminOnlyException('only Admins and Heads can edit vendors');
From the ticket description, only the general admin or finance team head/leads can edit vendors. In other words, we want to check if the submitter.role is at least in an admin role, or if the submitter is in the finance team as a lead or head.

2023-11-22 03:10 UTC, callmejim1226 commented on src/backend/tests/reimbursement-requests.test.ts
> +    test('Throws error if user isnt an admin or head', async () => {
Let's update the test name to say if the user isn't an admin or finance leads/head

2023-11-22 03:10 UTC, callmejim1226 requested changes
Almost there! 👍

2023-11-23 20:41 UTC, callmejim1226 commented on src/backend/src/services/reimbursement-requests.services.ts
> +    if (!isAdmin(submitter.role)) {
Almost there! To properly check the user permission for the edit vendors, let's do the following:
1. use `await validateUserIsPartOfFinanceTeam(submitter);` to first check if the user is in finance team as either lead or head by using try and catch.
2. In a case when the user is not in finance team, then we just check if the user's role is at least admin. (in a catch case of try & catch). Note that if `!isAdmin(submitter.role)` is true, then we know `!isHead(submitter.role)` is true. You can take a look at the definition of these permission check utils functions.
3. Lastly, if the user is not at least an admin, then we gonna throw the AccessDenied exception, where the msg will be only the admin or finance lead or head can edit vendors.
4. Make this permission check as a helper method in RR utils file. Similar example can be found here for edit RR user permission check: https://github.com/Northeastern-Electric-Racing/FinishLine/pull/1672/files#diff-fc838d062bcc6c9ab4a0798a759ab857af3bb5e94e9ef0485d0881a9a19eef63

2023-11-23 20:44 UTC, callmejim1226 requested changes
After the user permission check fix, this PR should be good to go for the final review from Reid.

2023-11-28 00:03 UTC, RChandler234 approved these changes
LGTM 🔥

2023-11-28 00:03 UTC, merged