#1526 edit material endpoint
Northeastern-Electric-Racing/FinishLine pull request #1701
Opened 2023-11-11 04:48 UTC by callmejim1226

## Changes

Added material edit endpoint in 
- project routes
- project controller
- project service

## Notes

This is a draft PR. Need to figure out how to update the optional properties, assembly and quantityUnit. I get type conflict error right now (commented them for now).

**Screenshot of the error:**
<img width="764" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/91857946/db3f91b4-f015-4def-9361-9024be33048e">

## Test Cases

TBA

## Screenshots

TBA

## To Do

_Any remaining things that need to get done_

- [ ] Fix type conflict error on `assembly` and `quantityUnit` props in `Prisma.material.update`
- [ ] Add tests for the edit material endpoint
- [ ] Add screenshots of the successful run on endpoint from Postman

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2023-11-11 23:43 UTC, RChandler234 requested changes
look at the create material endpoint to make sure you're doing all the same checks it does there

2023-11-11 23:43 UTC, RChandler234 commented on src/backend/src/routes/projects.routes.ts
> +  nonEmptyString(body('unitName')),
should be optional

2023-11-11 23:43 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
> +    assembly?: Assembly,
should be assemblyId - string

2023-11-11 23:43 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
> +    quantityUnit?: Unit
this isn't an input, we get the unit, from the unitName which acts as the id for a unit

2023-11-11 23:43 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
> +    unitName: string,
should optional, this is what you use to connect the quantity unit, it's a bit confusing name

2023-11-11 23:43 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
> +        //   connect:
I believe you can set assemblyId and unitName directly and it should work the same, while avoiding this issue you're having

2023-11-11 23:45 UTC, RChandler234 requested changes

2023-11-11 23:45 UTC, RChandler234 commented on src/backend/src/routes/projects.routes.ts
> +  '/bom/material/:wbsNum/edit',
apologies, this should be :materialId, and then you should use that to fetch the material/ check if it exists in the service method. You should be able to get the wbsNum from that material that you fetch, it shouldn't be changing after a material has been created

2023-11-14 07:10 UTC, RChandler234 requested changes

2023-11-14 07:10 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
> +
you also need all these checks from the createMaterialEndpoint, I'd recommend putting them into a helper method or smthn:
```
    if (assemblyId) {
      const assembly = await prisma.assembly.findFirst({ where: { assemblyId } });
      if (!assembly) throw new NotFoundException('Assembly', assemblyId);
    }

    const materialType = await prisma.material_Type.findFirst({
      where: { name: materialTypeName }
    });
    if (!materialType) throw new NotFoundException('Material Type', materialTypeName);

    const manufacturer = await prisma.manufacturer.findFirst({
      where: { name: manufacturerName }
    });
    if (!manufacturer) throw new NotFoundException('Manufacturer', manufacturerName);

    const unit = await prisma.unit.findFirst({
      where: { name: unitName }
    });
    if (!unit) throw new NotFoundException('Unit', unitName);
```

2023-11-14 07:10 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
> +        pdmFileName: pdmFileName || undefined
you don't need `: assemblyId || undefined` for that one or pdfmFileName, you can just write assemblyId and it'll do the || undefined for you

2023-11-16 01:47 UTC, walker-sean commented
Tangentially related - could you please change material names to **not** be unique in the schema

2023-11-19 05:25 UTC, RChandler234 submitted a review, later dismissed

2023-11-19 05:31 UTC, RChandler234 approved these changes
LGTM 🔥

2023-11-19 05:31 UTC, merged