#1604 Archivable Teams Edit Schema
Northeastern-Electric-Racing/FinishLine pull request #1709
Opened 2023-11-16 02:12 UTC by tigerhippo

## Changes

I added two new optional fields: dateArchived and userArchived, to the Team type in the Prisma schema. I also had to add a third new optional field, userId, because the relation for userArchived needed it. I then ran 'yarn prisma:migrate' and added a descriptive name for the migration.

## Test Cases

- yarn test:backend + frontend pass all test cases
- the migration I can see is consistent with the time it was done and the name I gave it
<img width="506" alt="Screen Shot 2023-11-15 at 9 10 05 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/60333735/fd8a9499-56b3-4507-88fe-3f8c0df31180">
- yarn start lets me run the FinishLine app and view it in a tab with no problems

## Checklist

- [X] All commits are tagged with the ticket number
- [X] No linting errors / newline at end of file warnings
- [X] All code follows repository-configured prettier formatting
- [X] No merge conflicts
- [X] All checks passing
- [X] Screenshots of UI changes (see Screenshots section)
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #1604

2023-11-24 02:51 UTC, RChandler234 requested changes

2023-11-24 02:51 UTC, RChandler234 commented on src/backend/src/prisma/schema.prisma
> +  userId       Int?
this should be userArchivedId

2023-11-27 21:08 UTC, RChandler234 requested changes

2023-11-27 21:08 UTC, RChandler234 commented on src/backend/src/prisma/schema.prisma
> +  Team                      Team[]
can you rename this to archivedTeams, and add a name to the relation on the team and use that with @relation(name: "name") here

2023-11-27 21:08 UTC, RChandler234 commented on src/backend/src/prisma/migrations/20231127023813_team_with_user_archived_fixed/migration.sql
> +-- DropForeignKey
can you delete both of these migrations and generate a new one that has all the changes in one migration

2023-11-30 03:42 UTC, merged

2023-11-30 03:43 UTC, tigerhippo commented
Awesome!