#1574: autocomplete added (first attempt)
Northeastern-Electric-Racing/FinishLine pull request #1769
Opened 2024-01-12 07:13 UTC by martin0he

## Changes

I replaced the MUI Select with the NERAutocomplete component.

## Notes

When I tried to create a reimbursement form, it returned an error "Failed to Upload Receipt(s): No access, refresh token, API key or refresh handler callback is set."

## Screenshots

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1574

2024-01-12 23:55 UTC, walker-sean requested changes
Looking good!

2024-01-12 23:55 UTC, walker-sean commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +  const vendorsToAutocomplete = (vendorName: Vendor): { label: string; id: string } => {
change vendorName to just vendor because it is of type Vendor

2024-01-12 23:55 UTC, walker-sean commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                      value={mappedVendors.find((vendorName) => vendorName.id === value) || null}
find() already returns undefined if a value is not found, so the || null is not needed

2024-01-12 23:55 UTC, walker-sean commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                      placeholder=""
Add a placeholder that says Select Vendor

2024-01-18 05:09 UTC, RChandler234 requested changes

2024-01-18 05:09 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                      value={mappedVendors.find((vendor) => vendor.id === value)}
you do actually need the null, when it returns undefined, the frontend crashes with an error, so I had to add that in for account code a while ago

2024-01-18 20:52 UTC, RChandler234 approved these changes
LGTM 🔥

2024-01-18 20:52 UTC, merged