#83 - Display Page Proposed Solutions Visual
Northeastern-Electric-Racing/FinishLine pull request #191
Opened 2022-09-09 01:19 UTC by Ari-S-123

## Changes

Standard CRs now have a list of proposed solutions displayed on the details page.

## Screenshots (if applicable)

![Screenshot 2022-09-08 211307](https://user-images.githubusercontent.com/80832201/189252145-098c60bb-1e9a-4154-a4b7-6ed4d49572b2.png)

![Screenshot 2022-09-08 211326](https://user-images.githubusercontent.com/80832201/189252156-ab90650e-2802-49bc-a168-2dfbdf39f6d8.png)

## To Do

_Any remaining things that need to get done_

- [ ] Unit Testing

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors
- [ ] No newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (if applicable)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] PR is linked to the ticket
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack

Closes #83

2022-09-09 05:29 UTC, jamescd18 commented
I think the third image looks really gross for a UI. I think it looks worse to be displaying proposed solutions via read only form inputs. I also don't think it makes any sense because the form inputs will never not be read only

2022-09-09 23:05 UTC, anthonybernardi requested changes
yeah I agree with James' review that they shouldn't be read only inputs. Just display them normally as text. I think this will require making a new component (like a ProposedSolutionView and changing the other one to ProposedSolutionForm or something).

I also agree with James that this is probs where we should remove the budget/timeline/scope aspect for CRs that now don't matter

2022-09-15 04:37 UTC, RChandler234 submitted a review, later dismissed

2022-09-15 14:29 UTC, anthonybernardi requested changes
In addition to my other comment two more things:
1. the add new proposed solution button shouldn't show up if the cr has already been reviewed (approved or denied)
2. unused import in ChangeRequestDetailsView.test.tsx

2022-09-15 14:29 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx
> +              <Form.Label>Description</Form.Label>
these labels should show up as white in dark mode

2022-09-17 18:01 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionsList.tsx
> +          flexDirection: 'column-reverse'
This is too much to have inline like this, I'd either make a style object than just call it here, or move this stuff into  a css file

2022-09-18 13:48 UTC, anthonybernardi reviewed
the pill shouldn't be on a separate row, that's how it looks rn. ALso I think we should copy Kevin's layout for each proposed solution

2022-09-19 19:25 UTC, anthonybernardi commented
<img width="1021" alt="Screen Shot 2022-09-19 at 3 24 58 PM" src="https://user-images.githubusercontent.com/63663597/191099020-cc923af4-2a46-4318-b53a-e50c5bfa6445.png">
screenshot of changes i made to make it spaced better

2022-09-20 18:22 UTC, merged