#1926: Added My Name to credits
Northeastern-Electric-Racing/FinishLine pull request #1931
Opened 2024-01-24 19:18 UTC by BenjiKataoka

## Changes

Changed the credits page to include my name

## Notes
N/A

## Screenshots
<img width="1728" alt="Screenshot 2024-01-24 at 2 16 37 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/113647358/cf7746ed-922a-401c-b8eb-64d2f6e5c30a"

<img width="493" alt="Screenshot 2024-01-24 at 2 17 56 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/113647358/867abe83-71b0-46d2-9782-f5b0ba262407">
>

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1926

2024-01-24 19:23 UTC, martin0he approved these changes
make sure to tick off everything on the checklist before pinging for a review. also, make sure you only ping **tech leads or higher** for a review. otherwise, great job keep it up

2024-01-24 21:00 UTC, RChandler234 requested changes

2024-01-24 21:00 UTC, RChandler234 commented on .env
> +DATABASE_URL="postgresql://postgres:docker@localhost:5432/nerpm?schema=public"
don't include this file in the PR

2024-01-29 22:19 UTC, BenjiKataoka commented
I hope I fixed everything wrong with my ticket

2024-01-30 13:41 UTC, martin0he commented
good job fixing the files, now all u have to do is fix the merge conflict. this means that your current working branch is out of date with the main develop branch. in your branch cmd, run git pull develop to update your current working branch.

2024-01-30 18:06 UTC, RChandler234 commented
> good job fixing the files, now all u have to do is fix the merge conflict. this means that your current working branch is out of date with the main develop branch. in your branch cmd, run git pull develop to update your current working branch.

I can just take care of the merge conflict

2024-01-30 18:10 UTC, RChandler234 approved these changes
LGTM 🔥

2024-01-30 18:10 UTC, merged