#1812 Added my name to credits
Northeastern-Electric-Racing/FinishLine pull request #1947
Opened 2024-01-24 22:21 UTC by YPAndrew0907

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-01-24 22:37 UTC, ryanhowe28 requested changes
Can you put your name at the bottom. Also fill out the pull request form with your changes and screenshots of your change on the page.

2024-01-25 01:40 UTC, YPAndrew0907 reviewed
Name added at the last 

![Image 2024-1-24 at 20 39](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/98450999/94c4b01e-086e-4d5e-bbe5-227243924fd5)

2024-01-25 03:59 UTC, jackturner106 reviewed
This looks great, I really like the gradient! I did leave one small change, other than that it looks good.

2024-01-25 03:59 UTC, jackturner106 commented on src/frontend/src/pages/CreditsPage/CreditsPage.tsx
> +      name: ' Yipeng (Andrew) Wang',
Could you remove the space before your name?

2024-02-03 16:11 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-03 16:11 UTC, merged