#1954 Added my name to credits.
Northeastern-Electric-Racing/FinishLine pull request #1959
Opened 2024-01-24 23:58 UTC by tanisharajgor

## Changes

Added my name to the credits page.

Closes #1954

2024-01-25 23:03 UTC, Aaryan1203 requested changes
You want to remember to fill out the PR template. That includes a description of what you did as well as a screenshot of the website with your changes

2024-01-25 23:03 UTC, Aaryan1203 commented on src/frontend/src/pages/CreditsPage/CreditsPage.tsx
> +    }
Great work!

2024-01-26 02:12 UTC, tanisharajgor commented
> You want to remember to fill out the PR template. That includes a description of what you did as well as a screenshot of the website with your changes

Apologize about that, here is the updated description:

**Description:**
Added my name to the credits page, with a light purple color and white, muted glow effect. 

**Fullscreen View**:
<img width="1432" alt="Fullscreen" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/54627422/9a405507-8156-479a-85dc-ea330189f82b">

**Smallest Window View**:
<img width="491" alt="SmallestWindow" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/54627422/4b0189c8-ef55-45df-837f-bcc4a8431c9e">

Closes https://github.com/Northeastern-Electric-Racing/FinishLine/issues/1954

2024-01-26 04:22 UTC, RChandler234 approved these changes
LGTM 🔥

2024-01-26 04:22 UTC, merged