#1499: replaced instances of 'any' in AppContext.test.tsx
Northeastern-Electric-Racing/FinishLine pull request #1988
Opened 2024-01-26 03:42 UTC by vsp05

## Changes

Changed props type from "any" to other values that made more sense in the file "AppContext.test.tsx".

Closes #1499

2024-01-26 21:01 UTC, jackturner106 reviewed
Good work! I think it should be possible to reduce the number of options there, I left a comment about that.

2024-01-26 21:01 UTC, jackturner106 commented on src/frontend/src/tests/app/AppContext.test.tsx
> +      children: string | number | boolean | {} | React.ReactNodeArray | React.ReactPortal | null | undefined;
Okay this is interesting! I like that you found a way to make it work, but I do think we should be able to tighten up the props a little bit. Could you try making the options limited to just React.ReactNode or possibly React.ReactNode | null and see if the tests still work?

2024-01-27 06:20 UTC, RChandler234 requested changes

2024-01-27 06:20 UTC, RChandler234 commented on src/frontend/src/tests/app/AppContext.test.tsx
> +    default: (props: { children: React.ReactNode | null }) => {
you should be able to remove the | null

2024-01-27 23:45 UTC, jackturner106 approved these changes
Looks good to me!

2024-01-28 17:55 UTC, RChandler234 approved these changes

2024-01-28 17:55 UTC, merged