#1990 added route, service, and controller method to delete unit
Northeastern-Electric-Racing/FinishLine pull request #1996
Opened 2024-01-27 20:28 UTC by superhvarn

## Changes

added route, service, and controller method to delete unit

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #1990)

2024-01-27 23:13 UTC, Aaryan1203 requested changes
Left a couple of comments

2024-01-27 23:13 UTC, Aaryan1203 commented on src/backend/src/services/projects.services.ts
> +    const deletedUnit = await prisma.unit.delete({
no need to save this to a constant, you can just call the function

2024-01-27 23:13 UTC, Aaryan1203 commented on src/backend/tests/projects.test.ts
> +      const deletedUnit = await ProjectsService.deleteUnit(superman, 'NERSoftwareTools');
same thing here

2024-01-27 23:13 UTC, Aaryan1203 commented on src/backend/tests/projects.test.ts
> +      expect(prisma.unit.delete).toBeCalledTimes(1);
to ensure that it is deleted, try to find the unit and ensure that it gives you a notfoundexception

2024-01-28 00:35 UTC, Aaryan1203 submitted a review, later dismissed
LGTM!

2024-01-28 17:57 UTC, RChandler234 requested changes

2024-01-28 17:57 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
> +    await prisma.unit.delete({
we do actually wanna save this value in a constant then return it

2024-01-31 18:08 UTC, RChandler234 requested changes
LGTM 🔥

2024-01-31 18:09 UTC, merged