#1928 fix color bom
Northeastern-Electric-Racing/FinishLine pull request #2014
Opened 2024-01-29 00:17 UTC by ArmaanMehra

## Changes

In the BOM Table, material status colors have been updated and made less harsh (Ordered - yellow, Unordered - orange, Shipped - blue, Received - green). The assembly row color is now the same dark grey we use for pageblock backgrounds.

## Notes

I believe the status colors are fine, but not sure if assembly line color is fine for light mode.

## Test Cases

No test cases needed (checked with tech lead Aaryan).

## Screenshots

<img width="1512" alt="Screenshot 2024-01-28 at 7 12 15 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124413244/8016b66a-a879-41d3-bf68-17647bed4f54">
<img width="585" alt="Screenshot 2024-01-28 at 7 12 49 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124413244/ce751cfc-eb9b-4d53-acb8-dda9e8cefed9">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # 1928

2024-01-29 03:50 UTC, Aaryan1203 approved these changes
This looks great! And I think the colors look nice as well. @RChandler234 what do you think?

2024-01-31 18:07 UTC, RChandler234 requested changes
Could you also make all the status chips the same size while you're in here

2024-01-31 18:07 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableCustomCells.tsx
> +      ? '#ba782a'
can you make unordered, more maroon

2024-02-09 04:18 UTC, RChandler234 requested changes

2024-02-09 04:18 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableCustomCells.tsx
> +  const boxStyle = {
can you rename this to bomStatusChipStyle and move it above this method

2024-02-09 04:18 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableCustomCells.tsx
>    const color =
can you also make a helper method that determines color from MaterialStatus

2024-02-16 20:56 UTC, ArmaanMehra commented
@RChandler234 @Aaryan1203 all changes requested have been resolved! Please take a look when y'all can

2024-02-19 03:54 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-19 03:54 UTC, merged