#1755: Added Reimbursement Disclaimer
Northeastern-Electric-Racing/FinishLine pull request #2031
Opened 2024-01-31 01:14 UTC by tanisharajgor

## Changes

Added question icon to the right of "Date of Expense" on the reimbursement request form. Tooltip appears on hover stating 'Reimbursement with Different Purchase Dates Should be on Different Requests'.

## Screenshots

<img width="1431" alt="FullScreen" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/54627422/c803c25e-8fe0-4cef-9a30-afd7f76da721">
<img width="494" alt="SmallestWindow" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/54627422/20963dcb-0358-428c-a4d8-4101390ee38d">

## Checklist

Please request reviewers and ping on slack only after you've gone through this whole checklist.
- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1755

2024-02-03 19:58 UTC, walker-sean approved these changes
LGTM

2024-02-03 20:30 UTC, RChandler234 requested changes

2024-02-03 20:30 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +// The reimbursement form code just redo this.
remove this line

2024-02-03 20:30 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
> +                  title="Reimbursement with Different Purchase Dates Should be on Different Requests"
Reimbursements*

2024-02-04 19:39 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-04 19:39 UTC, merged