#1989 hard deleted delete manufacturer endpoint
Northeastern-Electric-Racing/FinishLine pull request #2044
Opened 2024-02-01 04:58 UTC by AShyamkumar19

## Changes

Made the delete manufacturer a hard delete 

## Test Cases

- Fixed 1 test under Manufacturer Tests
- Made a mock of test of hard deleting 

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-02-01 22:54 UTC, Aaryan1203 requested changes
left some comments but good work!

2024-02-01 22:54 UTC, Aaryan1203 commented on src/backend/src/services/projects.services.ts
> +    //const dateDeleted: Date = new Date();
delete this

2024-02-01 22:54 UTC, Aaryan1203 commented on src/backend/src/services/projects.services.ts
>      if (manufacturer.dateDeleted) throw new DeletedException('Manufacturer', manufacturer.name);
no need to check for this anymore because the manufacturers are no longer being soft deleted

2024-02-02 17:45 UTC, Aaryan1203 reviewed
LGTM! Great work! 

@RChandler234 should we be testing all endpoints manually using postman so this type of problem doesn't occur again where an endpoint doesn't work as expected cuz sometimes the tests don't really help?

2024-02-03 20:54 UTC, RChandler234 commented
> LGTM! Great work!
> 
> @RChandler234 should we be testing all endpoints manually using postman so this type of problem doesn't occur again where an endpoint doesn't work as expected cuz sometimes the tests don't really help

yes 100%, this one was likely my bad cause some of the BOM stuff was done at the last minute, in general we should be thoroughly manually testing everything

2024-02-03 20:57 UTC, RChandler234 requested changes
while you're in here making the change, try manually testing the endpoint, this video will show you how: https://www.youtube.com/watch?v=CgFTb_hKdEo&feature=youtu.be

2024-02-03 20:57 UTC, RChandler234 commented on src/backend/src/services/projects.services.ts
>      });
can you wrap the deletedManufacturer being returned in the manufacturerTransformer

2024-02-03 21:03 UTC, RChandler234 requested changes
also throw an error if the manufacturer is associated with any materials, because otherwise prisma will throw an error when you try to delete it

2024-02-08 05:00 UTC, Aaryan1203 approved these changes
LGTM!

2024-02-09 05:52 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-09 05:52 UTC, merged