#1582: added the endpoint and started doing the tests
Northeastern-Electric-Racing/FinishLine pull request #2045
Opened 2024-02-01 05:40 UTC by martin0he

## Changes

I added an endpoint to change a reimbursement that only allows the creator to edit their reimbursement. It takes in an amount and date as a payload.

## Notes

Currently adding backend tests

## Test Cases

## Screenshots

## To Do

_Any remaining things that need to get done_

- [ ] add backend tests

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1582

2024-02-02 23:40 UTC, walker-sean requested changes

2024-02-02 23:40 UTC, walker-sean commented on src/backend/tests/reimbursement-requests.test.ts
> +    test('Successfully edits a reimbursement', async () => {
You need to add a mock for prisma.reimbursement.update to this test

2024-02-06 15:32 UTC, martin0he commented on src/backend/tests/reimbursement-requests.test.ts
> +    const reimbursementMock = {
all the other test data comes from reimbursement-requests.test-data.ts , should I still add it to just the seed or that file?

2024-02-06 17:46 UTC, RChandler234 commented on src/backend/tests/reimbursement-requests.test.ts
> +    const reimbursementMock = {
just put it in reimbursement-requests.test-data.ts

2024-02-06 21:26 UTC, walker-sean requested changes
ok last thing from me i think !!!

2024-02-06 21:26 UTC, walker-sean commented on src/backend/tests/test-data/reimbursement-requests.test-data.ts
> +export const updatedReimbursementMock = {
This is only used in one place, so you don't even need to declare this constant - you can just use the spread operator in the test - that way it is clear what youre doing

2024-02-07 21:45 UTC, walker-sean approved these changes
Nice!

2024-02-09 05:59 UTC, merged