#1728 Edit proposed solution
Northeastern-Electric-Racing/FinishLine pull request #2046
Opened 2024-02-01 05:46 UTC by jessicayzhao

## Changes

Added edit button to proposed solution that re-opens the proposed solution pop-up and allows you to edit the values in the proposed solution.

## Screenshots

<img width="564" alt="Screenshot 2024-02-01 at 12 44 50 AM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/132928939/14f43435-59bc-496d-9ba5-9da429ab70c1">

<img width="1411" alt="Screenshot 2024-02-01 at 12 45 26 AM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/132928939/4bedde78-2901-47fc-8a4b-20b846fb8270">

## To Do

- [ ] keep original information in solution pop up?
- [ ] stop proposed solution from disappearing while editing

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-02-05 04:41 UTC, RChandler234 requested changes
The problem with old values showing up when you create a new proposed solution is a separate issue with ProposedSolutionForm. Basically, you need to get the reset method from the useForm hook (same way we do it for handleSubmit or control), then create a wrapped method for onAdd, so that onAdd is called then reset is called, setting all the values in the form to undefined. This new wrapper method will replace the one place where onAdd is called in that file rn.

Let me know if you have questions, this should give some insight as well: https://react-hook-form.com/docs/useform/reset

2024-02-05 04:41 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionView.tsx
> +      {showEditModal ? (
you can remove this ternary operator. The open prop on ProposedSolutionForm hides the modal if it's false and shows it if it's true, so you can just include that component in the `<></>` you added and you should be good

2024-02-05 04:41 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionView.tsx
> +          onAdd={(data) => {
you'll need to pass in these four fields from the proposed solution in this file to the corresponding props on this component to get the current values on an edit to show up:
```
  description,
  budgetImpact,
  timelineImpact,
  scopeImpact,
```

2024-02-07 21:48 UTC, walker-sean approved these changes
Nice!

2024-02-09 06:03 UTC, RChandler234 requested changes
When you edit a proposed solution a second time, it still has the values from the first time you went to edit it

2024-02-09 06:03 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionForm.tsx
> +            handleSubmit(handleAdd)(e);
The submit button on this page should say 'Save' when you're editing instead of 'Add'

2024-03-29 04:50 UTC, closed without merging