#1999 added testing stage to work package forms
Northeastern-Electric-Racing/FinishLine pull request #2048
Opened 2024-02-02 02:08 UTC by superhvarn

## Changes

added testing stage to work package forms and made some backend changes to store it within the database.

## Screenshots
<img width="1551" alt="Screenshot 2024-02-01 at 9 08 27 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/56454934/f6bffbae-8982-4268-bac8-0cad6ae238cb">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-02-02 03:17 UTC, Aaryan1203 requested changes
left a small comment, but looks good

2024-02-02 03:17 UTC, Aaryan1203 commented on yarn.lock
> +  checksum: 2fc420cb6e6080a9808781ff81a2f0d37d63897c8c981d477001be18e55c8ec33422cf966e49efdca61d4a5335d16a4d6a09d5bd6da22a8396d0dcd350b9b9da
don't push the yarn lock file

2024-02-02 03:17 UTC, Aaryan1203 requested changes
Also add a picture that shows the testing stage in the create work package view

2024-02-04 21:04 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-04 21:04 UTC, merged