#2058 Added my name to credits
Northeastern-Electric-Racing/FinishLine pull request #2059
Opened 2024-02-03 22:10 UTC by XHoke04

## Changes

Added my name to credits page

## Screenshots
<img width="1336" alt="Screenshot 2024-02-03 at 5 02 59 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/156729120/0056f9ff-896a-4ad0-a2d7-17f0bb81846c">

Closes # (issue #2058 )

2024-02-04 01:09 UTC, Aaryan1203 requested changes
Great work!

Just remember to assign yourself the ticket and also take a screenshot of the page in the smallest screen view

2024-02-05 03:58 UTC, Aaryan1203 submitted a review, later dismissed
LGTM!

2024-02-05 04:04 UTC, Aaryan1203 approved these changes

2024-02-05 04:17 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-05 04:17 UTC, merged