#2001 made migration, made some backend changes, made some frontend c…
Northeastern-Electric-Racing/FinishLine pull request #2067
Opened 2024-02-05 04:29 UTC by superhvarn

## Changes

made migration, made some backend changes, made some frontend c…

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #2001 )

2024-02-06 00:01 UTC, Aaryan1203 requested changes
Your typescript tests are still failing. i will take a look later today at how we can fix that

2024-02-06 00:01 UTC, Aaryan1203 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
> +            <FormLabel>Notes (Optional)</FormLabel>
make it a lowercase 'o' just so its consistent with the others

2024-02-06 01:41 UTC, Aaryan1203 requested changes
When i tested it right now, i am still getting an error when submitting without putting something for notes saying that the notes are a required field. I would say check the frontend checks to make sure its not still expecting one

2024-02-07 00:15 UTC, Aaryan1203 commented on src/frontend/src/utils/bom.utils.ts
> +    notes: material.notes ?? 'None'
don't think you need this

2024-02-07 03:59 UTC, Aaryan1203 approved these changes
Tested, looks good to me!

2024-02-07 04:16 UTC, Aaryan1203 approved these changes

2024-02-10 23:27 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-10 23:27 UTC, merged