#1950 made dropdowns for assemblies
Northeastern-Electric-Racing/FinishLine pull request #2097
Opened 2024-02-10 18:29 UTC by jackturner106

## Changes

Assembly materials are now hidden until their associated assembly is clicked, at which point they drop down. Created a Misc section for materials with no associated assembly. DataGrid updated to hold up to 100 values on 1 page.

## Test Cases

Tested with up to 100 assemblies to ensure they stayed on 1 page, and with over 100 to ensure that switching between pages is still possible with the dropdowns.

## Screenshots

![1950_1_1](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/921fdd84-df18-4b86-942a-e118190ef187)
![1950_1_2](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/500b382c-c174-4a90-9225-9685bd8e037e)
![1950_1_3](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/b510bfb5-a27e-4530-813a-1b8a3385bd24)

Attaching a smallest possible window screenshot but like, please don't use the assemblies datagrid in a small window.
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/49f106c7-c1d1-45b2-be03-aaa771b08f4d)
## To Do

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1950

2024-02-10 23:39 UTC, RChandler234 requested changes
It closes the assembly whenever u click on any item inside of it which we don't want. Could you also add some kind of arrow indicator to show if an assembly is collapsed or not

2024-02-14 04:06 UTC, walker-sean requested changes

2024-02-15 00:10 UTC, RChandler234 requested changes
can you try to get rid of the color change on hover for the assembly and material rows while you're in here

2024-02-15 00:10 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx
>        <DataGrid
can you change line 81 to be - 180px instead of 260px, I think we're scrunching up the table too much

2024-02-16 03:06 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-16 03:06 UTC, merged