#1794: Allow Guests to browse without SlackId
Northeastern-Electric-Racing/FinishLine pull request #2098
Opened 2024-02-10 18:46 UTC by Dao-Ho

## Changes

Passed in userRole into AppAuthenticated along with existing userId, allowing us to check whether the user is a guest. If the user is a guest, allow them to continue to the site without the SlackId requirement. Otherwise, prompt the requirement if they are a member, lead, admin, etc.

## Notes

Also added userRole as a parameter for AppAuthenticated.test.tsx when testing the component.

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1794

2024-02-12 02:31 UTC, callmejim1226 requested changes
Great work! The current code looks good to me :)

Although, I think it would be better to make a further update. Curretnly, when we log in as a GUEST in Finishline, we still see a yellow warning pop-up in the top as the screenshot shows. 

Can we remove this pop-up when the user is logged into Finishline as a guest?

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/91857946/cdf3a133-eb0f-46f5-b24a-39f920cba4a6)

2024-02-14 03:33 UTC, callmejim1226 commented on yarn.lock
We don't want to have any changes in yarn.lock file unless the project's dependencies have changed (which is not the case in this commit). 

Can we undo the changes in this yarn.lock file?

2024-02-14 03:41 UTC, callmejim1226 requested changes
Great work! Almost there! Just a single comment on yarn.lock file since we don't any changes in yarn.lock to be pushed into develop branch

2024-02-14 21:07 UTC, callmejim1226 approved these changes
Looks good to me! Great work!

2024-02-14 21:29 UTC, RChandler234 requested changes

2024-02-14 23:59 UTC, RChandler234 approved these changes
LGTM 🔥

2024-02-14 23:59 UTC, merged