#2009 added get user schedule settings endpoint
Northeastern-Electric-Racing/FinishLine pull request #2107
Opened 2024-02-11 03:11 UTC by martin0he

## Changes

added route to users that returns the specified user's schedule settings

## Notes

seed data for this doesn't exist yet and the create endpoint hasn't been made yet so testing rn is kind of a pain

## Test Cases

user doesn't exist
user has no schedule settings

## Screenshots

## To Do

- [ ] add condition to return error if user doesn't exist
- [ ] add seed data for users with settings for testing
- [ ] do postman tests

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2009

2024-02-14 04:04 UTC, walker-sean requested changes
Nice !

2024-02-14 04:04 UTC, walker-sean commented on src/backend/tests/users.test.ts
> +    test('getUserScheduleSettings runs', async () => {
Nitpick: "works" is clearer over "runs"

2024-02-14 20:23 UTC, martin0he commented on src/shared/src/types/user-types.ts
> +  userId: number;
i was copying the same format as secure settings and it includes userId, also I use the userId to find the settings in services

2024-02-15 00:24 UTC, RChandler234 requested changes

2024-02-15 00:24 UTC, RChandler234 commented on src/backend/src/controllers/users.controllers.ts
> +      const userScheduleSettings = await UsersService.getUserScheduleSetting(userId);
we should pass in the submitter and validate that it's the same as the id of the user who's schedule settings we're requesting. We should probably have a separate endpoint for retrieving availability given a set of userIds

2024-02-15 00:24 UTC, RChandler234 commented on src/backend/src/transformers/user-schedule-settings.transformer.ts
> +    userId: settings.userId
don't include userId here

2024-02-15 00:24 UTC, RChandler234 commented on src/shared/src/types/user-types.ts
> +  userId: number;
or here

2024-02-17 17:47 UTC, RChandler234 requested changes
The test is failing because the service method returns a shared type but you're comparing it to a prisma type

2024-02-18 00:57 UTC, martin0he commented
> The test is failing because the service method returns a shared type but you're comparing it to a prisma type

So should I change the service method to a prisma type or the other one to the shared type (shared is the one without userId and user)?

2024-02-18 01:00 UTC, RChandler234 commented
> > The test is failing because the service method returns a shared type but you're comparing it to a prisma type
> 
> 
> 
> So should I change the service method to a prisma type or the other one to the shared type (shared is the one without userId and user)?

Change the test to compare the return from the service method to a shared type user schedule settings

2024-02-21 02:48 UTC, walker-sean requested changes
Looking good!

2024-02-21 02:48 UTC, walker-sean commented on src/backend/src/routes/users.routes.ts
remove this newline

2024-02-21 02:48 UTC, walker-sean commented on src/backend/src/services/users.services.ts
> +  static async getUserScheduleSetting(userId: number, submitter: PrismaUser): Promise<UserScheduleSettings> {
getUserScheduleSettings (plural)

2024-02-25 17:39 UTC, RChandler234 requested changes

2024-02-25 17:39 UTC, RChandler234 commented on src/backend/src/services/users.services.ts
> +   * @returns the user's schedule settings
you should have the submitter param in the comment as well

2024-02-25 19:17 UTC, walker-sean approved these changes

2024-02-25 19:18 UTC, merged