added error in start date field
Northeastern-Electric-Racing/FinishLine pull request #2115
Opened 2024-02-13 21:29 UTC by pidang1

## Changes

showed the error "invalid startDate" when an invalid date is clicked

## Screenshots

![Screenshot (1)](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147662005/072cff4c-2382-4b30-9bb7-2628c333522f)
![Screenshot (2)](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147662005/1b43e4ac-11a6-47b1-bd5d-d2d795e382d3)

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1300

2024-02-17 18:14 UTC, jackturner106 requested changes

2024-02-17 18:14 UTC, jackturner106 commented on src/frontend/src/pages/WorkPackageForm/WorkPackageFormDetails.tsx
> -                    shouldDisableDate={disableStartDate}
This should not have been removed, you'll need to put it back

2024-02-25 20:58 UTC, RChandler234 requested changes
Can you also change the message that's displayed when a start date is invalid. It should say `Start Date Must be a Monday`

2024-03-24 19:12 UTC, RChandler234 approved these changes
LGTM 🔥

2024-03-24 19:12 UTC, merged