#163: (WIP) Add Proposed Solution Seed Data
Northeastern-Electric-Racing/FinishLine pull request #216
Opened 2022-09-21 03:53 UTC by Danwo0

## Changes

_Explanation of changes goes here_

There are no seed data for proposed solutions. Let's change that.

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots (if applicable)

_Any relevant screenshots go here_

## To Do

_Any remaining things that need to get done_

- [ ] add actual "meaningful" data

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/FinishLine/blob/develop/docs/ContributorGuide.md) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors
- [ ] No newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (if applicable)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] PR is linked to the ticket
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack

Closes # (issue #)

2022-09-26 06:06 UTC, jamescd18 requested changes
Data generally looks good, but there's some tweaks in the insertion script I think are probably needed, and some notes for future:

1. no, you don't need to worry about the IDs for proposed solutions. Prisma handles generating those and so far I'm not aware of seed data needing to do anything with those IDs
2. knowing SQL is great and powerful, but you definitely wanna be sure to not overly rely on it. SQL implementation of the database can sometimes take you away from what's accessible / available / important at the application logic layer if you're not actively thinking about it. also [prisma studio](https://www.prisma.io/studio) comes with usage of prisma
3. seed data is intended to be used and thought of in a sorta closed system of all the seed data. when you seed or re-seed the db, you're intentionally wiping the db clean and loading it with your specified data. that way, typically, you can do some things that you wouldn't do otherwise

2022-09-26 13:46 UTC, anthonybernardi commented on src/backend/src/prisma/seed.ts
> +        createdByUserId: seedProposedSolution.createdByUserId,
only if you're connecting by objects. if you connect by ids you can just hook up the ids like this

2022-09-26 13:51 UTC, anthonybernardi commented
on the right track! but instead of doing all this connecting with the crData, you should just make the proposed solution seed objects have the full data (scope, budget, timeline) on their own. then you just have to make the proposed solution (`await prisma.proposed_solutions.createMany`) with that data. Also all the data should be meaningful (so try to think of stuff instead of just writing "example 1")

2022-09-30 02:52 UTC, anthonybernardi approved these changes
nice! LGTM

2022-09-30 21:00 UTC, merged