#2119-BOM-price-label-change
Northeastern-Electric-Racing/FinishLine pull request #2167
Opened 2024-02-22 03:39 UTC by Sarah-Zhang1

## Changes
All instances with the label 'Price' are renamed to 'Price per Unit' in the frontend 

## Test Cases
- ran yarn test:frontend

## Screenshots
1) normal sized window 
<img width="1512" alt="Screenshot 2024-02-21 at 10 37 05 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147781368/e2f352ed-f220-4ddc-aa05-d58b43364517">

2) smallest window 
<img width="503" alt="Screenshot 2024-02-21 at 10 36 47 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147781368/966e85ed-c52a-4526-83f7-5235aa0d11e2">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2119

2024-02-22 03:58 UTC, jessicayzhao approved these changes
LGTM :)

2024-02-23 02:56 UTC, RChandler234 requested changes
Could you see if you can get this to wrap around instead of doing '...'
<img width="183" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/29521172/e702489f-275a-4417-b38e-fb4e52f46100">

2024-03-21 00:58 UTC, RChandler234 requested changes

2024-03-21 00:58 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
> +              <FormLabel>Price per Unit</FormLabel>
you can put this style object on the form label on the FormLabel

2024-03-24 20:04 UTC, RChandler234 approved these changes
LGTM 🔥

2024-03-24 20:04 UTC, merged