#1764: added auto complete for change request ID in edit work package
Northeastern-Electric-Racing/FinishLine pull request #2182
Opened 2024-02-29 02:42 UTC by ItsEricSun

## Changes

Make the change request ID form field autocomplete in edit work package like project lead.

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/78322291/be3d5337-b043-40e9-9743-e5c7f247d9be)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/78322291/287b348f-b7db-40cd-a521-a1cb459b869d)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/78322291/abe988f4-7df1-4fa3-b0d1-de1fcb0be512)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1764

2024-02-29 07:09 UTC, RChandler234 requested changes

2024-02-29 07:09 UTC, RChandler234 commented on src/frontend/src/components/ChangeRequestDropdown.tsx
> +  );
You should be able to simplify this to just use approvedChangeRequestOptions now that we're using an NERAutocomplete, you can search for the approvedChangeRequestOption that has the same id as the tracked value

2024-03-20 23:17 UTC, callmejim1226 approved these changes
Looks good to me!

2024-03-25 05:12 UTC, RChandler234 approved these changes
LGTM 🔥

2024-03-25 05:12 UTC, merged