1998 caio da silva user schedule endpoint
Northeastern-Electric-Racing/FinishLine pull request #2186
Opened 2024-03-01 19:51 UTC by caiodasilva2005

## Changes

Added endpoint for setting user schedule

## Test Cases

Made test to ensure request is returning an id.

<img width="671" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/145620095/68dd9f60-2694-4093-8074-278afcbf5862">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [X] All commits are tagged with the ticket number
- [X] No linting errors / newline at end of file warnings
- [X] All code follows repository-configured prettier formatting
- [X] No merge conflicts
- [X] All checks passing
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #1998

2024-03-10 16:17 UTC, jackturner106 requested changes
This is looking good! There's a couple more things I would like to verify on the endpoint. Also, it looks like .[0]x was pushed? Its the file that git uses to track commits, and normally it should not show up, so I'm not actually sure whats happened there. See if you can get it to not show up in the commit, you may need to more or less manually revert it.

2024-03-10 16:17 UTC, jackturner106 commented on src/backend/src/services/users.services.ts
> +  static async setUserScheduleSettings(
Can you check that emails are unique? See how its done for phone numbers in setUserSecureSettings.

2024-03-10 16:17 UTC, jackturner106 commented on src/backend/tests/users.test.ts
> +    test('setUserScheduleSettings works successfully', async () => {
Could you add tests for invalid emails/invalid zoom links, and maybe also for non-unique emails?

2024-03-13 20:30 UTC, RChandler234 requested changes

2024-03-13 20:30 UTC, RChandler234 commented on src/backend/src/controllers/users.controllers.ts
> +      res.status(200).json({ message: `Successfully updated schedule settings for user ${user.userId}.` });
should be returning the updated schedule settings

2024-03-13 20:30 UTC, RChandler234 commented on src/backend/src/services/users.services.ts
> +  static async setUserScheduleSettings(
this should have a detailed comment documented inputs/ outputs

2024-03-14 16:40 UTC, RChandler234 requested changes
remove that extra file pls

2024-03-14 16:40 UTC, RChandler234 commented on src/backend/src/controllers/users.controllers.ts
> +      const editedScheduleSettings = await UsersService.setUserScheduleSettings(
*updatedScheduleSettings

2024-03-14 16:40 UTC, RChandler234 commented on src/backend/src/services/users.services.ts
> +    const newUserScheduleSettings = await prisma.schedule_Settings.upsert({
updateScheduleSettings*

2024-03-14 16:40 UTC, RChandler234 commented on src/backend/src/services/users.services.ts
> +    return newUserScheduleSettings.drScheduleSettingsId;
this should return the whole updateScheduleSettings, not just the id

2024-03-17 16:22 UTC, RChandler234 approved these changes
LGTM 🔥

2024-03-17 16:22 UTC, merged