#1600: Added Working Preview to Create Team Description
Northeastern-Electric-Racing/FinishLine pull request #2194
Opened 2024-03-08 02:11 UTC by aahiltn

## Changes

Added Preview Buttons to the Create Team description section in the Admin Tools page. Uses ReactMarkdown to preview text.  

## Test Cases

- Submitting Form without Description (Correctly gives a warning)
- Saving over the 300 word limit (Correctly gives a warning)
- Preview Unsaved Text 

## Screenshots

Description Required: 
<img width="436" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/65504406/1021d995-3659-40e9-acda-b4368d380eed">

Editing Description:
<img width="437" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/65504406/2b2eddeb-0b2c-4c74-a974-8fab07280c83">

Preview Description:
<img width="421" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/65504406/0e51dd32-3b1c-4103-8ab5-de5a5c393b82">

Saved Description:
<img width="414" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/65504406/950225a8-1263-4734-9e24-1e7b76f70fa0">

## Checklist

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1600

2024-03-09 20:27 UTC, jackturner106 requested changes
Overall, great work getting this working! I do think the logic can be simplified some as far as removing the isEditingDescription variable and possibly the save button, let me know what you think

2024-03-09 20:27 UTC, jackturner106 commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +                  isEditingDescription ? (
Currently if isEditingDescription is false and the user tried to submit the error text is hidden. I don't think you need isEditingDescription at all, it should work if you just make it true all the time

2024-03-09 20:27 UTC, jackturner106 commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +      <Button
Seems like the save button is uneccessary? The description saves even if you never click it, at least when I test it

2024-03-09 20:27 UTC, jackturner106 commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +    ?.filter((user) => isHead(user.role))
Was there a reason to remove the loading icons, and make this optional?

2024-03-17 17:12 UTC, jackturner106 requested changes
Good work! I like this better. I think you could get it a little bit simpler by removing the cancel button as well, and two other changes

2024-03-17 17:12 UTC, jackturner106 commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +        Cancel
Currently clicking the cancel button makes the textbox disappear, which doesn't really make sense as something the user would want to do. Can you remove the cancel button altogether?

2024-03-17 17:12 UTC, jackturner106 commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +  const DescriptionButtons: React.FC<DescriptionButtonsProps> = ({ toRight }) => {
Calling this DescriptionButtons isn't quite right since it's really there to hold the header, go ahead and rename it

2024-04-03 18:07 UTC, jackturner106 submitted a review, later dismissed
Looks good to me!

2024-04-03 20:41 UTC, walker-sean requested changes
This is looking really good!

Not a huge deal, but could you add some spacing between the rows of the team form an d have the label and button both sit right on top of the text field? That way, it's more obvious what they belong to

2024-04-03 20:41 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +  const [isPreview, setIsPreview] = useState(false);
change to `showPreview`

2024-04-03 20:41 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +  const [currentDescription, setCurrentDescription] = useState('');
We actually don't need this useState - most of the rest of the comments will relate to using the form without it

2024-04-03 20:41 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +                        onChange={(e) => {
Remove the onChange

2024-04-03 20:41 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +                      <TextField
add {...field} as the first prop

2024-04-03 20:41 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +                        value={currentDescription}
remove the value

2024-04-03 20:41 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +                        error={!!errors.description || !isUnderWordCount(currentDescription, 300)}
change all instances of currentDescription to field.value and remove all instances of setCurrentDescription

2024-04-05 01:06 UTC, walker-sean requested changes
Nice work! Currently the text field is resetting, but that should be fixed by moving the spread operation

2024-04-05 01:06 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +                      <TextField
The `{...field}`should be in the `<TextField />`

2024-04-12 02:09 UTC, RChandler234 requested changes

2024-04-12 02:09 UTC, RChandler234 commented on src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
> +                  <Box sx={{ display: 'flex-col' }}>
'display: flex-col' isn't actually doing anything, I believe this is from tailwind? We don't use that, so it's not actually applying any css

2024-04-14 01:46 UTC, RChandler234 requested changes
this should have the same margin on the bottom as it does on the top

2024-04-21 17:41 UTC, jackturner106 commented
> this should have the same margin on the bottom as it does on the top

Like this?
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/432f675d-8bcb-4f23-8bf0-db42eb37e933)

Or like this?
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/41128621/eec213a8-2eb4-4000-b4e6-d4ffd7981740)

2024-04-21 20:07 UTC, walker-sean approved these changes
Love it !

2024-04-21 20:07 UTC, merged