#2121 moving create unit functionality to admin tools
Northeastern-Electric-Racing/FinishLine pull request #2198
Opened 2024-03-11 19:03 UTC by Zwendle

## Changes

Added the ability to create a new unit to the admin tools page under the Build of Materials Config section. Also removed the create unit functionality from the dropdown of the units select on the material form.

## Screenshots

<img width="1728" alt="Screenshot 2024-03-13 at 16 38 27" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/cd40146e-06b7-41c5-9e88-a1d1d54f55b1">
<img width="500" alt="Screenshot 2024-03-13 at 16 38 55" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/e352a8d8-1ba1-40c1-ba8b-e2fc9ba7feff">
<img width="1728" alt="Screenshot 2024-03-13 at 16 39 21" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/ffcceacc-c892-414f-a835-1babe77f9ba5">
<img width="501" alt="Screenshot 2024-03-13 at 16 39 55" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/1b480664-9297-4f15-95ed-3af5cd847e4d">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2121

2024-03-12 14:49 UTC, martin0he commented on src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
> +        <Grid item direction="column" xs={11} md={6}>
make this xs=12

2024-03-12 14:55 UTC, martin0he requested changes
great work so far this is a really good start. what you have to do now is 1) remove the dropdown option to create a new unit in the bom page (where this feature used to be, get rid of it there so that it only shows the available existing units only), 2) modify the table to just show one column with units, no need for dates, you're prob gonna have to create your own table component that's similar to the existing one just with one column and not column[] and that's more or less it for now. really great job so far !

2024-03-13 20:13 UTC, martin0he approved these changes
Looks good to me, good work ill get another review

2024-03-13 20:14 UTC, martin0he requested changes
update your PR, get rid of unnecessary notes and also update your screenshots

2024-03-14 22:36 UTC, RChandler234 approved these changes
LGTM 🔥

2024-03-14 22:36 UTC, merged