#1274 finance fixes
Northeastern-Electric-Racing/FinishLine pull request #2202
Opened 2024-03-14 00:58 UTC by ryanhowe28

## Changes

draft
## Notes

dont look at me

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1586

2024-03-27 21:26 UTC, RChandler234 requested changes

2024-03-27 21:56 UTC, RChandler234 requested changes
You'll need to update the backend tests because you updated the service method

2024-03-27 21:56 UTC, RChandler234 commented on src/backend/src/services/reimbursement-requests.services.ts
> +  static async markReimbursementRequestAsDelivered(submitter: User, reimbursementRequestId: string, dateMarkedDelivered: string) {
just name this dateDelivered

2024-03-27 21:56 UTC, RChandler234 commented on src/frontend/src/hooks/finance.hooks.ts
> +// export const useEditReimbursementRequest = (reimbursementRequestId: string) => {
don't comment this out

2024-03-27 21:56 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
> +    // <NERModal
delete

2024-03-27 21:56 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
> +    // const handleMarkDelivered = () => {
delete

2024-03-27 21:56 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
> +  const handleMarkDelivered = async (data: { dateDelivered: Date }) => {
this should be dateReceived, not dateDelivered that's why it's not submitting

2024-03-27 21:56 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
> +      reset={reset}
this should be this `() => reset({ dateReceived: undefined })`

2024-03-27 21:56 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
> +  const {
I would move all this form code and the modal into it's own file like we do for: `src\frontend\src\pages\FinancePage\FinanceComponents\ReportRefundModal.tsx`

2024-04-18 15:33 UTC, closed without merging

2024-04-18 15:33 UTC, ryanhowe28 commented
Not close to being done