#2145-settings-page-tabs
Northeastern-Electric-Racing/FinishLine pull request #2206
Opened 2024-03-14 03:30 UTC by alexpark0

## Changes

Changed settings page into a tab-based view

## Screenshots
<img width="1440" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147440322/f79d85a7-a8db-434b-a230-109e4858b566">

<img width="1440" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147440322/1f0ad604-d084-41ff-98fa-2756b3201ceb">

<img width="597" alt="Screenshot 2024-03-13 at 11 29 08 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147440322/fc898ac0-f3ba-4fd2-96c6-5162a06d7739">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2145

2024-03-14 15:11 UTC, ryanhowe28 requested changes
Looking good, small things

2024-03-14 15:14 UTC, ryanhowe28 commented on src/frontend/src/pages/SettingsPage/Preferences.tsx
> +      <PageBlock title={'Organization Settings'}>
Lets move organization settings to the details tab

2024-03-18 19:19 UTC, ryanhowe28 commented on src/frontend/src/pages/SettingsPage/SettingsPreferences.tsx
> +      {showAlert && <Alert severity="info">Haha {auth.user?.firstName} bye bye!</Alert>}
Looks like you flipped the names/content of the preferences and details files. In the middle of that you took this line and put it on the preference page when it should be on the details page and should show when someone hits trickster mode. Look at how it was before

2024-03-18 19:20 UTC, ryanhowe28 requested changes
One thing that got put out of place.

2024-03-18 19:36 UTC, ryanhowe28 submitted a review, later dismissed
LGTM

2024-03-18 20:03 UTC, walker-sean requested changes
Looking good!

We also need to add the schedule settings (in develop), and there are some merge conflicts

2024-03-18 20:03 UTC, walker-sean commented on src/frontend/src/pages/SettingsPage/SettingsDetails.tsx
> +      <PageBlock title={'Organization Settings'}>
I know this has gone back and forth, but lets put everything that can be changed into the preferences tab. The details tab should just be that readonly list

2024-03-19 15:25 UTC, merged