#2223: Design Review mark user confirmation endpoint
Northeastern-Electric-Racing/FinishLine pull request #2225
Opened 2024-03-18 20:30 UTC by martin0he

## Changes
added a new endpoint

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2223

2024-03-18 20:31 UTC, martin0he commented
this is my postman setup
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90310958/c01c4b25-9cde-4b71-a03d-86978a97a9f2)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90310958/66bc9c15-0385-4334-83de-d6566183da48)

2024-03-18 23:39 UTC, RChandler234 requested changes

2024-03-18 23:39 UTC, RChandler234 commented on src/backend/src/controllers/design-reviews.controllers.ts
> +      const { availability } = req.body;
you named it meetingTimes in the route, that's why you're getting null (should be availability)

2024-03-19 04:19 UTC, RChandler234 approved these changes
LGTM 🔥

2024-03-19 04:19 UTC, merged