#2158 work package templates admin tool templates table
Northeastern-Electric-Racing/FinishLine pull request #2252
Opened 2024-03-22 20:00 UTC by Jake-Hensley

## Changes

Made a table in Admin Tools under the Project Config tab that shows Work Package Templates.

## Notes

Currently there is just a test array in the file to demonstrate that the table works. Yarn.lock was modified but I'm not sure if it was supposed to be.

## Screenshots

<img width="1280" alt="image" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/150979806/5dacbb01-cda1-4612-9d82-f1e60955c37b">

## To Do

- [ ] Hook to get the Work Package Templates
- [ ] Create the functionality of the new work package template button

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2158

2024-03-25 15:57 UTC, bderbs30 commented
to fix the yarn lock stuff you can checkout the yarn.lock file from develop and that should fix it

This is the command I ran in terminal: git checkout develop -- yarn.lock

2024-03-26 00:22 UTC, bderbs30 commented on src/frontend/src/pages/AdminToolsPage/ProjectsConfig/WorkPackageTemplateTable.tsx
> +const WorkPackageTemplateTable = () => {
Once the hook is completed we'll be able to call it similar to the linktype table. Though, for the hook we need an endpoint which is currently being done

2024-05-10 01:01 UTC, Peyton-McKee requested changes

2024-05-10 01:44 UTC, Peyton-McKee submitted a review, later dismissed
yippee

2024-05-10 01:50 UTC, merged