#2120 make unit dynamic
Northeastern-Electric-Racing/FinishLine pull request #2272
Opened 2024-03-27 05:32 UTC by ArmaanMehra

## Changes

So far what I've done is I've written out the logic for making the units more dynamic. However, I'm working with mock units since there don't seem to be any units when I work with however it tries to access the actual data.
So far:
- Able to parse Units and convert all units with "Pack of..." to a single "Pack" option.
- If Pack option is selected, then a Pack Size option pops up, and all options of pack size from original units datais provided.

## Notes

IMPORTANT NOTE: This issue is not complete yet, I've opened this PR for feedback on what I've done so far and advice on how to move forward.

Rn the issue I'm running into is that I'm not 100% sure if what I'm doing works, since I don't have access to backend Units data when I'm running this on localhost.

## Test Cases

Unsure on how to test this, or if it needs testing since this is all in fronted.

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124413244/5942bd91-2ba4-4a34-a163-30370a66bf2a)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124413244/dd4c36d3-e1d5-4ab3-9148-4a18caf116f4)
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124413244/e4742b8b-30bb-499e-b62e-3b4e575d6cdd)

## To Do

- [ ] Still need to convert the dynamic unit data back to a string to send back to backend.

## Checklist

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-03-28 02:18 UTC, Aaryan1203 requested changes
I am a little confused with that exactly the ticket is supposed to be doing right now but I did leave a couple comments for now

2024-03-28 02:18 UTC, Aaryan1203 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
> +  const unitName = watch('unitName');
I dont think this is requierd

2024-03-28 02:18 UTC, Aaryan1203 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
> +    .map((unit) => unit.name.replace('Pack of ', ''));
I think there will be a better way to do this, but i think we can change it once we understand what exactly were doing

2024-04-14 02:41 UTC, RChandler234 requested changes
code's looking good! Only thing left is to add support for packs in the admin tool for adding units

2024-05-22 00:36 UTC, closed without merging