#1725: Lets finance leads delete reimbursement requests
Northeastern-Electric-Racing/FinishLine pull request #2283
Opened 2024-03-28 04:38 UTC by Zwendle

## Changes

Changed a conditional to check if the reimbursement request submitter is a finance lead/head, also created a new file for reimbursement request testing under the "unmocked" directory and created some tests for the functionality.

## Notes

Had a significant amount of assistance from Peyton with the testing code, so any comments regarding those files should be addressed to him

## Test Cases

- Submitter is not a finance head/lead so the delete reimbursement function throws an error
- Submitter is a finance head/lead so the function works

## Screenshots

<img width="1219" alt="Screenshot 2024-03-28 at 00 36 51" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/edb92afc-0ba9-4602-83ed-daa6fdf57474">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1725

2024-03-30 15:37 UTC, martin0he commented on src/backend/src/services/reimbursement-requests.services.ts
> +        'You do not have access to delete this reimbursement request, only the creator or finance leads can delete a reimbursement request'
this is actually only checking if the user is finance, not if they're a creator too. add back the if statement you deleted that was there before. also make the message for this say 'only finance leads...'

2024-03-30 15:39 UTC, martin0he commented on src/backend/tests/mocked/reimbursement-requests.test.ts
> +          'You do not have access to delete this reimbursement request, only the creator or finance leads can delete a reimbursement request'
you're gonna have to update this comment too to what you change it to say in my above comment so that it matches and passes

2024-03-30 15:41 UTC, martin0he commented on src/backend/tests/mocked/reimbursement-requests.test.ts
>          ReimbursementRequestService.deleteReimbursementRequest(GiveMeMyMoney.reimbursementRequestId, superman)
also separate the tests: case 1: when the user is not creator. case 2: when the user is not finance lead+. case 3: when user is finance but not leadership

2024-03-30 15:44 UTC, martin0he commented on src/backend/tests/test-utils.ts
> +export const createFinanceTeamAndLead = async () => {
add a regular finance member to this team so you can test for that case too

2024-03-30 15:45 UTC, martin0he commented on src/backend/tests/unmocked/reimbursement-requests.test.ts
> +        'You do not have access to delete this reimbursement request, only the creator or finance leads can delete a reimbursement request'
update the throw to say whatever you changed it to above ('...only finance leads ...'), and add the test cases I mentioned earlier

2024-03-30 15:47 UTC, martin0he requested changes
Great work so far, really solid start, keep it up

2024-03-30 15:48 UTC, martin0he commented
> Great work so far, really solid start, keep it up

also make sure to fix your prettier formatting too 👍

2024-04-05 17:53 UTC, martin0he commented on src/backend/tests/mocked/reimbursement-requests.test.ts
> +import { createTestUser } from '../test-utils';
take a look at this^

2024-05-09 22:11 UTC, Peyton-McKee requested changes

2024-05-09 22:11 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +    if (request.recipientId !== submitter.userId! || !(await isUserLeadOrHeadOfFinanceTeam(submitter)))
this should be and

2024-05-09 22:11 UTC, Peyton-McKee commented on src/backend/src/services/reimbursement-requests.services.ts
> +    if (request.recipientId !== submitter.userId! || !(await isUserLeadOrHeadOfFinanceTeam(submitter)))
get rid of force unwrap

2024-05-10 22:40 UTC, Peyton-McKee requested changes

2024-05-10 22:40 UTC, Peyton-McKee commented on src/backend/tests/unmocked/reimbursement-requests.test.ts
> +    const financeHead = await prisma.user.findUnique({
your not using this.

2024-05-10 22:40 UTC, Peyton-McKee commented on src/backend/tests/unmocked/reimbursement-requests.test.ts
> +  test('Delete Reimbursement Request fails when deleter is not the creator', async () => {
this test and the test above are identical

2024-05-10 22:40 UTC, Peyton-McKee commented on src/backend/tests/unmocked/reimbursement-requests.test.ts
> +  test('Delete Reimbursement Request fails when deleter is not the creator', async () => {
convert this test to be suceeding when the user is a finance lead

2024-05-11 02:16 UTC, Peyton-McKee approved these changes
i think this should work now

2024-05-11 02:16 UTC, merged