#2084 delete unit column
Northeastern-Electric-Racing/FinishLine pull request #2286
Opened 2024-03-29 20:23 UTC by anyadas11

## Changes

Added a column of trash can icons in the unit table in admin tools that allow for deleting a unit. 

## Notes

- there is an error occurring and I'm not sure where it's coming from

## Screenshots
<img width="1702" alt="Screenshot 2024-03-29 at 4 21 08 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147773632/0b64cbbc-5253-4dc1-aeb2-112790a5ec6a">
<img width="379" alt="Screenshot 2024-03-29 at 4 21 26 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/147773632/e9cadd43-5659-4251-a415-27e91c500866">

## To Do

- [ ] fix delete functionality  - figure out the error with handleDeleteUnit

## Checklist

- [X] All commits are tagged with the ticket number
- [X] All code follows repository-configured prettier formatting
- [X] No merge conflicts
- [X] Screenshots of UI changes (see Screenshots section)
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #2084

2024-04-14 15:51 UTC, bderbs30 commented on src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
> +    <Box paddingBottom="4">
The padding at the bottom isn't working 
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/66f84b9e-d126-4270-b458-d3eec26a3680)
Look at the syntax it should be 

paddingBottom={4}

2024-04-14 15:53 UTC, bderbs30 commented
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/18f9029f-9580-4cf3-b185-402683544ee4)
In the top right of the table the edges aren't bordered by a black line like the others

2024-04-14 16:15 UTC, bderbs30 commented
> ![image](https://private-user-images.githubusercontent.com/124754518/322285831-18f9029f-9580-4cf3-b185-402683544ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTE1MTUsIm5iZiI6MTcxMzExMTIxNSwicGF0aCI6Ii8xMjQ3NTQ1MTgvMzIyMjg1ODMxLTE4ZjkwMjlmLTk1ODAtNGNmMy1iMTg1LTQwMjY4MzU0NGVlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxNjEzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTRhY2Q2NDgzMzMwYzEwNWViMDA0NmYyYjRlOGQ3OTVmOGIzODE0OTIxYjIxZDg5NDhhMjc2N2M4ZDI1ODc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fcATtRKhwDW-tYP2GkD3E0mG7QoK8rkmKHF-aDY8FMg) In the top right of the table the edges aren't bordered by a black line like the others


You'll want to look at this code specifically in the columns prop of the admin tool table
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/1e0470d0-4754-43ae-9d02-aa1dcdd37271)

The change you'll need to make is present in this code example

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/124754518/811d0fb2-cb01-42fa-a84c-63daf5374368)


if you have any questions let me know

2024-04-15 21:05 UTC, RChandler234 requested changes

2024-04-15 21:05 UTC, RChandler234 commented on src/backend/src/controllers/projects.controllers.ts
> +      const { unitId } = req.params;
this should still be unitName, that's what the field is called in the schema

2024-04-16 13:50 UTC, bderbs30 approved these changes
LGTM 💸

2024-04-16 15:53 UTC, merged