#2076: made seed data for slackbot testing
Northeastern-Electric-Racing/FinishLine pull request #2297
Opened 2024-04-01 22:46 UTC by wavehassman

## Changes

added a team in the seed data named Mean Girls

## To Do

- [ ] document testing

## Checklist 

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2076

2024-04-02 22:32 UTC, jessicayzhao submitted a review, later dismissed
Mean Girls!! LGTM!

2024-04-03 01:43 UTC, walker-sean requested changes

2024-04-03 01:43 UTC, walker-sean commented on src/backend/src/prisma/seed-data/teams.seed.ts
> +const meanGirls = (headId: number): Prisma.TeamCreateArgs => {
Great choice of characters, but can the name of the team relate to Slack so it's more clear what it can be used for?

2024-04-03 21:18 UTC, RChandler234 requested changes

2024-04-03 21:18 UTC, RChandler234 commented on src/backend/src/prisma/seed-data/teams.seed.ts
> +      teamName: 'Mean Girls',
Ok damn, I love the Mean Girls, could you rename the team name to Slack Testing or smthn, and then we can keep all the mean girls stuff in the desc/ members

2024-04-04 02:44 UTC, RChandler234 approved these changes
LGTM 🔥

2024-04-04 02:44 UTC, merged