#2122: Added ability to delete assemblies
Northeastern-Electric-Racing/FinishLine pull request #2308
Opened 2024-04-04 01:19 UTC by rupjaisinghani0904

## Changes
Created menu that expands to show delete option
Delete button now makes call to delete assembly endpoint

## Notes

delete assembly endpoint implementation needed some changing 

Closes # 2122

2024-04-04 17:02 UTC, alaneng-neu requested changes

2024-04-04 17:02 UTC, alaneng-neu commented on src/frontend/src/utils/urls.ts
> -const userScheduleSettingsSet = () => `${users()}/schedule-settings/set`;
Your builds are failing because you deleted a lot of the urls that need to be in the code

2024-04-04 17:02 UTC, alaneng-neu commented on src/frontend/src/utils/urls.ts
> -  userScheduleSettings,
These should be added back into the code

2024-04-04 17:02 UTC, alaneng-neu commented on src/frontend/src/utils/urls.ts
> -  designReviewDelete,
Same with all of these

2024-04-04 17:12 UTC, alaneng-neu reviewed
Also make sure to add yourself as an assignee to the PR, and link the ticket to this PR (the last line of the PR comment should be Closes #2122) with no space between the # and ticket number

2024-04-05 04:46 UTC, alaneng-neu requested changes
Can you add screenshots of the UI changes like in the PR template?

2024-04-05 04:46 UTC, alaneng-neu commented on src/backend/src/services/projects.services.ts
> +      include: { wbsElement: true }
Why do you need to get the wbsElement?

2024-04-05 04:46 UTC, alaneng-neu commented on src/frontend/src/hooks/bom.hooks.ts
> + * @returns mutation function to delete a material
Make sure to change the docs for these 2 lines also

2024-04-19 23:56 UTC, alaneng-neu submitted a review, later dismissed

2024-04-20 03:38 UTC, RChandler234 approved these changes

2024-04-20 03:38 UTC, merged