2326 drc debugs set team teamtype endpoint
Northeastern-Electric-Racing/FinishLine pull request #2346
Opened 2024-04-13 18:48 UTC by AShyamkumar19

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-04-14 14:26 UTC, Aaryan1203 requested changes
Great work on your ticket! Just left a few comments

Can you also add the postman screenshots of the request you send to set the teamtype and the response you get back from it. in the screenshot I don't think I saw the set team type on the team

2024-04-14 14:26 UTC, Aaryan1203 commented on src/backend/src/controllers/teams.controllers.ts
> +      const updateTeamType = await TeamsService.setTeamType(submitter, req.params.teamId, teamTypeId);
can you destructure the teamId just like you do it for the teamTypeId, it just makes it a bit easier to read

2024-04-14 14:26 UTC, Aaryan1203 commented on src/backend/src/services/teams.services.ts
> +    }
can you move this check right after you define the teamType constant

2024-04-14 14:26 UTC, Aaryan1203 commented on src/backend/src/services/teams.services.ts
> +      throw new HttpException(400, 'Team type with the given ID does not exist');
can you throw a not found exception here as well

2024-04-14 14:54 UTC, Aaryan1203 requested changes
Also can you make your pr more descriptive, a lot of the parts of the template are left as original

2024-04-15 21:18 UTC, RChandler234 requested changes
looking really good!

2024-04-15 21:18 UTC, RChandler234 commented on src/backend/src/controllers/teams.controllers.ts
> +      const updateTeamType = await TeamsService.setTeamType(submitter, teamId, teamTypeId);
updatedTeam*

2024-04-15 21:18 UTC, RChandler234 commented on src/backend/src/services/teams.services.ts
> +  static async setTeamType(submitter: User, teamId: string, teamTypeId: string): Promise<Team> {
you should add a thorough comment to this

2024-04-15 21:18 UTC, RChandler234 commented on src/backend/src/services/teams.services.ts
> +    const updateTeam = await prisma.team.update({
updated*

2024-04-17 19:27 UTC, merged