#1904 Create CR from project edits
Northeastern-Electric-Racing/FinishLine pull request #2358
Opened 2024-04-19 23:28 UTC by alaneng-neu

## Changes

Added a button in the edit project form to create a change request from edits

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

- [ ] connect modal to submit functionality
- [ ] update inputs from the modal

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1904

2024-04-27 00:19 UTC, Peyton-McKee requested changes
If theres a reason why you have to do it this way lmk otherwise I feel like you should be using the forms we already have

2024-04-27 00:19 UTC, Peyton-McKee commented on src/backend/src/routes/change-requests.routes.ts
> +  body('proposedSolutions').isArray({ min: 0 }),
just delete the min part

2024-04-27 00:19 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectCreateChangeRequestForm.tsx
> +const ProjectCreateChangeRequestForm: React.FC<ProjectCreateChangeRequestFormProps> = ({
this shouldnt just be for projects, it should be for wbs elements, so we can use it with work packages too right @RChandler234

2024-04-27 00:19 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectCreateChangeRequestForm.tsx
> +  const renderReasonInput = (index: number) => {
this looks like a ton of repeat code from the actual create change request form, you should abstract absolutely as much as you possibly can between the two forms, honestly you should be using the actual create change request form but just dont force any proposed solutions

2024-05-01 22:48 UTC, alaneng-neu commented
> If theres a reason why you have to do it this way lmk otherwise I feel like you should be using the forms we already have

if this is a follow up to the comment:

> this looks like a ton of repeat code from the actual create change request form, you should abstract absolutely as much as you possibly can between the two forms, honestly you should be using the actual create change request form but just dont force any proposed solutions

its because reid wanted a modal for just those specific 3 fields, since it would be able to submit the project edits from the project edit form, and then those 3 fields would be able to be filled out by the user making the CR, as opposed to before when it was planned to just hard code values for them

2024-05-07 00:46 UTC, Peyton-McKee requested changes

2024-05-07 00:46 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
> +      onSubmitSecondary={onSubmitCreateChangeRequest}
rename to onSubmitChangeRequest

2024-05-07 00:46 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
>    const { mutateAsync, isLoading } = useEditSingleProject(project.wbsNum);
rename to mutate async to something more descriptive

2024-05-07 00:46 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
> +      exitEditMode();
this shoudl have you go to the change requests page.

2024-05-07 00:46 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
> +  const onSubmitCreateChangeRequest = async (data: ProjectCreateChangeRequestFormInput) => {
move this into the form, it can be used for both create and edit i believe kill two birds with one stone

2024-05-07 06:32 UTC, RChandler234 requested changes
Start the edit form with the change request field empty instead of prefilling it like we do now. 
Submit should be disabled if there isn't a change request entered into the field, and create change request should be disabled if there is, so that it's always very clear to the user which action they should be taking. I don't like the just ignoring the change request id if we choose to create a change request. 
I would also swap the position of the change request input and the budget input

2024-05-07 22:18 UTC, RChandler234 commented
I'm just gonna make a new branch in the interest of getting it done for the release

2024-05-07 22:43 UTC, closed without merging