#1944-CaioDaSilva-SortTable
Northeastern-Electric-Racing/FinishLine pull request #2363
Opened 2024-04-22 21:44 UTC by caiodasilva2005

## Changes

Added sorting functionality to refund table. Can now be sorted by amount or date in ascending or descending order.

## Notes

I added dropdown boxes to control selection for sorting, but this can be changed if needed.

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/145620095/989a141b-1cc0-45ff-b223-3a03c4cf5169)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/145620095/e5caa0ff-858f-434f-8fef-00174bb49a23)

## To Do

[] Change dropdown menus to another form of user input

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [X] All commits are tagged with the ticket number
- [X] No linting errors / newline at end of file warnings
- [X] All code follows repository-configured prettier formatting
- [X] No merge conflicts
- [X] All checks passing
- [X] Screenshots of UI changes (see Screenshots section)
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #1944

2024-04-25 02:03 UTC, RChandler234 requested changes

2024-04-25 02:03 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> -  const canViewAllReimbursementRequests = user.isFinance || isAdmin(user.role);
you should not be changing this line

2024-04-25 02:03 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +  ];
move this array above the component, since it's just a static array

2024-04-25 02:03 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +  const percentRefunded = (totalReceived / currentlyOwed) * 100;
why are you changing this line?

2024-04-25 02:03 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +  function handleSort(orderByIn: OrderBy) {
can you make this an arrow method

2024-04-25 02:03 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +function getComparator<Key extends keyof any>(
make this an arrow method

2024-04-25 02:03 UTC, RChandler234 commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +function descendingComparator<T>(a: T, b: T, orderBy: keyof T) {
make this an arrow method

2024-05-09 22:37 UTC, Peyton-McKee approved these changes
Looks good nice work

2024-05-09 22:37 UTC, merged