#2247 Added a Get Single TeamType Endpoint
Northeastern-Electric-Racing/FinishLine pull request #2367
Opened 2024-04-24 23:19 UTC by AShyamkumar19

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-04-25 01:53 UTC, Aaryan1203 requested changes
Great work on this!

Now you just gotta write tests

2024-04-25 19:42 UTC, Aaryan1203 requested changes
Great work, just one small comment

2024-04-25 19:42 UTC, Aaryan1203 commented on src/backend/tests/unmocked/team-type.test.ts
> +      await expect(async () => TeamsService.getSingleTeamType(nonExistingTeamTypeId)).rejects.toThrow(NotFoundException);
Throw a `new NotFoundException` and make sure it has the exact description of the exception that is being thrown. Look above at other tests that throw exceptions for an example

2024-04-25 23:19 UTC, Aaryan1203 approved these changes
Good work
LGTM!

2024-04-26 04:40 UTC, Aaryan1203 approved these changes
great work LGTM

2024-05-08 23:29 UTC, Peyton-McKee approved these changes

2024-05-08 23:30 UTC, merged