#1898 Fix Create CR Button
Northeastern-Electric-Racing/FinishLine pull request #2377
Opened 2024-05-05 19:29 UTC by Peyton-McKee

## Changes

Deleted separate route for creating a work package with a CR. Everything can be inferred by whether or not the button is pressed on the form. This makes the code much much cleaner and makes integrating it with projects and other wbs elements trivial to follow. 

## Screenshots

I tested it and it works. I assume the review scope cr change request hasnt been finished and thats why i cannot accept it without a proposed solution. 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1898  (issue #)

2024-05-05 19:37 UTC, RChandler234 requested changes
Looks really good 🔥🔥🔥

2024-05-05 19:37 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageForm/WorkPackageForm.tsx
>    mutateAsync: (data: WorkPackageApiInputs) => void;
Can u rename this one to be onFormSubmit (bad name) or smthn, since the other one u added is also technically a mutateAsync

2024-05-05 19:37 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
> +        title={`${wbsPipe(wbsElement.wbsNum)} - ${wbsElement.name}`}
Not at my laptop so apologies if u added this and I missed it, can u add this info bubble with tooltip somewhere that makes sense, I want ppl to be able to figure out how to use this form with no ambiguity with just the info on the page without having to ask us.

You can also just delete this code u commented out if it's somewhere else

2024-05-06 00:00 UTC, walker-sean requested changes

2024-05-06 00:00 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
> +  console.log(crWatch);
Remove this

2024-05-06 01:35 UTC, walker-sean approved these changes

2024-05-06 01:35 UTC, merged