Put columns into icons for BOMS
Northeastern-Electric-Racing/FinishLine pull request #2379
Opened 2024-05-06 21:12 UTC by ryanhowe28

## Changes

instead of a column, made notes and links into icons
## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/102765855/206ca1d7-5f4f-4092-9f07-e0e307d5cbf2)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1877

2024-05-07 23:47 UTC, Peyton-McKee requested changes
we should make the title of the column actions it looks not great with no title

also on medium to small screens they dissapear they should be combined into one icon

2024-05-07 23:47 UTC, Peyton-McKee commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListDataGrid.tsx
> +              console.log('hitting this button');
fart

2024-05-12 03:45 UTC, ryanhowe28 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListDataGrid.tsx
> +              console.log('hitting this button');
lmaoooo

2024-05-12 17:50 UTC, Peyton-McKee approved these changes
noice

2024-05-12 17:59 UTC, merged