#139- Renamed seed files
Northeastern-Electric-Racing/FinishLine pull request #254
Opened 2022-09-29 00:06 UTC by ryanhowe28

## Changes
Re-named seed-data files
Added "seed" to the name in all the files in backend/src/prisma/seed-data

#139

2022-09-29 20:22 UTC, Ari-S-123 approved these changes
lgtm

2022-09-30 01:41 UTC, Ari-S-123 requested changes
You need to update the imports in seed.ts too.

2022-09-30 02:36 UTC, anthonybernardi requested changes

2022-09-30 02:36 UTC, anthonybernardi commented on src/backend/src/prisma/seed.ts
> -  for (const seedTeam of dbSeedAllTeams) {
this was deleted by accident

2022-10-02 16:12 UTC, anthonybernardi approved these changes
nice work!

2022-10-02 16:13 UTC, merged