#162 peyton mckee
Northeastern-Electric-Racing/FinishLine pull request #256
Opened 2022-09-29 16:54 UTC by Peyton-McKee

## Changes
Created validations.utils to house intMinZero function 

Created intMinZero function to replace .isInt({ min: 0 }).not().isString() that covers much of the routing files 

## Notes

No extra notes

## Test Cases

Ran tests built into project not sure if I need to make more?

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ x] All commits are tagged with the ticket number
- [ x] No linting errors / newline at end of file warnings
- [ x] All code follows repository-configured prettier formatting
- [ x] No merge conflicts
- [x ] All checks passing
- [x ] Remove any non-applicable sections of this template
- [ x] Assign the PR to yourself
- [ x] No `yarn.lock` changes (unless dependencies have changed)
- [ x] Request reviewers & ping on Slack
- [x ] PR is linked to the ticket (fill in the closes line below)

Closes #255   (issue #255)

2022-09-29 20:20 UTC, Ari-S-123 approved these changes
lgtm

2022-09-30 00:38 UTC, anthonybernardi requested changes
great start! Aside from the comment I put, the other thing we want to do is test that the validation still works. You can do this by running the app then sending http requests with an app like postman. Put screenshots of your request and the response in the pr.

Also contributor guideline stuff:
* make sure to tag all commits with the issue # (# sign is important)
* give pr and branch a meaningful name relative to the ticket (branch is fine cuz it's too late, but you can edit pr name)
* make sure this pr is linked to the ticket on the right side where it says development

2022-09-30 00:38 UTC, anthonybernardi commented on src/backend/src/utils/validation.utils.ts
> +export const intMinZero = (validationObject: any): any => {
validationObject should not be type `any` or return `any` either. check out what the types of the body('asdf') things are in the routes files and put that here

2022-09-30 02:39 UTC, anthonybernardi requested changes
the login endpoint doesn't use any of these validators that you changed. try one like /risks/create -- you'll have to mkae the body match what it's supposed to be in the risks route file. then try it by making the projectId invalid or something (not a >=0 int) and it should fail. if it doesn't fail then validation is now broken

2022-10-02 17:45 UTC, anthonybernardi approved these changes
awesome work! thanks for doing the testing too

2022-10-02 17:45 UTC, merged