2159 work package templates hook up to createedit wp pages
Northeastern-Electric-Racing/FinishLine pull request #2607
Opened 2024-05-26 02:22 UTC by AShyamkumar19

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-05-26 21:36 UTC, Peyton-McKee requested changes
Your tests are failing you may have to merge develop into your branch

2024-06-12 03:10 UTC, superhvarn requested changes
Remove the project hook changes

2024-06-12 03:33 UTC, superhvarn submitted a review, later dismissed

2024-06-14 19:42 UTC, walker-sean requested changes
This is looking really good so far!

A few things we're missing:
- We need to also apply the blocked by information (you can look at the ticket to see the logic that goes into that
- We need to check whether a user has input new data into the field. If they have, do not overwrite. This can be done by comparing the value to default value (empty or an actual value if its an edit)

2024-06-14 19:42 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageForm/WorkPackageTemplateDetails.tsx
> +      <Box sx={{ display: 'flex', flexDirection: 'row' }}>
See if you can make this component cause the cursor to go into "click mode"

2024-06-14 19:42 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageForm/WorkPackageTemplateDetails.tsx
> +export const WorkPackageTemplateSection: React.FC<WorkPackageTemplateProps> = ({
Rename the file to match the component name

2024-06-17 22:54 UTC, superhvarn requested changes
lgtm just make sure to keep the text within the work package template boxes when collapsing the screen

2024-06-17 23:10 UTC, Aaryan1203 commented on src/frontend/src/pages/WorkPackageForm/WorkPackageTemplateSection.tsx
> +              height: { xs: '4em', sm: '5em', md: '6em', lg: '7em' },
See if there is a better way to do this for the styling, this isn't good practice

2024-06-17 23:10 UTC, superhvarn commented on src/frontend/src/pages/WorkPackageForm/WorkPackageTemplateSection.tsx
> +              height: { xs: '4em', sm: '5em', md: '6em', lg: '7em' },
I concur

2024-06-17 23:19 UTC, superhvarn approved these changes
lgtm

2024-06-18 18:08 UTC, walker-sean approved these changes
LGTM

2024-06-18 18:09 UTC, merged