#2423-added arrow icon and decreased margin
Northeastern-Electric-Racing/FinishLine pull request #2627
Opened 2024-05-30 01:49 UTC by caiodasilva2005

## Changes

 Changed open button for side bar to arrow icon and decreased page margins slightly to fit more content

## Notes

 This was a follow up on making the side bar collapsible

## Screenshots

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/145620095/114d648f-21ba-4d76-aef2-4a03ab945064)

## Checklist

- [X] All commits are tagged with the ticket number
- [X] No linting errors / newline at end of file warnings
- [X] All code follows repository-configured prettier formatting
- [X] No merge conflicts
- [X] All checks passing
- [X] Screenshots of UI changes (see Screenshots section)
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [X] Request reviewers & ping on Slack
- [X]  PR is linked to the ticket (fill in the closes line below)

Closes #2423

2024-06-01 22:01 UTC, Peyton-McKee requested changes
Acceptance Changes requested in slack

2024-06-08 22:21 UTC, walker-sean requested changes
Sweet! The movecontent stuff is really nice

2024-06-08 22:21 UTC, walker-sean commented on src/frontend/src/layouts/Sidebar/Sidebar.tsx
> +  console.log('NEW BAR-----------------');
remove

2024-06-08 22:21 UTC, walker-sean commented on src/frontend/src/components/HiddenContentMargin.tsx
> +export const DRAWERWIDTH = 200;
This can be imported from NERDrawer

2024-06-08 22:21 UTC, walker-sean commented on src/frontend/src/layouts/Sidebar/Sidebar.tsx
> +          <Box justifyContent={drawerOpen ? 'flex-start' : 'center'}>
This content should stay at the bottom of the sidebar, not directly following after the links

2024-06-22 03:02 UTC, walker-sean approved these changes

2024-06-22 03:03 UTC, walker-sean approved these changes

2024-06-22 03:03 UTC, merged