#2496 change delete work package view to ner form modal
Northeastern-Electric-Racing/FinishLine pull request #2629
Opened 2024-05-30 20:01 UTC by vsp05

## Changes

Changed the Dialog component on the DeleteWorkPackageView to a NERFormModal.

## Test Cases
testing to make sure the functionality still works - i.e. that when you delete a work package, it does, in fact, delete it.
Before deleting WP 0.5.1:
<img width="1710" alt="Screenshot 2024-05-30 at 3 50 04 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/f4dc7e87-f701-4c07-9623-0b8d3c46bbc9">
Process of actually deleting WP 0.5.1:
<img width="1710" alt="Screenshot 2024-05-30 at 3 50 34 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/1b5ebb35-21a3-4d5f-a9d5-1db4c1da2fd6">
After deleting WP 0.5.1:
<img width="1710" alt="Screenshot 2024-05-30 at 3 51 07 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/8a7b379f-32f7-429f-bdb7-5e38fa0107f3">

second test - making sure that you can't delete a WP unless you enter in the proper name:
what shows up when you try to click the delete button without entering anything into the WBSnum field:
<img width="594" alt="Screenshot 2024-05-30 at 3 52 31 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/6da16e95-6c6b-462d-861b-952dd850290c">
what shows up when you try to click the delete button after entering the wrong WBSnum into the WBSnum fields:
<img width="583" alt="Screenshot 2024-05-30 at 3 53 35 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/957b179b-c831-4d21-81da-1849bbcedf5a">

## Screenshots
Full-sized window:
before:
<img width="1710" alt="Screenshot 2024-05-30 at 3 56 31 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/1030c9cb-0336-4e34-a6e5-8eccf59c018a">

after:
<img width="1710" alt="Screenshot 2024-05-30 at 3 55 12 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/99883a74-702b-474d-bf55-c9ecd5328914">

Smallest possible window:
before (you are able to scroll to see the full message):
<img width="492" alt="Screenshot 2024-05-30 at 3 57 09 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/2fa32d94-2c02-47ce-88d4-1adf4b1d0756">

after (you are able to scroll):
<img width="495" alt="Screenshot 2024-05-30 at 3 55 50 PM" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/70610902/4308ffbc-eae7-4450-b875-4b7b4b33682b">

Closes #2496

2024-05-31 00:46 UTC, superhvarn requested changes
Good work so far!

2024-05-31 00:46 UTC, superhvarn commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackageView.tsx
> +      name: ''
Does name do anything here? If not, you can delete it.

2024-05-31 20:06 UTC, superhvarn submitted a review, later dismissed
LGTM!

2024-05-31 21:19 UTC, walker-sean requested changes
Nice!

2024-05-31 21:19 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackageView.tsx
>  interface DeleteWorkPackageViewProps {
For the yup schema add a custom message for the required() section saying 'WBS number is required'

2024-05-31 21:19 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackageView.tsx
> +      <Typography sx={{ fontWeight: 'bold' }}>This action cannot be undone!!</Typography>
Love the enthusiasm, but one exclamation point is good for this

2024-05-31 21:19 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackageView.tsx
> +          To confirm deletion, please type in the WBS number of this Work Package.
Nitpick: work package does not need to be capitalized

2024-05-31 21:19 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackageView.tsx
> +    <NERFormModal
Could you disable the delete button until the wbs number is correct

2024-06-12 20:44 UTC, walker-sean approved these changes
LGTM

2024-06-12 20:44 UTC, merged