#2628 Delete Work Package Template Button
Northeastern-Electric-Racing/FinishLine pull request #2645
Opened 2024-06-03 19:22 UTC by walker-sean

## Changes

Added delete buttons for work package templates and a modal to confirm that connects to the hook

## Notes
I also fixed some typos I found

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/114596410/956aa329-bdf3-4c27-b180-ddc23c18728a)

![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/114596410/9f914469-9012-426f-90d4-aa9f0193f91d)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2628

2024-06-03 19:33 UTC, Peyton-McKee requested changes
Shwag

2024-06-03 19:33 UTC, Peyton-McKee commented on src/frontend/src/hooks/work-packages.hooks.ts
> +    ['work package templates', 'delete'],
Can u change the create worn package template funtion below these to have the s as well

2024-06-03 19:33 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/ProjectsConfig/WorkPackageTemplateTable.tsx
> +        <Typography>This will also delete all templates blocked by this one.</Typography>
Add a statement saying if you wish to only delete this work package template, remove any reference to this template from any other templates blocked bys. But put that into chatgpt to be more clear

2024-06-03 20:20 UTC, Peyton-McKee approved these changes
This looks good we probably shouldnt merge it until aaryans is good if u wanna check that out first. Also i think he mightve made the hooks in that one too

2024-06-04 00:59 UTC, Aaryan1203 commented
> This looks good we probably shouldnt merge it until aaryans is good if u wanna check that out first. Also i think he mightve made the hooks in that one too

Wait I think my hooks are merged in already? @Peyton-McKee

2024-06-04 01:05 UTC, Peyton-McKee commented
oh right I forgot i merged that, does that mean we now have two sets of hooks? @walker-sean can you see if theres any duplicates in that file if you merge develop?

2024-06-04 01:05 UTC, Peyton-McKee commented
oh nevermind then I missed that

2024-06-04 01:06 UTC, merged