Refs/heads/2157 work package templates createedit form
Northeastern-Electric-Racing/FinishLine pull request #2646
Opened 2024-06-04 02:00 UTC by superhvarn

## Changes

- Clicking on a work package template will take user to edit form
- Clicking create new work package template will also take the user to the form
- Work Package Template Details and Work Package Details
- Blocked By is autofilled in the edit form

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-06-12 23:39 UTC, Aaryan1203 requested changes
Can't delete a work opackage template anymore. I think the link takes up the entire component.

The cancel button doesn't work on the edit page

2024-06-12 23:44 UTC, Aaryan1203 requested changes
looks mostly good just a couple comments

2024-06-12 23:44 UTC, Aaryan1203 commented on src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx
> -      <Typography variant="h5" gutterBottom borderBottom={1} color="#ef4345" borderColor={'white'}>
whyd you get rid of this?

2024-06-12 23:44 UTC, Aaryan1203 commented on src/frontend/src/pages/AdminToolsPage/ProjectsConfig/WorkPackageTemplateTable.tsx
> +  */
dellete this

2024-06-12 23:44 UTC, Aaryan1203 commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateForm.tsx
> +    console.log(workPackageTemplate);
delete

2024-06-16 02:59 UTC, Aaryan1203 submitted a review, later dismissed
lgtm

2024-06-17 01:12 UTC, walker-sean requested changes
Nice! I really love the form, and it works really well!

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateFormView.tsx
> +      toast.success('Work Package Template submitted successfully');
This should say 'Work package template edited successfully' on edit

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/ProjectsConfig/WorkPackageTemplateTable.tsx
> +  const workPackageTemplateRows = workPackageTemplates.map((workPackageTemplateId) => (
Replace `workPackageTemplateId` here with `workPackageTemplate`

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/CreateWorkPackageTemplate.tsx
> +      exitActiveMode={() => history.push(routes.ADMIN_TOOLS)}
You can use `history.goBack()` so that you go back to the project config tab

Also, because this is the same for both forms, you can move this another level deeper and not use a prop or `WorkPackageTemplateForm`

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/CreateWorkPackageTemplate.tsx
> +  const schema = yup.object().shape({
The schemas match each other so you can move this down a level deeper

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateForm.tsx
> +    workPackageTemplate = workPackageTemplates?.find((wpt) => wpt.workPackageTemplateId === workPackageTemplateId);
use `useSingleWorkPackageTemplate`

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateForm.tsx
> +  let workPackageTemplate;
To avoid all of these conditional checks, you can have an optional `defaultValues` prop in this component, and pass it in from the Edit component where you know the values will exist

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/EditWorkPackageTemplate.tsx
> +  setPageMode: (value: React.SetStateAction<boolean>) => void;
I don't think you need this

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/EditWorkPackageTemplate.tsx
> +const EditWorkPackageForm: React.FC<EditWorkPackageTemplateProps> = () => {
EditWorkPackageTemplate

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateFormView.tsx
> +    const blockedByWbsNums = blockedBy.map((blocker) => blocker.id);
blockedByIds

2024-06-17 01:12 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateFormView.tsx
> +            <DescriptionBulletsEditView
Could this go in the same file as the other fields or do you think it won't fit?

2024-06-17 01:13 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateForm.tsx
> +  let workPackageTemplate;
And you could use the useSingleWorkPackageTemplate hook there to get the values

2024-06-20 20:03 UTC, walker-sean commented on src/frontend/src/pages/AdminToolsPage/ProjectsConfig/WorkPackageTemplateTable.tsx
> +  const workPackageTemplateRows = workPackageTemplates.map((workPackageTemplateId) => (
Each item of the list is a template, not an id, so this needs to be updated

2024-06-20 20:18 UTC, walker-sean requested changes
Nice!

2024-06-20 20:18 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/EditWorkPackageTemplate.tsx
> +  const defaultValues = {
Import the type for this (which can be renamed WorkPackageTemplateFormInputs or something to declare the type here

You can actually use the spread operator for all of the fields, and will just manually need to override stage and blocked by

2024-06-20 20:18 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateForm.tsx
> +    duration: yup.number().required()
add a custom required message here too

2024-06-26 19:04 UTC, walker-sean requested changes

2024-06-26 19:04 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateFormView.tsx
> +      console.error('Error submitting work package template:', error);
Remove

2024-06-26 19:04 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/EditWorkPackageTemplate.tsx
> +  console.log('SINGLE', workPackageTemplate);
Remove

2024-06-26 19:04 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateForm.tsx
> +  console.log('ALL', workPackageTemplates);
Remove

2024-06-26 19:04 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateForm.tsx
> +  const schema = yup.object().shape({
Add the rest of the form fields to the schema and use the type to determine which fields should be optional and required

2024-06-26 19:04 UTC, walker-sean commented on src/frontend/src/pages/WorkPackageTemplateForm/WorkPackageTemplateFormView.tsx
> +      duration: defaultValues?.duration ?? 0,
Duration is actually optional so we dont want this 0, (will set 0 as the duration when we don't want any duration set)

2024-07-02 23:44 UTC, walker-sean approved these changes
LGTM

2024-07-02 23:44 UTC, merged