#2313 set dr status endpoint
Northeastern-Electric-Racing/FinishLine pull request #2657
Opened 2024-06-08 06:40 UTC by bracyw

## Changes

Created a endpoint for setting the status of a design review. It can be used by the creator of the design review or app admins. Implemented behavior in design-review, routes, controllers, and services files.

NEW: added unmocked tests

## Test Cases
- change with app admin who is not creator
- set status works when creator is not admin
- fails when user is not admin or creator

tested with postman, results shown below

## Screenshots
before change - with app admin:
<img width="994" alt="Valid set status (with app admin who is not creator) - before" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/138251570/0abf1ae2-c102-4602-8e45-7ed7681e68f2">
after change - with app admin:
<img width="1024" alt="Valid set status with app admin (who is not creator) - after" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/138251570/65a666b0-5999-44b1-a20b-bf2e003c15ca">

set status works when creator is not admin
<img width="1004" alt="Valid set status (creator who is not admin)" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/138251570/37f08d09-629b-4c96-a420-a4aeba4d8fed">

invalid when user is not admin or creator
<img width="1005" alt="Invalid user set status" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/138251570/bc5d7a60-4824-4242-a185-537eaee4ba34">

invalid status - produces error
<img width="1004" alt="Invalid status - error" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/138251570/bca0efa5-44ee-4082-bc32-73b4d70570b4">

## To Do

_Any remaining things that need to get done_

- [ ] Fix variable type issue (described in comments)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2313

2024-06-09 02:19 UTC, superhvarn requested changes
Looks like some checks are failing. You might need to have more exceptions in the controller method.

2024-06-16 17:19 UTC, superhvarn commented on src/backend/src/controllers/design-reviews.controllers.ts
> +      return res.status(200).json(updatedDesignReview);
I don't think you have to do a return here.

2024-06-16 17:23 UTC, superhvarn requested changes
lgtm, just fix that controller thing

2024-06-16 17:54 UTC, superhvarn approved these changes, later dismissed
LGTM

2024-06-17 03:17 UTC, walker-sean requested changes
Nice work! Just some comments on the tests

2024-06-17 03:17 UTC, walker-sean commented on src/backend/tests/unmocked/design-review.test.ts
> +  // change with app admin who is not creator
There is actually a distinction between app admins and simply admins - we are just concerned with admins for this

2024-06-17 03:17 UTC, walker-sean commented on src/backend/tests/unmocked/design-review.test.ts
> +describe('Design Reviews', () => {
These tests are taking on a lot more than they need to, meaning they are becoming very complicated. Take a look at our other unmocked tests and see the structure they fall into, making a call to the endpoint in a specific test case, and checking against what we expect in that case. Anything beyond that is really testing other endpoints or functionality, which is too much overhead for these tests

2024-06-17 03:17 UTC, walker-sean commented on src/backend/tests/unmocked/design-review.test.ts
> +describe('Design Reviews', () => {
Writing concise, effective tests can be tough to figure out, so let me (or a tech lead) know if you need help and the other examples aren't helping

2024-06-20 20:20 UTC, walker-sean approved these changes

2024-06-20 20:21 UTC, merged