#1587: added everything from previous wrong branch (made off of develop)
Northeastern-Electric-Racing/FinishLine pull request #2662
Opened 2024-06-12 02:09 UTC by tigerhippo

## Changes

- work-packages.routes.ts delete route takes in a CR ID (the identifier field of a CR)
- work-packages.controllers.ts delete method gets CR ID from request body and passes that into the service function
- work-packages.services.ts delete method takes in CR ID, makes a Change on the CR corresponding to the given CR ID (which states that the WP is deleted), then soft deletes the WP

## To Do

- yarn test:frontend 
- yarn test:backend 
- test to check that FinishLine starts up and is working

## Checklist

- [X] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [X] Screenshots of UI changes (see Screenshots section)
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #1587

2024-06-20 18:36 UTC, Zwendle approved these changes

2024-06-20 20:55 UTC, walker-sean requested changes
Looking good

The identifier is really just used as a user facing way to distinguish change requests. For the backend functions and prisma functions, you still need to use the crId

2024-06-20 20:55 UTC, walker-sean commented on src/backend/src/services/work-packages.services.ts
> +    await validateChangeRequestAccepted(identifier.toString());
this function takes the id of the cr, not the identifier

2024-06-20 20:55 UTC, walker-sean commented on src/backend/src/services/work-packages.services.ts
> +        changeRequestId: identifier.toString(),
This should also be the change request id

2024-06-20 20:55 UTC, walker-sean commented on src/backend/src/controllers/projects.controllers.ts
> +      const deletedProject: Project = await ProjectsService.deleteProject(user, wbsNumber, identifier, organizationId);
For references to the identifier, call it changeRequestIdentifier to not be ambiguous

2024-06-26 19:11 UTC, walker-sean requested changes
Still some references/usages of a CrId over an identifier which I marked

2024-06-26 19:11 UTC, walker-sean commented on src/backend/src/controllers/projects.controllers.ts
> +      const deletedProject: Project = await ProjectsService.deleteProject(user, wbsNumber, crId, organizationId);
Here

2024-06-26 19:11 UTC, walker-sean commented on src/backend/src/controllers/work-packages.controllers.ts
> +      await WorkPackagesService.deleteWorkPackage(user, wbsNum, crId, organizationId);
Here

2024-06-26 19:11 UTC, walker-sean commented on src/backend/src/services/projects.services.ts
> +  static async deleteProject(user: User, wbsNumber: WbsNumber, crId: string, organizationId: string): Promise<Project> {
Here

2024-06-26 19:11 UTC, walker-sean commented on src/backend/src/services/projects.services.ts
> +  static async deleteProject(user: User, wbsNumber: WbsNumber, crId: string, organizationId: string): Promise<Project> {
Add the change to the work package here too

2024-06-26 19:11 UTC, walker-sean commented on src/backend/src/services/work-packages.services.ts
> +  static async deleteWorkPackage(submitter: User, wbsNum: WbsNumber, crId: string, organizationId: string): Promise<void> {
here

2024-06-26 19:11 UTC, walker-sean commented on src/backend/src/services/work-packages.services.ts
> +    await validateChangeRequestAccepted(crId);
This takes a changeRequestId, not an identifier. You need to find the CR using the identifier, and then use its id

2024-07-07 01:56 UTC, walker-sean requested changes
Drop some Postman screenshots as well and you should be good to go

2024-07-07 01:56 UTC, walker-sean commented on src/backend/src/routes/projects.routes.ts
> +projectRouter.delete('/:wbsNum/delete', nonEmptyString(body('changeRequestIdentifier')), ProjectsController.deleteProject);
You can replace `nonEmptyString` with `intMinZero`, and add `validateInputs`

2024-07-07 01:56 UTC, walker-sean commented on src/backend/src/routes/work-packages.routes.ts
> +  nonEmptyString(body('changeRequestIdentifier')),
Same here

2024-07-07 01:56 UTC, walker-sean commented on src/backend/src/services/work-packages.services.ts
> +    const changeRequest = await prisma.change_Request.findFirst({
Try `findUnique` here. If it doesn't work you can change it back

2024-08-19 17:47 UTC, walker-sean approved these changes

2024-08-19 17:47 UTC, merged