#2636 created getAllUsefulLinks endpoint
Northeastern-Electric-Racing/FinishLine pull request #2669
Opened 2024-06-13 03:03 UTC by Aaryan1203

## Changes

Created get all useful links endpoint
Added it to the organization's route

## Test Cases

Passes
![Screenshot 2024-06-12 at 10 47 58 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76594216/c7813bad-aadf-4e80-b963-1e210820ace6)

Fails if user is not an admin
![Screenshot 2024-06-12 at 11 02 27 PM](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76594216/6c034b70-4eb7-4245-a420-28de253e06dc)

Fails if organization doesn't exist
![image](https://github.com/Northeastern-Electric-Racing/FinishLine/assets/76594216/579a1895-70da-4c45-aab7-3a03fff82923)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2636

2024-06-16 03:17 UTC, superhvarn requested changes
lgtm, just a typo on line 113 of unmocked tests

2024-06-16 03:21 UTC, superhvarn approved these changes, later dismissed
lgtm

2024-06-16 03:21 UTC, superhvarn commented on src/backend/tests/unmocked/organization.test.ts
> +    it('succeds and gets all the links', async () => {
typo

2024-06-16 21:34 UTC, walker-sean requested changes

2024-06-16 21:34 UTC, walker-sean commented on src/backend/src/services/organizations.service.ts
> +  static async getAllUsefulLinks(submitter: User, organizationId: string) {
Add JSDoc here to document the service function

2024-06-16 21:34 UTC, walker-sean commented on src/backend/src/services/organizations.service.ts
> +    if (!(await userHasPermission(submitter.userId, organizationId, isAdmin)))
We don't want this check because the get all endpoint will be used to display links on the homepage, which we want everyone to be able to see

2024-06-17 13:28 UTC, walker-sean requested changes

2024-06-17 13:28 UTC, walker-sean commented on src/backend/src/services/organizations.service.ts
> +    if (!organization) {
Missed this the first time through -- change this to be a `NotFoundException` and this is good to go

2024-06-20 20:57 UTC, walker-sean approved these changes

2024-06-20 20:57 UTC, merged