#2674 Fixed reimbursement request bug
Northeastern-Electric-Racing/FinishLine pull request #2677
Opened 2024-06-24 03:49 UTC by AShyamkumar19

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-06-24 03:50 UTC, Aaryan1203 requested changes
prettier check is failing

2024-06-24 04:10 UTC, Aaryan1203 requested changes
Make sure to update your pr so its descriuptive

2024-06-26 00:11 UTC, superhvarn approved these changes, later dismissed
LGTM

2024-06-26 19:53 UTC, walker-sean requested changes

2024-06-26 19:53 UTC, walker-sean commented on src/frontend/src/pages/FinancePage/RefundsSection.tsx
> +  ).filter((request: ReimbursementRequest) => request.reimbursementStatuses[0].type !== ReimbursementStatusType.DENIED);
This looks at the first status, we actually want to check the most recent (last status in the array)

2024-06-29 23:52 UTC, superhvarn approved these changes
Logic for the filter looks good to me

2024-06-30 23:31 UTC, walker-sean reviewed
LGTM

2024-06-30 23:31 UTC, walker-sean approved these changes

2024-06-30 23:32 UTC, merged