#2611 auto implementing change requests edit project form warn about required links
Northeastern-Electric-Racing/FinishLine pull request #2690
Opened 2024-07-02 17:54 UTC by Zwendle

## Changes

Implemented yup schema so that its errors for required links pop up below the URL boxes in the project edit page

## Notes

- any http link will cause the error to disappear even if it doesn't match the correct box (ie: putting https://youtube.com for the Confluence URL will cause the "Invalid URL" error to disappear)
- the URL boxes are shifted up due to the error text so they no longer align with the link type boxes (looks a little funky)

## Screenshots

<img width="1728" alt="Screenshot 2024-07-02 at 13 38 55" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/fa2da54e-e159-4b19-be24-014469fb4ccc">
<img width="1728" alt="Screenshot 2024-07-02 at 13 39 47" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/0bff952d-fdc5-47ac-8eea-e7ab52885047">
<img width="1728" alt="Screenshot 2024-07-02 at 13 40 13" src="https://github.com/Northeastern-Electric-Racing/FinishLine/assets/90429900/a1a368ae-96c7-4688-bf9a-bf0ec774f0a9">

## To Do

- [ ] check URL types to make sure they match the link type in the left boxes (if needed)
- [ ] adjust the placement of the link type boxes when errors show up (if needed)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-07-04 20:02 UTC, vsp05 requested changes
looks good, except for the part where the boxes shift up when the errormessage is displayed ... I'm not really sure how to fix that, but I guess you should play around with the sx in the linkseditview.tsx and maybe that'll do it?

2024-07-04 20:02 UTC, vsp05 commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx
> +                    <Typography fontSize={'15px'}>
Just out of curiosity, why did you change the font size here?

2024-07-07 19:44 UTC, Zwendle commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx
> +                    <Typography fontSize={'15px'}>
O that was just to make the second commit idk my vscode's kinda weird

2024-07-07 19:44 UTC, Zwendle commented on src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx
> +                    <Typography fontSize={'15px'}>
Changed it back to 16 in the most recent commit tho

2024-07-18 03:57 UTC, vsp05 approved these changes
LGTM!

2024-07-25 21:42 UTC, walker-sean approved these changes
LGTM

2024-07-25 21:42 UTC, merged