#2699 created models for FAQs and Milestone
Northeastern-Electric-Racing/FinishLine pull request #2720
Opened 2024-07-20 01:52 UTC by Aaryan1203

## Changes
Created models for FAQs and Milestones
## Notes

Still need to create shared types

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-07-22 12:53 UTC, Peyton-McKee requested changes
Looks good

2024-07-22 12:53 UTC, Peyton-McKee commented on src/backend/src/prisma/schema.prisma
> +  dateDeleted               DateTime?
these need to be linked to an organization

2024-07-22 12:53 UTC, Peyton-McKee commented on src/backend/src/prisma/schema.prisma
> +  milestoneId   String    @id @default(uuid())
needs to be linked to an organization

2024-07-22 12:53 UTC, Peyton-McKee commented on src/backend/src/prisma/schema.prisma
> +  description   String?
I dont think this needs to be optional, we can just have it be an empty string

2024-07-23 21:45 UTC, walker-sean approved these changes

2024-07-23 21:45 UTC, merged