#238 Created two tests for work-packages
Northeastern-Electric-Racing/FinishLine pull request #275
Opened 2022-10-03 03:31 UTC by Peyton-McKee

## Changes

Created tests checking whether the user is a guest or invalid and will return an error is so. Also created a guest user for a mock in checking the test. Moved changeBatmobile and createWorkPackagePayload to projects.test-data to organize code more(not sure if I'm allowed to do that).

## Notes
When doing this I initially tried to alter the physical request so the userId was one that wasn’t in the database and that threw me a compiler error rather than a unit test error. Not sure if I should alter my code to address this issue? 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #238  (issue #263)

2022-10-04 02:03 UTC, anthonybernardi requested changes
awesome work!! all my changes are pretty small stuff

2022-10-04 02:03 UTC, anthonybernardi commented on src/backend/tests/test-data/users.test-data.ts
> +export const guestUser = {
if making a new user, give them unique info than the old ones because then we can distinguish them better

2022-10-04 02:03 UTC, anthonybernardi commented on src/backend/tests/test-data/projects.test-data.ts
> +export const createWorkPackagePayload = {
the payloads can stay in the test files

2022-10-04 02:03 UTC, anthonybernardi commented on src/backend/tests/test-data/projects.test-data.ts
> +export const changeBatmobile = {
this is a change request obejct, so put it in a new `change-requests.test-data.ts` file

2022-10-04 02:03 UTC, anthonybernardi commented on src/backend/tests/test-data/projects.test-data.ts
> +export const createWorkPackagePayload = {
actually putting this in a data file isn't that bad, but it hsould be in a new file `work-packages.test-data.ts`

2022-10-04 02:03 UTC, anthonybernardi commented on src/backend/tests/work-packages.test.ts
> +    afterEach(() => {
the `afterEach` goes directly inside the describe (not inside tests) and it already exists in this file so you don't need to make a new one

2022-10-04 02:03 UTC, anthonybernardi commented on src/backend/tests/work-packages.test.ts
> +    afterEach(() => {
same thing as my other comment

2022-10-04 02:04 UTC, anthonybernardi commented on src/backend/tests/test-data/users.test-data.ts
> +export const guestUser = {
feel free to do any character you want, i was doing superhero stuff earlier. i think it makes it more fun lol

2022-10-04 02:27 UTC, Ari-S-123 approved these changes
lgtm

2022-10-05 21:18 UTC, anthonybernardi approved these changes
awesome work!

2022-10-05 21:18 UTC, merged