2707 recruitment deletemilestone endpoint
Northeastern-Electric-Racing/FinishLine pull request #2751
Opened 2024-08-07 19:22 UTC by AShyamkumar19

## Changes

Deletes a milestone based on the milestone id and organization id

## Screenshots

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2707

2024-08-08 14:48 UTC, Aaryan1203 requested changes
Great job! your tests look rlly good. Just a couple things and then it looks good for me

2024-08-08 14:48 UTC, Aaryan1203 commented on src/backend/tests/test-utils.ts
> +export const createTestMileStone = async (user: User, organizationId: string) => {
createTestMilestone*

2024-08-08 14:48 UTC, Aaryan1203 commented on src/backend/tests/unmocked/recruitment.test.ts
> +      ).rejects.toThrow(new HttpException(400, 'Milestone with id: id1 not found!'));
thijs should throw a not found exception

2024-08-08 14:48 UTC, Aaryan1203 commented on src/backend/tests/unmocked/recruitment.test.ts
> +      const [testMilestone1] = await Promise.all([createTestMileStone(testSuperman, orgId)]);
there is no need to make this an array and use promise.all. instead do it how you did it above on line 108

2024-08-08 22:02 UTC, superhvarn submitted a review, later dismissed
lgtm

2024-08-09 11:19 UTC, Peyton-McKee requested changes

2024-08-09 11:19 UTC, Peyton-McKee commented on src/backend/src/services/recruitment.services.ts
> +    if (!organizationId) throw new NotFoundException('Organization', organizationId);
You need to actually try to get the organization. Not just check if the orgid exists

2024-08-11 05:39 UTC, Aaryan1203 requested changes
couple comments but rlly nice job

2024-08-11 05:39 UTC, Aaryan1203 commented on src/backend/src/routes/recruitment.routes.ts
> +recruitmentRouter.get('/milestones', RecruitmentController.getAllMilestones);
remove this its already there, i think it got added when we did merge confclits

2024-08-11 05:39 UTC, Aaryan1203 commented on src/backend/tests/unmocked/recruitment.test.ts
> +  describe('Delete a single milestone', () => {
add a test for if the organiztion doesn't exist

2024-08-11 20:35 UTC, Aaryan1203 submitted a review, later dismissed
lgtm

2024-08-12 03:11 UTC, walker-sean requested changes
Quick comment + merge conflicts

2024-08-12 03:11 UTC, walker-sean commented on src/backend/src/services/recruitment.services.ts
> +   * @param deleter the name of the user deleting the milestone
This isn't a name, it's the user

2024-08-12 21:44 UTC, merged