#2704 endpoint complete
Northeastern-Electric-Racing/FinishLine pull request #2752
Opened 2024-08-08 21:18 UTC by superhvarn

## Changes

- Added route, controller, and service
- Created tests
- Added new test util for creating FAQs

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #2704 )

2024-08-09 15:31 UTC, Aaryan1203 requested changes
left a couple comments but overall pertty good

2024-08-09 15:31 UTC, Aaryan1203 commented on src/backend/src/services/recruitment.services.ts
> +      throw new HttpException(404, `FAQ with id ${frequentlyAskedQuestionId} doesn't exist`);
throw a not found exception

2024-08-09 15:31 UTC, Aaryan1203 commented on src/backend/tests/test-utils.ts
> +  await prisma.frequentlyAskedQuestion.deleteMany({});
do you need the {} in this?

2024-08-09 15:31 UTC, Aaryan1203 commented on src/backend/tests/unmocked/recruitment.test.ts
> +    await createTestFAQ(orgId, 'faq123');
i owuld say to just add this line in the test you need it because otherwise were creating a test faq each time when sometimes we don't even need it

2024-08-09 15:31 UTC, Aaryan1203 commented on src/backend/src/services/recruitment.services.ts
> +
add a check for the organization not existing

2024-08-10 15:36 UTC, Aaryan1203 requested changes
looks pretty good almost done

2024-08-10 15:36 UTC, Aaryan1203 commented on src/backend/src/services/recruitment.services.ts
> +      throw new HttpException(401, `Organization with id ${organizationId} doesn't exist`);
why did you change this

2024-08-10 15:36 UTC, Aaryan1203 commented on src/backend/src/services/recruitment.services.ts
> +    if (!organizationId) {
Dont check if the organization id doesn't exist, first find the organization and check if that doesn't exist. look at how its done in other endpoints

2024-08-10 15:36 UTC, Aaryan1203 commented on src/backend/src/services/recruitment.services.ts
> +      throw new HttpException(400, `Organization with id ${organizationId} doesn't exist`);
use a not found exception

2024-08-11 19:28 UTC, Aaryan1203 requested changes
one more test and shoult be good

2024-08-11 19:28 UTC, Aaryan1203 commented on src/backend/tests/unmocked/recruitment.test.ts
> +    it('Fails if user is not an admin', async () => {
add a test for if the organization doesn't exist

2024-08-11 20:32 UTC, Aaryan1203 approved these changes
lgtm

2024-08-12 02:54 UTC, walker-sean approved these changes
LGTM

2024-08-12 02:55 UTC, merged