2700 recruitment getallfaqs endpoint
Northeastern-Electric-Racing/FinishLine pull request #2753
Opened 2024-08-10 19:06 UTC by superhvarn

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-08-11 05:43 UTC, Aaryan1203 requested changes
great job, couple small things and your good

2024-08-11 05:43 UTC, Aaryan1203 commented on src/backend/src/routes/recruitment.routes.ts
> +recruitmentRouter.get('/milestones', RecruitmentController.getAllMilestones);
Remove this, already there probably from a merge conflict

2024-08-11 05:43 UTC, Aaryan1203 commented on src/backend/src/services/recruitment.services.ts
> +    if (!organizationId) {
move this check above the allFaqs. and also don't do !organizationId. First find the organization and check if it exists like its done in other endpoints

2024-08-11 19:27 UTC, Aaryan1203 requested changes
one more small thing and should be good

2024-08-11 19:27 UTC, Aaryan1203 commented on src/backend/src/services/recruitment.services.ts
> +      where: { organizationId }
can you also add where date deleted is null so we don't get any deleted faqs

2024-08-11 20:32 UTC, Aaryan1203 approved these changes, later dismissed
lgtm

2024-08-12 03:03 UTC, walker-sean approved these changes, later dismissed
LGTM

2024-08-12 03:04 UTC, walker-sean reviewed
Merge conflicts then good 2 go

2024-08-14 18:52 UTC, merged