#2726 created getOrganizationImages endpoint
Northeastern-Electric-Racing/FinishLine pull request #2757
Opened 2024-08-20 18:42 UTC by AkulAggarwal2

## Changes

Created the getOrganizationImages endpoint to display the current organizations images on the frontend. 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2726

2024-08-21 00:17 UTC, superhvarn approved these changes, later dismissed
LGTM

2024-08-21 13:56 UTC, Aaryan1203 requested changes
Nice work, couple of small things right now

2024-08-21 13:56 UTC, Aaryan1203 commented on src/backend/src/services/organizations.services.ts
> +      exploreAsGuestImage: organization?.exploreAsGuestImageId
You shouldn't need the question mark here anymore

2024-08-21 13:56 UTC, Aaryan1203 commented on src/backend/src/services/organizations.service.ts
I think you may have accidentally added this file, you can delete it

2024-08-23 03:18 UTC, walker-sean approved these changes
LGTM

2024-08-23 03:18 UTC, merged