#2494: change tasklistnotesmodal to nerformmodal
Northeastern-Electric-Racing/FinishLine pull request #2759
Opened 2024-08-22 22:50 UTC by vsp05

## Changes

Changed the TaskListNotesModal (TaskModal.tsx) to an NERFormModal, rather than using mui dialog. Also changed the TaskFormModal from a mui dialog to an NERFormModal.

## Notes
There's a weird flickering problem due to the task list page re-rendering a lot. Peyton and Sean said not to worry too much about it. (See around 19 seconds into the video below if youre curious)
https://github.com/user-attachments/assets/8f045969-74f2-4d8d-b9b5-ae180a155eac

## Screenshots
New UI video walkthrough:
https://github.com/user-attachments/assets/9badf8a5-43ba-49bb-9161-aeade2740500

Old UI video walkthrough:
https://github.com/user-attachments/assets/3ebed208-c0e4-4dca-874a-c9c31f477d2b

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2494

2024-08-24 17:09 UTC, caiodasilva2005 reviewed
Since the NERModal is now being used I think it would be better if when creating a new task,  the title of the modal corresponds to the type of task you are created. For example, if I am creating a new task in "In Progress", the red bar at the top of the modal could say "New In Progress Task" or something like that. I just think it looks a little strange with just the red bar at the top and no title, but that is a matter of opinion. Other than that this looks good to me. @walker-sean , what are your thoughts?

2024-08-25 20:23 UTC, caiodasilva2005 requested changes

2024-08-25 20:23 UTC, caiodasilva2005 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/v2/TaskColumn.tsx
> +    status === 'IN_BACKLOG' ? 'New Backlog Task' : status === 'IN_PROGRESS' ? 'New In Progress Task' : 'New Done Task';
Instead of checking if status is equal to 'IN_BACKLOG', you should do status === TaskStatus.IN_BACKLOG, and do the same for the other statuses

2024-08-25 20:23 UTC, caiodasilva2005 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskFormModal.tsx
> +      title={title ? title : task?.title ?? ''}
I think using title ?? task?.title ?? '' would be more readable

2024-08-26 01:15 UTC, walker-sean reviewed
Nice job so far

Right now there's a bug where after you edit a task, the edit modal will open instead of the details modal. You could fix this by having the two usestates in the task list component so only one can be active at once

2024-08-26 01:15 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskFormModal.tsx
> +  title?: string;
Instead of this, just check if there are default values for the title - if there are default values, make the title 'Edit Task', otherwise 'New Task'

2024-08-26 01:15 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskFormModal.tsx
> +                      <MenuItem key={p} value={p}>
Pass these through an enum pipe for display so that the options don't show up as all caps

2024-08-26 01:15 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskFormModal.tsx
> +              <FormLabel>Deadline (YYYY-MM-DD)</FormLabel>
Make this MM-DD-YYYY

2024-08-26 01:15 UTC, walker-sean commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskModal.tsx
> +      <NERModal
Can you tighten up the spacing so its a small modal that displays the information more compactly? There's a lot of excess space right now

2024-09-03 02:15 UTC, walker-sean approved these changes
LGTM

2024-09-03 02:15 UTC, merged