#2712 pnm homepage
Northeastern-Electric-Racing/FinishLine pull request #2760
Opened 2024-08-23 19:16 UTC by Aaryan1203

## Changes

Created PNM home page

## Screenshots
![image](https://github.com/user-attachments/assets/be5b44fe-ff05-46b5-b3fa-a7e54aaa3dac)

## To Do

- [ ] Need to wait for organizationId ticket to be merged so I can access the organization from the pnm home page
- [ ] Remove the preferences tab on the settings page for a user on the pnm homepage

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2712

2024-09-01 16:08 UTC, Peyton-McKee requested changes
If i go to teams and then press home again, it brings me back to the original home screen, not the pnm one. Seems like that flow needs to be worked out a bit more. Maybe reach out to Naisha to iron out the flow between the different home screens.

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/hooks/organizations.hooks.ts
> + * @param organizationId organizationId to be fetched.
theres no param

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/components/NERTabs.tsx
> +const NERTabs = ({ setTab, tabsLabels, baseUrl, defaultTab, id, noUnderline = false }: TabProps) => {
rename this to like FullPageTabs or something

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/hooks/organizations.hooks.ts
> +export const useProvideOrganization = (): OrganizationProvider => {
if your putting this here now, delete the old file

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/layouts/Sidebar/Sidebar.tsx
> +          {!onPNMHomePage && <NavUserMenu open={drawerOpen} />}
you can make this a ternary

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/components/Tabs.tsx
> +  isFinance?: boolean;
i dont like the isFinance boolean that much, it instead should describe what the finance style is. Or make all the values that finance overrides their own props

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/PNMHomePage.tsx
> +  const { data: organization } = useCurrentOrganization();
this needs to be loading, error etc checked

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/PNMHomePage.tsx
> +              <Typography sx={{ mt: 4, fontSize: '1.2em' }}>{organization?.description}</Typography>
this will not need to be optional when you add the loading and error checks

2024-09-01 16:08 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/PNMHomePage.tsx
> +                <Tabs tabs={tabs} tabValue={tabValue} setTabValue={setTabValue} />
shouldnt the point of the tabs be you put in an object for what each tab corresponds to, so you dont need to do that individually in the component

2024-09-08 22:42 UTC, Peyton-McKee requested changes
This looks great, it was my mistake for trying to do this without just having them be routed to different url pages. This seems to be signifcantly more complicated than just switching them in the router

2024-09-08 22:42 UTC, Peyton-McKee commented on system-tests/cypress/e2e/pnm-page/pnm-home-page.cy.js
> +    cy.contains('Useful Links').should('be.visible');
add a selector for this.

2024-09-08 22:42 UTC, Peyton-McKee commented on system-tests/cypress/e2e/homepage/home-page.cy.js
> +    cy.contains('h3', 'About NER').should('be.visible');
This should be a selector.

2024-09-08 22:42 UTC, Peyton-McKee commented on system-tests/cypress/e2e/homepage/home-page.cy.js
> +    cy.contains('h3', 'About NER').should('be.visible');
I added an object for VISIBLE and whatnot that should be used

2024-09-08 22:42 UTC, Peyton-McKee commented on system-tests/cypress/e2e/homepage/home-page.cy.js
> +    cy.contains('Useful Links').should('be.visible');
UseFul Links should be a selector and be used in this file.

2024-09-08 22:42 UTC, Peyton-McKee commented on system-tests/cypress/e2e/homepage/home-page.cy.js
> +    cy.contains(FINISHLINE_BUTTON).click();
you should be checking that the sidebar still exists as well thats what the issue was

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/pages/TeamsPage/TeamSummary.tsx
> +        <Button variant="outlined" size="small" disabled={onPNMHomePage}>
just make it hidden, not disabled

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/components/Timeline.tsx
> +  return <Typography>Timeline Section</Typography>;
add a TODO statement with the ticket number for completing this

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/Home.tsx
> +  const { onGuestHomePage, setOnGuestHomePage, onPNMHomePage, setOnPNMHomePage } = useHomePageContext();
I feel like our lives would be significantly simplified if we made a different url for the guest home page and the pnm home page im ngl lol

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/FAQsList.tsx
> +  return <Typography>FAQ section</Typography>;
Add TODO with ticket number for this component

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx
> +      <Tabs tabValue={tabValue} setTabValue={setTabValue} tabs={tabs} greyscale />
this is so much better

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/FinanceComponents/ReimbursementRequestInfo.tsx
> +  const tabs = [{ label: 'My Requests', value: 0 }];
am i blind or is this not being used?

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/pages/FinancePage/FinanceComponents/ReimbursementRequestInfo.tsx
> +// import TableSortLabel from '@mui/material/TableSortLabel';
delete

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/layouts/Sidebar/SidebarButton.tsx
> +const SidebarButton = ({ onClick, label, icon }: SidebarButtonProps) => {
nice

2024-09-08 22:42 UTC, Peyton-McKee commented on src/frontend/src/app/HomePageContext.tsx
> +    JSON.parse(localStorage.getItem('onGuestHomePage') || 'true')
yeah i feel like if were doing this we might as well just put it in the url instead, make our lives significantly easier

2024-09-13 02:45 UTC, walker-sean approved these changes

2024-09-13 02:47 UTC, merged