#2829 stats page schema changes
Northeastern-Electric-Racing/FinishLine pull request #2841
Opened 2024-09-19 01:59 UTC by wavehassman

## Changes

Added new models to the schema for the graphs, graph collections (essentially containers), and the necessary enums

## Notes

had to add an id to model GraphData to create the relation, don't love it 

## Checklist

- [x] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [ ] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2829

2024-09-24 21:40 UTC, walker-sean requested changes

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +  organizationId String       @unique
This will make it so an organization will only have one collection

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +  organizationId        String           @unique
This will make it so an organization can only have one graph

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +  linkId                String           @id @default(uuid())
Is this the id for the graph?

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +  Graph  Graph[]
This indicates a one to many relation but the graph model shows a unique id for graphdata

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +enum Permission {
So I probably did a bad job of explaining permissions but permissions are more like "edit graph" and then permissions can belong to users or roles. These examples are really just pointing to roles themselves

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +enum Values {
These are more like measures

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +enum Data_Type {
Lets name this something less vague like `Graph_Data_Unit` or something, idk what a good one would be

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +  Graph                  Graph?                     @relation(fields: [graphLinkId], references: [linkId])
What is this for?

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +  Graph        Graph?         @relation(fields: [graphLinkId], references: [linkId])
Maybe I'm a bit confused about the purpose of this field, but shouldn't it be a many to many relation?

2024-09-24 21:40 UTC, walker-sean commented on src/backend/src/prisma/schema.prisma
> +  Graph                  Graph?                     @relation(fields: [graphLinkId], references: [linkId])
Same here

2024-09-30 16:24 UTC, martin0he commented on src/backend/src/prisma/schema.prisma
> +  Graph                  Graph?                     @relation(fields: [graphLinkId], references: [linkId])
its been removed now

2024-10-08 17:09 UTC, walker-sean approved these changes
Will probably need some changes down the line but this is a good to work with now

2024-10-08 17:09 UTC, merged