#2808: Added work package util function to get overdue WPs
Northeastern-Electric-Racing/FinishLine pull request #2842
Opened 2024-09-19 04:10 UTC by Jalen1

## Changes

- Added a function in work-package.utils.ts that takes in an array of work packages and returns an array of overdue work packages.

## Notes

- Function consists of a loop that pushes each work package is not complete and has a due date prior to current date to return array.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2808

2024-09-19 04:20 UTC, Aaryan1203 requested changes
Just a small comment but great start!

2024-09-19 04:20 UTC, Aaryan1203 commented on src/frontend/src/utils/work-package.utils.ts
> +
This works perfectly! I think a cleaner way to do this would be to do something like filter the list, it'll make the code a little easier to read

2024-09-19 04:28 UTC, Aaryan1203 approved these changes
Awesome great work! lgtm

2024-09-22 17:58 UTC, vsp05 approved these changes
LGTM! @walker-sean could you take a look when you get a chance? Should we write tests for this?

2024-09-23 17:34 UTC, merged