#2806 created getUpcomingWorkPackages util
Northeastern-Electric-Racing/FinishLine pull request #2843
Opened 2024-09-19 05:10 UTC by Jalen1

## Changes

Added a function in work-package utils that, when given an array of work packages, returns upcoming work packages (start date within 2 weeks).

## Notes
- Used a filter that kept work packages whose startDate value was between the current date and 2 weeks after the current date, inclusive.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [ ] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2806

2024-09-22 17:54 UTC, vsp05 approved these changes, later dismissed
Looks good to me! @walker-sean should we write tests for this or is it fine?

2024-09-23 17:46 UTC, walker-sean requested changes

2024-09-23 17:46 UTC, walker-sean commented on src/frontend/src/utils/work-package.utils.ts
> +  return workPackages.filter(({ startDate }) => currentTime <= startDate && startDate <= twoWeeks);
Just make it so that work packages with a start date of the current date are filtered out

2024-10-21 23:23 UTC, vsp05 approved these changes

2024-10-22 01:18 UTC, walker-sean approved these changes

2024-10-22 01:18 UTC, merged