#2849 added set description endpoint for organizations
Northeastern-Electric-Racing/FinishLine pull request #2850
Opened 2024-09-25 02:13 UTC by chpy04

## Changes

Added a set description endpoint to organizations in the path 'organizations/description/set' that takes in a string and updates the description of the user's organization. Requires the user to be an admin. Returns the new organization.

## Test Cases

- The user is not an admin --> fails
- The user is an admin and the description gets updated

## Screenshots

<img width="1144" alt="SetDescriptionPostman" src="https://github.com/user-attachments/assets/8fd73d86-0ff6-44d1-9244-abdd37742786">

Closes #2849

2024-09-25 02:32 UTC, caiodasilva2005 approved these changes, later dismissed
LGTM

2024-09-25 14:48 UTC, walker-sean requested changes

2024-09-25 14:48 UTC, walker-sean commented on src/backend/src/services/organizations.services.ts
> +   *
This needs a purpose statement + descriptions of params

2024-10-01 23:00 UTC, walker-sean approved these changes

2024-10-01 23:00 UTC, merged