#1586 reimbursement date delivered input
Northeastern-Electric-Racing/FinishLine pull request #2853
Opened 2024-09-25 12:56 UTC by jonathan-chen10

## Changes

Add Calendar Selector to Date Delivered modal so people can select date delivered so it's not always today

## Notes

Changed confirm button from useless checkbox to validated Yes/No (No by default, you have to manually move it to yes)

Calendar has filters in FE and BE so (dateOfExpense <= dateDelivered <= today). Some timezone shenanigans but I think it works

## Test Cases

See screenshots

- Click "No, not delivered" 
- Edge cases for calendar validation (not in screenshots)
- The Working Case: Delivery date added as expected

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_
![Screenshot 2024-09-25 at 8 26 23 AM](https://github.com/user-attachments/assets/3e184d52-5a31-4788-b113-fde125a0f133)
![Screenshot 2024-09-25 at 8 26 33 AM](https://github.com/user-attachments/assets/14876eff-68be-4f3c-a6b2-4973d485f039)

Refuse to submit if you don't confirm
![Screenshot 2024-09-25 at 8 26 55 AM](https://github.com/user-attachments/assets/35c57277-df9f-4be7-b3f5-14365f9c28be)

![Screenshot 2024-09-25 at 8 27 16 AM](https://github.com/user-attachments/assets/ba0c5e81-e826-4e96-ab4e-1d278daea4a4)
Calendar disabled in FE

Date is updated!
![Screenshot 2024-09-25 at 8 43 10 AM](https://github.com/user-attachments/assets/bc590f8b-91e7-4652-8c3b-08fd6a3d8c7d)

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

Too Early
![Screenshot 2024-09-25 at 8 41 15 AM](https://github.com/user-attachments/assets/3c38c4bd-dbe5-4fa9-bda8-81f6fa6151b6)

Too Late
![Screenshot 2024-09-25 at 8 42 31 AM](https://github.com/user-attachments/assets/a8a5669b-6611-4fb0-9652-3404d89991f0)

Just Right
![Screenshot 2024-09-25 at 8 42 52 AM](https://github.com/user-attachments/assets/5f47cc3f-e611-417f-ba99-a5b908e462ce)

![Screenshot 2024-09-25 at 8 30 12 AM](https://github.com/user-attachments/assets/74242dbc-3515-4dce-90f9-c5c6ec4d14a7)
![Screenshot 2024-09-25 at 8 43 25 AM](https://github.com/user-attachments/assets/f5421db2-f3c1-412a-8a92-00c10f77a73c)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [ ] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1586

2024-09-28 18:30 UTC, vsp05 requested changes
Overall, great work! I just pointed out one minor change that should be pretty easy to fix - it'll just clean up the code a bit. Otherwise, LGTM!

2024-09-28 18:30 UTC, vsp05 commented on src/backend/src/services/reimbursement-requests.services.ts
> +    const startOfDay = (date: Date): Date => {
Maybe move this function to utils so that you can call startOfDay in other files (for example, you use this logic a lot in MarkDeliveredModal.tsx)

2024-09-28 18:30 UTC, vsp05 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/MarkDeliveredModal.tsx
> +    return date < new Date(new Date(reimbursementRequest.dateOfExpense).setHours(0, 0, 0, 0));
like here ^

2024-09-28 18:30 UTC, vsp05 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/MarkDeliveredModal.tsx
> +    const now = new Date(new Date().setHours(0, 0, 0, 0));
and here ^

2024-09-28 18:30 UTC, vsp05 commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/MarkDeliveredModal.tsx
> +      await markDelivered({ dateDelivered: new Date(data.dateDelivered.setHours(0, 0, 0, 0)) });
and here ^

2024-10-09 00:56 UTC, alaneng-neu submitted a review, later dismissed
LGTM

2024-10-11 03:01 UTC, vsp05 approved these changes, later dismissed
LGTM! Great work!

2024-10-21 00:15 UTC, alaneng-neu approved these changes, later dismissed

2024-10-21 23:16 UTC, vsp05 submitted a review, later dismissed

2024-10-27 03:57 UTC, walker-sean requested changes

2024-10-27 03:57 UTC, walker-sean commented on src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/MarkDeliveredModal.tsx
> +  const dateIsBeforeExpenseCreated = (date: Date): boolean => {
Could you rename this to `dateIsBeforeExpense` - we want to make sure we're clear this isn't when the expense was reported

2024-11-03 17:48 UTC, Peyton-McKee approved these changes

2024-11-14 19:56 UTC, walker-sean approved these changes

2024-11-14 19:57 UTC, merged