2725 recruitment admin tool to update organizations images
Northeastern-Electric-Racing/FinishLine pull request #2860
Opened 2024-09-30 15:51 UTC by superhvarn

## Changes

- Added two upload buttons in the admin tools
- Download and display capabilities
- hook for setting images
- 

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-10-19 15:49 UTC, Aaryan1203 requested changes
Right now when I upload, the loading indicator comes up for both buttons. Also, you can use my NERUplaodButton because with that it gives u a submit and cancel button which would be useful for this as well because right now the user doesn't have any option to not upload the picture when it comes up.

Can you make the two buttons side by side instead of one on top of the other

I get this when I upload smth rn:
<img width="1683" alt="image" src="https://github.com/user-attachments/assets/f7433db5-e63a-4a79-a1cd-655a26bd4b5f">

2024-12-17 17:36 UTC, Aaryan1203 requested changes

2024-12-17 17:36 UTC, Aaryan1203 commented on src/frontend/src/pages/HomePage/GuestHomePage.tsx
> +            imageSrc={`https://drive.google.com/thumbnail?id=${organization?.applyInterestImageId}&sz=w1000`}
use the useGetimageUrl hook. take a look at how I did it in the team type section

2024-12-18 15:53 UTC, Aaryan1203 requested changes
Can you put the two upload buttons next to eachother instead of one on top of the other.

Also, when you upload an image, there should be a loading indicator before it pops up.

When i upload an image right now, I don't see it unless I refresh the page.

2024-12-18 15:53 UTC, Aaryan1203 commented on src/backend/src/services/organizations.services.ts
There is an endpoint in this file called getOrganizationImages which is not beiung used. Can you delete that from the routes controller and service

2024-12-21 18:09 UTC, Peyton-McKee requested changes
should be done after these changes

2024-12-21 18:09 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/RecruitmentConfig/AdminToolsRecruitmentConfig.tsx
> +  const { mutateAsync: organizationImages } = useSetOrganizationImages();
add isLoading check here

2024-12-21 18:09 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/RecruitmentConfig/AdminToolsRecruitmentConfig.tsx
> +  const { data: organization } = useCurrentOrganization();
add isLoading, isError and error to all of these and associated checks

2024-12-21 18:09 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/GuestHomePage.tsx
> +  if (applyImageError) return <ErrorPage message="Error loading apply interest image" />;
include the individual error messages here as well

2024-12-21 18:09 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/GuestHomePage.tsx
> +  if (!applyInterestImageUrl || !exploreGuestImageUrl) throw new Error('Image URLs are undefined');
woah were not throwing errors in componenets, we should be returning the loading indivator

2024-12-21 18:09 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/GuestHomePage.tsx
> +  if (!organization || isLoading || applyImageLoading || exploreImageLoading) return <LoadingIndicator />;
return loading indicator after errors

2024-12-24 00:49 UTC, merged