#2803 Unreviewd Change Requests
Northeastern-Electric-Racing/FinishLine pull request #2873
Opened 2024-10-09 00:59 UTC by chpy04

## Changes

- Added a component that displays any change requests that currently requires a user's review.
- refactored duplicate code for producing change requests into change request utils file

## Notes

Had to override overflow in the`ChangeRequestRow` component to make it scroll. Also, change request cards are somewhat difficult to see but I couldn't change the color while also using the `ChangeRequestRow`, so lmk if I should just display them myself. 

## Screenshots

<img width="1452" alt="CRsScroll" src="https://github.com/user-attachments/assets/de764777-476d-4299-b873-881be455b9c7">
<img width="1447" alt="CRsEmpty" src="https://github.com/user-attachments/assets/df1907e0-f647-42f9-9e57-0abb5ed0be3b">

Closes #2803

2024-10-13 18:56 UTC, caiodasilva2005 requested changes
Really nice work! Just one small thing

2024-10-13 18:56 UTC, caiodasilva2005 commented on src/frontend/src/components/ChangeRequestRow.tsx
> +  flexWrap?: string;
Change this to a boolean and have it be wrap if true and nowrap if false. Just make sure to update the change request row props in the change request overview page with this approach

2024-10-27 23:55 UTC, caiodasilva2005 requested changes
Changes requested in slack

2024-11-29 03:14 UTC, walker-sean requested changes
The  "Unreviewed Change Requests" section on the CR page shows the CRs the user has *made* and is waiting for review on. I think that's what we're looking for here too. If not, we should change the title to match what's on the CR page

2024-11-29 14:00 UTC, chpy04 commented
> The "Unreviewed Change Requests" section on the CR page shows the CRs the user has _made_ and is waiting for review on. I think that's what we're looking for here too. If not, we should change the title to match what's on the CR page

I was interpreting it as admins will be able to see the change requests that they need to review, but @caiodasilva2005 should confirm that

2024-11-29 16:55 UTC, caiodasilva2005 commented
@walker-sean yeah I was thinking the same as what Chris mentioned because it would prob be a useful tool for admins to keep track of the change requests they need to review. In this case, yeah I believe the title should be changes to "Change Requests to Review" or something like that. This way, this component will have different functionality than the on the CRs page

2024-12-06 16:04 UTC, merged