#2775: Recommitting and updating dependencies
Northeastern-Electric-Racing/FinishLine pull request #2924
Opened 2024-11-04 23:34 UTC by gcooper407

## Changes

Created a Bar Chart component to be used on the Statistics page
Created a (temporary) sample bar chart on the stats page with sample data to showcase the components
Updated dependencies (package.json) to properly support the new components 

## Screenshots

<img width="1437" alt="Screenshot 2024-10-15 at 8 52 48 PM" src="https://github.com/user-attachments/assets/6bda6c61-c323-4f69-93bb-0707a791f6a9">

<img width="639" alt="Screenshot 2024-10-15 at 8 53 29 PM" src="https://github.com/user-attachments/assets/18143410-1f62-4a7f-b733-30e60a43cff6">

<img width="656" alt="Screenshot 2024-10-15 at 9 08 00 PM" src="https://github.com/user-attachments/assets/e389fff5-dd2a-4baf-a22b-fd2e7cb12783">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [ ] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2775

2024-11-06 20:08 UTC, wavehassman commented
LGTM

2024-11-20 18:46 UTC, walker-sean requested changes
This looks really cool!!

2024-11-20 18:46 UTC, walker-sean commented on src/frontend/src/components/StatsBarChart.tsx
> +    <div style={{ width: '100%', height: '100%', maxWidth: width, maxHeight: height }}>
Could you switch this over to a Box?

2024-11-29 03:39 UTC, walker-sean approved these changes
LGTM

2024-11-29 03:39 UTC, merged