#2949 Added my name to credits
Northeastern-Electric-Racing/FinishLine pull request #2976
Opened 2024-11-13 02:11 UTC by elbow74

## Changes

added my name to the credits page

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_
<img width="1438" alt="Screenshot 2024-11-12 at 9 10 48 PM" src="https://github.com/user-attachments/assets/0d2db833-246d-4fee-9a13-b6196c942cae">

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-11-13 05:55 UTC, alaneng-neu requested changes
Make sure you are using prettier to format your files! I think you should already have prettier downloaded from Launchpad, but make sure your "Format on save" setting in VS Code is checked on. If you don't have it downloaded, you can find it [here](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). Additionally, make sure you are filling in the last line of the PR, i.e. "Closes #2949"

2024-11-20 01:44 UTC, vsp05 approved these changes

2024-11-20 01:51 UTC, alaneng-neu approved these changes

2024-11-20 18:55 UTC, walker-sean approved these changes
Looks great! In the future, please remember to remove unneeded parts of the template

2024-11-20 18:55 UTC, merged