#2698 Allow custom zoom links in user schedule settings
Northeastern-Electric-Racing/FinishLine pull request #3029
Opened 2024-11-21 01:42 UTC by Yaomister

## Changes

Changed the UserScheduleSettingsEdit.tsx file to allow the user to save custom Zoom links (that contain the snippit "zoom.us/" in the url) instead of just Zoom links that start with https://zoom.us/.

## Screenshots

<img width="1106" alt="Screenshot 2024-11-20 at 11 44 24 AM" src="https://github.com/user-attachments/assets/94995d56-a8b4-4614-906c-31acf78adf3c">

<img width="1721" alt="Screenshot 2024-11-20 at 11 44 39 AM" src="https://github.com/user-attachments/assets/e4fefc65-0bd4-4d67-9373-36c84a885b2f">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [] No merge conflicts
- [] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2698

2024-11-21 01:55 UTC, vsp05 requested changes
The error message isn't necessarily the right description. For example, if you input zoom.us/hello, the error will say 'must contain zoom.us/', even though the real issue is that the link doesn't start with https

2024-11-21 01:59 UTC, vsp05 commented
also I think there should be a /j/ after the zoom.us (see how it was written in the previous code). Basically, i think the validation should check for ...link.includes('zoom.us/j/')

2024-11-21 16:08 UTC, Yaomister commented
I didn't include the check for "/j/" in the link cause in the original issue, zach had a screenshot of him saving a link without the "/j/" and it said it was an acceptable link, but lmk if I should still change it.

2024-11-21 18:33 UTC, vsp05 commented
> I didn't include the check for "/j/" in the link cause in the original issue, zach had a screenshot of him saving a link without the "/j/" and it said it was an acceptable link, but lmk if I should still change it.

good catch. I think for now, include the /j/ in there, just because thats how it was in the codebase before.

2024-11-21 22:16 UTC, vsp05 submitted a review, later dismissed
lgtm! great work!

2024-11-24 21:58 UTC, alaneng-neu requested changes
Just a little grammatical error to fix!

2024-11-24 21:58 UTC, alaneng-neu commented on src/frontend/src/pages/SettingsPage/UserScheduleSettings/UserScheduleSettingsEdit.tsx
> +        toast.error('Invalid Zoom Link Format. Link must contains "zoom.us/j/".');
The string should be `...Link must contain...` instead of `contains`

2024-11-24 23:37 UTC, alaneng-neu approved these changes
LGTM

2024-11-25 19:17 UTC, vsp05 approved these changes
LGTM!

2024-11-25 20:59 UTC, walker-sean approved these changes

2024-11-25 20:59 UTC, merged