#2997-Send Notifications
Northeastern-Electric-Racing/FinishLine pull request #3035
Opened 2024-11-22 15:45 UTC by caiodasilva2005

## Changes

Created an endpoint to send notifications to a user based on user id

## Test Cases

- Fails on invalid user id
- Succeeds and sends notifcation to user

## Screenshots

![Screenshot 2024-11-18 155125](https://github.com/user-attachments/assets/d46fe23f-f9db-4f86-a6d2-17a30fb3a9be)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #2997

2024-11-25 20:37 UTC, walker-sean requested changes

2024-11-25 20:37 UTC, walker-sean commented on src/backend/src/services/users.services.ts
> +    const udaptedUser = await prisma.user.update({
spelling

2024-11-25 20:37 UTC, walker-sean commented on src/backend/src/services/users.services.ts
> +    const createdNotification = await prisma.notification.create({
This isn't quite what we want, right? This will make a new notification in the database for every user it is sent to. We want to have one notification which is connected to many users

2024-11-25 20:49 UTC, chpy04 commented on src/backend/src/services/users.services.ts
> +    const createdNotification = await prisma.notification.create({
I think the idea is that we need to keep track of which notifications have been seen by users, so a notification would be pushed to all the users that need to see it, and then as users see the notification it is removed from their unreadNotifications.

2024-11-26 21:54 UTC, caiodasilva2005 commented on src/backend/src/services/users.services.ts
> +    const createdNotification = await prisma.notification.create({
@walker-sean yeah that is a mistake, I will fix this

2024-12-11 00:58 UTC, Peyton-McKee requested changes
Where are these functions being used? Are we exposing these functions to an endpoint? if so there should be routes controllers and services for that instead of just utils.

2024-12-11 00:58 UTC, Peyton-McKee commented on src/backend/src/prisma/migrations/20241122155216_updated_notifications/migration.sql
> +/*
did you make the original notification sql file? if so consolidate the two into one please

2024-12-11 00:58 UTC, Peyton-McKee commented on src/backend/src/utils/homepage-notifications.utils.ts
> +const sendNotificationToUser = async (userId: string, notificationId: string, organizationId: string) => {
javadoc

2024-12-11 00:58 UTC, Peyton-McKee commented on src/backend/src/utils/homepage-notifications.utils.ts
> +
why are we checking that user exists but not the other things, not sure if we need to check any of these and mark in the documentation that verification of these items should exist already. Or we do all of the verification in here.

2024-12-11 00:58 UTC, Peyton-McKee commented on src/backend/src/utils/homepage-notifications.utils.ts
> +  return notificationTransformer(createdNotification);
transforming should not be happening in utils, this should be in the service function

2024-12-11 19:44 UTC, Peyton-McKee requested changes

2024-12-11 19:44 UTC, Peyton-McKee commented on src/backend/src/prisma/schema.prisma
>    createdAnnouncements            Announcement[]            @relation(name: "CreatedAnnouncements")
I dont know why everyone is capitalizing the relation names. All relation names should be camelcase

2024-12-11 19:44 UTC, Peyton-McKee commented on src/backend/src/routes/users.routes.ts
> +userRouter.post(
Dont we have a notifications router already? I feel like this should be under that

2024-12-11 22:56 UTC, Peyton-McKee approved these changes

2024-12-11 22:58 UTC, merged