#2637 Update Testing Color
Northeastern-Electric-Racing/FinishLine pull request #3042
Opened 2024-11-25 15:49 UTC by justalittlemushroom

## Changes
Updated Testing Color from Yellow to Light Blue for Better Contrast

## Screenshots
<img width="1512" alt="Screenshot 2024-11-25 at 10 41 12" src="https://github.com/user-attachments/assets/e8a0d2ec-2ec4-4a2e-afa3-2aaab8b4ca33">
<img width="84" alt="Screenshot 2024-11-25 at 10 43 32" src="https://github.com/user-attachments/assets/fb4ab632-9531-4a46-b4e6-f61ba3ddb1a1">

## Checklist
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2024-11-25 18:57 UTC, vsp05 commented on src/frontend/src/utils/gantt.utils.ts
>  export const GanttWorkPackageTextColorPipe: (stage: WorkPackageStage | undefined) => string = (stage) => {
since the color is white in all cases now, you can just remove this entire colorpipe, and have it just be '#ffffff' wherever this pipe is called

2024-11-25 18:57 UTC, vsp05 requested changes
great work! just a small comment about unneeded code

2024-11-25 19:00 UTC, vsp05 requested changes

2024-11-25 19:00 UTC, vsp05 commented on src/frontend/src/utils/gantt.utils.ts
> +import { deepOrange, green, grey, indigo, lightBlue, orange, pink } from '@mui/material/colors';
can you keep it as yellow instead of lightBlue (just darker hues of yellow)

2024-11-27 04:10 UTC, vsp05 submitted a review, later dismissed
Great work!

2024-11-27 06:34 UTC, alaneng-neu requested changes

2024-11-27 06:34 UTC, alaneng-neu commented on src/frontend/src/utils/gantt.utils.ts
> -export const GanttWorkPackageTextColorPipe: (stage: WorkPackageStage | undefined) => string = (stage) => {
I would actually just make this a constant like `export const GanttWorkPackageTextColor: string = '#ffffff'`, and then replace the usage of the pipe with this new constant instead. This way if we ever need to change the text color, we only need to change it in one place

2024-12-05 00:19 UTC, alaneng-neu approved these changes
LGTM

2024-12-06 04:17 UTC, vsp05 approved these changes
LGTM!

2024-12-11 22:58 UTC, walker-sean approved these changes

2024-12-11 22:58 UTC, merged