#2595: Added a faint border around the current day to the design review calendar
Northeastern-Electric-Racing/FinishLine pull request #3043
Opened 2024-11-25 17:57 UTC by morrill-tw

## Changes

Added a faint gray border around the current day to the design review calendar.

## Screenshots

![Screenshot 2024-11-25 124941](https://github.com/user-attachments/assets/cac37db1-fcd5-40e2-907d-503237322eef)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # 2595

2024-11-25 19:06 UTC, vsp05 commented
Great work! Could you remove your changes on ```yarn.lock```? Once you do that I'll approve!

2024-11-25 19:13 UTC, vsp05 commented
oh, also don't add a space in between # and 2595. If you remove the space, it will link this pr with the issue, which is what we want

2024-11-25 21:02 UTC, alaneng-neu requested changes

2024-11-25 21:02 UTC, alaneng-neu commented on yarn.lock
> +  version: 1.0.30001680
You shouldn't have any `yarn.lock` changes, because dependencies didn't change

2024-11-27 04:12 UTC, vsp05 approved these changes
Great Work!

2024-11-27 04:34 UTC, alaneng-neu approved these changes
LGTM

2024-12-11 23:00 UTC, walker-sean approved these changes

2024-12-11 23:00 UTC, merged