#186 - WPP CheckList
Northeastern-Electric-Racing/FinishLine pull request #305
Opened 2022-10-06 22:03 UTC by Ari-S-123

## Changes

Added CheckList Component and implemented it in Work Package Expected Activities and Deliverables.

## Screenshots

![Screenshot 2022-10-06 173328](https://user-images.githubusercontent.com/80832201/194426664-b26006c0-58db-4237-8d98-44d08dc81e47.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #186

2022-10-07 00:18 UTC, RChandler234 commented on src/frontend/src/components/CheckList.tsx
> +  const handleCheck = (idx: number) => {
can you add a line break here between line 23/24 for readability

2022-10-07 21:29 UTC, RChandler234 approved these changes

2022-10-08 04:11 UTC, anthonybernardi requested changes
epic

2022-10-08 04:11 UTC, anthonybernardi commented on src/frontend/src/components/CheckList.tsx
> +    const updatedChecks = checks.map((check, i) => {
`const check = checks[idx]; check.resolved = !check.resolved;`

2022-10-08 04:11 UTC, anthonybernardi commented on src/frontend/src/components/CheckList.tsx
> + * This file is part of NER's PM Dashboard and licensed under GNU AGPLv3.
is part of FinishLine by NER

2022-10-08 04:11 UTC, anthonybernardi commented on src/frontend/src/components/CheckList.tsx
> +              defaultChecked={check.resolved}
`checked={check.resolved}` otherwise you run into issues (this happened to me with risk log lol)

2022-10-08 04:11 UTC, anthonybernardi commented on src/frontend/src/tests/components/CheckList.test.tsx
> +jest.mock('../../hooks/Theme.hooks');
see my frontend testing pr for how to do this in a one liner in teh beforeEach

2022-10-08 14:50 UTC, anthonybernardi requested changes

2022-10-08 14:50 UTC, anthonybernardi commented on src/frontend/src/components/CheckList.tsx
> +    const updatedChecks = checks.map((check, i) => {
ok so what i meant in my previous review was that you don't need the map at all but i forgot we shouldn't mutate the list without setting it. technically this way still mutates the old list but it's fine becuase we set it right after i think.

so i think a better way to do this entire map thing (we'll see if we get errors lol) is:
`const updatedChecks = [...checks]; updatedChecks[idx].resolved = !updatedChecks[idx].resolved; setChecks(updatedChecks);`

2022-10-08 18:51 UTC, anthonybernardi approved these changes
awesome!

2022-10-08 18:51 UTC, merged