#2817 upcoming design reviews
Northeastern-Electric-Racing/FinishLine pull request #3058
Opened 2024-12-08 19:53 UTC by jessegarcia1

## Changes

Created the card and display for the upcoming design reviews for leads.

## Screenshots

![image](https://github.com/user-attachments/assets/680f0ce4-7482-4fe1-91c5-ae558e2e2eb1)
![image](https://github.com/user-attachments/assets/edef4eeb-3c63-4eec-b6e7-4d9fd01e4190)

Closes #2817

2024-12-11 23:15 UTC, walker-sean requested changes
Alright it looks great but two things I noticed:
1. When there are too many design reviews everything gets too smushed. Talk to @caiodasilva2005 about using the component with the scrollbar
2. You should also include the person that scheduled the design review, as they may not think to add themself as a required member.

2024-12-12 01:02 UTC, caiodasilva2005 requested changes
If a design review is scheduled for Thursday 12/12 for example, it is showing Wednesday 12/11 on the design review card in the component, meaning every card is showing the design review as one day before it is scheduled. Try potentially modifying the get Weekday and get removeYear functions to account for having to add 1 to the day, and make sure to test edge cases like scheduling a review on Sunday

2024-12-16 20:41 UTC, walker-sean requested changes

2024-12-16 20:41 UTC, walker-sean commented on src/frontend/src/pages/HomePage/components/DesignReviewCard.tsx
> +  console.log('CONFIRMED:', confirmedMemberIds);
Remove

2024-12-16 20:41 UTC, walker-sean commented on src/frontend/src/pages/HomePage/components/DesignReviewCard.tsx
> +function getWeekday(date: Date): string {
Could you change these to const functions

2024-12-19 23:28 UTC, walker-sean approved these changes
LGTM

2024-12-19 23:28 UTC, merged