#3074-Get Unread Announcements
Northeastern-Electric-Racing/FinishLine pull request #3076
Opened 2024-12-19 13:27 UTC by caiodasilva2005

## Changes

- Created endpoint for getting unread announcements
- Updated schema to reflect data needed from slack events

## Notes

- the createAnnouncements service function is called when we receive a message in a slack thread

## Screenshots

![image](https://github.com/user-attachments/assets/fd61482d-4f75-4bcc-b514-45046fcfeb61)

## To Do

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [X] All commits are tagged with the ticket number
- [X] No linting errors / newline at end of file warnings
- [X] All code follows repository-configured prettier formatting
- [X] No merge conflicts
- [X] All checks passing
- [X] Screenshots of UI changes (see Screenshots section)
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [X]  Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #3074

2024-12-20 05:44 UTC, Peyton-McKee requested changes

2024-12-20 05:44 UTC, Peyton-McKee commented on src/backend/src/routes/users.routes.ts
> +userRouter.get('/:userId/announcements', UsersController.getUserUnreadAnnouncements);
i dont think we should be passing in userId to any of these routes. I could be confused. Message me on slack what userId actually represents here

2024-12-20 05:44 UTC, Peyton-McKee commented on src/backend/src/services/users.services.ts
> +   * @param userId id of user to get unread announcements from
shouldnt we only ever get the current users announcements?

2024-12-20 05:44 UTC, Peyton-McKee commented on src/backend/src/services/users.services.ts
> +    if (!requestedUser) throw new NotFoundException('User', userId);
if were gonna do it like this we need to add a check that the user is in this organization

2024-12-20 05:44 UTC, Peyton-McKee commented on src/backend/src/services/announcement.service.ts
> +  static async createAnnouncement(
where is this being called?

2024-12-20 05:44 UTC, Peyton-McKee commented on src/backend/src/services/announcement.service.ts
> +    dateCreated: Date,
dateCreated is being passed in here?

2024-12-20 22:30 UTC, walker-sean submitted a review, later dismissed

2024-12-20 22:30 UTC, walker-sean commented on src/backend/src/routes/users.routes.ts
> +userRouter.get('/notifications/current-user', UsersController.getUserUnreadNotifications);
I think it would make more sense to create new routers rather than going this deep
something like `notificationRouter.get('current-user')`

2024-12-20 22:30 UTC, walker-sean commented on src/backend/src/transformers/announcements.transformer.ts
> +  return {
Use the spread operator to simplify this

2024-12-22 04:35 UTC, Peyton-McKee submitted a review, later dismissed
you can merge after making this change, dont forget to update frontend

2024-12-22 04:35 UTC, Peyton-McKee commented on src/backend/src/routes/notifications.routes.ts
> +  nonEmptyString(body('notificationId')),
i think it makes more sense to have it be /:notificationId/remove

2024-12-24 00:52 UTC, Peyton-McKee approved these changes

2024-12-24 00:52 UTC, merged