#2811 setup onboarding progress bar
Northeastern-Electric-Racing/FinishLine pull request #3084
Opened 2024-12-20 00:08 UTC by superhvarn

## Changes

- progress bar for checklists
- overall progress
- finish button

## Screenshots

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #2811)

2024-12-20 02:21 UTC, Aaryan1203 requested changes
Can you make the progress bar look a little more like the mocks and also for the checklists, i think the progress bar should be next to the text

2024-12-20 22:42 UTC, walker-sean requested changes

2024-12-20 22:42 UTC, walker-sean commented on src/frontend/src/components/OnboardingProgressBar.tsx
> +interface ProgressBarWithValueProps {
Please rename to `OnboardingProgressBarProps`

2024-12-21 18:13 UTC, Peyton-McKee reviewed
You can merge if these comments dont uncover anything

2024-12-21 18:13 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/OnboardingHomePage.tsx
> +        <NERButton variant="contained">Finished?</NERButton>
this button doesnt do anything?

2024-12-21 18:13 UTC, Peyton-McKee commented on src/frontend/src/pages/HomePage/components/Checklist.tsx
> +          <Grid container justifyContent="space-between" alignItems="center">
whats going on with all these grids. Are these really all necessary

2024-12-21 22:41 UTC, merged