#2816 confirm onboarding checklist modal
Northeastern-Electric-Racing/FinishLine pull request #3090
Opened 2024-12-21 00:40 UTC by superhvarn

## Changes

- modal complete
- user is promoted when user confirms

## Screenshots
<img width="641" alt="Screenshot 2024-12-20 at 7 40 20 PM" src="https://github.com/user-attachments/assets/dbe1455b-0974-42ca-b9e1-f632933082c4" />

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #2816 )

2024-12-21 03:10 UTC, Aaryan1203 requested changes
Can you make it so when you click the finished button on the onboarding home page then this shows up. Also can the modal be more rounded like the other ones

2025-01-02 19:54 UTC, Aaryan1203 requested changes

2025-01-02 19:54 UTC, Aaryan1203 commented on src/backend/src/prisma/schema.prisma
> +  completedOnboarding Boolean               @default(false)
it should default to true, we will call the endpoint to make it false once when they are on the onboarding page and then once again when they click finish

2025-01-02 19:54 UTC, Aaryan1203 commented on src/frontend/src/pages/HomePage/OnboardingHomePage.tsx
> +  const user = useCurrentUser();
you shouldn't ever need to call useCurrentUser

2025-01-02 19:54 UTC, Aaryan1203 commented on src/frontend/src/pages/HomePage/OnboardingHomePage.tsx
> +    await toggleCompletedOnboarding.mutateAsync({ userId: user.userId });
the endpoint should use req.currentUser

2025-01-02 19:54 UTC, Aaryan1203 commented on src/frontend/src/utils/urls.ts
> +const userSecureSettings = (id: string) => `${usersById(id)}/secure-psettings`;
was adding the 'p' an accident

2025-01-02 19:54 UTC, Aaryan1203 commented on src/shared/src/types/user-types.ts
> +
shouldn't need this

2025-01-02 19:54 UTC, Aaryan1203 commented on src/backend/src/services/users.services.ts
> +
I am assuming there is somewhere that this is being done right now like when a user goes from becoming a guest to a member, is this the same code as it is there? If not do uk where we can find that because i think we might not need this part and can probably just call whatever it uses right now

2025-01-03 18:26 UTC, Peyton-McKee approved these changes

2025-01-03 18:27 UTC, merged