#3013 started create checklist modal
Northeastern-Electric-Racing/FinishLine pull request #3092
Opened 2024-12-21 22:34 UTC by Aaryan1203

## Changes

Started the create checklist modal. have this up as a checkpoint

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] Get modal to actually work

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #3013 and #3014

2024-12-25 05:13 UTC, walker-sean requested changes
Ok, great start - The first things that stand out to me:
1. The modal is (in my opinion) a bit confusing. The idea of having multiple descriptions is probably pretty unintuitive, and I think people would interpret an array field of descriptions to mean that they will apply to subtasks
2. Adding to that point, we probably want to push people toward writing one description. An idea could be having a description text box, and then giving an option to "Add Additional Information" which can look like the bullet field we have now
3. Only one description appears when subtasks are added (not in the modal, but the display - should probably be fixed in another ticket)
4. I dont think there is really an error in approach with edit. Inspecting the network activity, it looks like the default values aren't actually being sent to the endpoint.
5. We need to validate subtasks being empty

2025-01-06 16:42 UTC, Peyton-McKee reviewed
This looks really good. One thing im confused on is whats the purpose of these little menu buttons. I would assume youd be able to drag it to reorder the bullets but rn they do nothing. 
<img width="206" alt="Screenshot 2025-01-06 at 11 42 17 AM" src="https://github.com/user-attachments/assets/401f752e-73b7-43b9-8726-a0cb8744c5e6" />

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/CreateChecklistModal.tsx
> +  const schema = yup.object().shape({
move schema above the component

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/CreateChecklistModal.tsx
> +  const handleFormSubmit = async (data: ChecklistCreateArgs) => {
i dont think we need this

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/CreateChecklistModal.tsx
> +      const parentChecklist = await handleFormSubmit(formattedData);
just use createChecklist here

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/CreateChecklistModal.tsx
> +        descriptions: (data.descriptions as unknown as { name: string }[]).map((desc) => desc.name)
this is weird. something is wrong if you have to do this

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/CreateChecklistModal.tsx
> +    defaultValues: {
define default values object outside of this

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/CreateChecklistModal.tsx
> +    setSubtasks([...subtasks, { name: '', isOptional: false, dateCreated: new Date(), checklistId: '' }]);
why do we need to be passing in dateCreated? I would assume the createChecklistargs does not take in a dateCreated

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/EditChecklistModal.tsx
> +  const handleFormSubmit = async (data: ChecklistCreateArgs) => {
same comments for this component

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/EditSubtaskModal.tsx
> +    try {
i dont think we need these either

2025-01-06 16:42 UTC, Peyton-McKee commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/SubtaskFormModal.tsx
> +  const schema = yup.object().shape({
put schema outside of component

2025-01-06 17:14 UTC, Aaryan1203 commented on src/frontend/src/pages/AdminToolsPage/OnboardingConfig/Checklists/CreateChecklistModal.tsx
> +        descriptions: (data.descriptions as unknown as { name: string }[]).map((desc) => desc.name)
The reason I had to do it like this is because i need to make descriptions be an object with the key of name and then the string in order for me to use it in the useFieldArray. Because of that i had to do this wierd type casting thing and cudn't find another way around it

2025-01-09 23:05 UTC, Aaryan1203 reviewed
lgtm

2025-01-09 23:05 UTC, merged