#2815 make progress bar reactive
Northeastern-Electric-Racing/FinishLine pull request #3103
Opened 2024-12-30 16:35 UTC by superhvarn

## Changes

- onboarding progress bar fills up when team type checklists and general checklists are filled
- finished button enables when it is at 100
- team type checklists and general checklists have progress bars which fill when its tasks are completed
- every task including subtask checks and stays checked when reloaded
- new hook for toggling checklist
- fixed up getUserTeamTypeChecklists and getGeneralChecklists to include userChecked for subtasks

## Screenshots

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #2815)

2025-01-10 15:03 UTC, Peyton-McKee reviewed
can you fix merge conflicts before i leave a larger review

2025-01-11 02:25 UTC, Aaryan1203 requested changes

2025-01-11 02:25 UTC, Aaryan1203 commented on src/frontend/src/hooks/onboarding.hook.ts
>  export const useUsersTeamTypeChecklists = () => {
this should be named useUsersChecklists everywhere

2025-01-13 20:01 UTC, Peyton-McKee approved these changes

2025-01-13 20:01 UTC, merged