#189: Checklists Drive Progress Wire Up
Northeastern-Electric-Racing/FinishLine pull request #316
Opened 2022-10-10 02:10 UTC by anthonybernardi

## Changes

wired it up fully

## Notes

also fixed the bug where you had to refresh after approving a change request to see what proposed solution was approved

## Screenshots

<img width="1121" alt="Screen Shot 2022-10-09 at 10 09 35 PM" src="https://user-images.githubusercontent.com/63663597/194790773-29f39004-b92d-4ec8-b37d-26d2a83c877d.png">
<img width="1126" alt="Screen Shot 2022-10-09 at 10 09 45 PM" src="https://user-images.githubusercontent.com/63663597/194790776-a3511d5c-2364-4884-8b32-4f9de08e715f.png">

Closes #189

2022-10-10 16:19 UTC, Ari-S-123 approved these changes
lgtm

2022-10-10 18:03 UTC, RChandler234 requested changes

2022-10-12 15:00 UTC, anthonybernardi commented on src/frontend/src/components/CheckList.tsx
> +import ErrorPage from '../pages/ErrorPage';
tru

2022-10-12 21:38 UTC, RChandler234 approved these changes

2022-10-12 22:26 UTC, merged