#264 backend test CreateWorkPackage endpoint part 2
Northeastern-Electric-Racing/FinishLine pull request #318
Opened 2022-10-10 23:19 UTC by anurag-arasan

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2022-10-10 23:27 UTC, Ari-S-123 submitted a review, later dismissed

2022-10-12 14:45 UTC, anthonybernardi requested changes
ah so what you did in these tests here is 1) mock that a function returns null 2) call the function 3) check that it returns null. this doesn't really tell us anything other than jest mocking works.

what we need to test instead is that the createWorkPackage endpoint function errors out (or whatever teh case is) as intended when this util function returns null or an unreviewedCr. so you should mock the utils and probably a few prisma functions but then you're calling the endpoint function and it should do the right thing

2022-10-16 21:47 UTC, anurag-arasan commented
> ah so what you did in these tests here is 1) mock that a function returns null 2) call the function 3) check that it returns null. this doesn't really tell us anything other than jest mocking works.
> 
> what we need to test instead is that the createWorkPackage endpoint function errors out (or whatever teh case is) as intended when this util function returns null or an unreviewedCr. so you should mock the utils and probably a few prisma functions but then you're calling the endpoint function and it should do the right thing

@anthonybernardi I don't believe that my changes just told us that "jest mocking works".  The changes I've added test the two cases specifically for the getChangeRequestReviewState, one of which happens to be "when a separate function returns null this should return null". The premise that I have "mock[ed] that a function returns null" is thereby incorrect. 

However, I understand that the intent of this issue is to holistically test createWorkPackage endpoint, and I have misinterpreted the language in my assigned issue (https://github.com/Northeastern-Electric-Racing/FinishLine/issues/264) by testing the cases for the getChangeRequestReviewState instead of testing the cases for the createWorkPackage endpoint given the mocked return value of getChangeRequestReviewState. I will promptly make these changes, and I apologize for the tardiness on this ticket, but I just wanted to clarify my reasoning behind my initial attempt of this PR.

2022-10-17 16:55 UTC, Ari-S-123 approved these changes

2022-10-19 13:59 UTC, anthonybernardi approved these changes
awesome!!

2022-10-19 14:00 UTC, merged