#226: added and implemented helper print function
Northeastern-Electric-Racing/FinishLine pull request #319
Opened 2022-10-10 23:36 UTC by stevenl224

## Changes

Added and implemented a helper print function that printed the updated statuses of a change. Implementation of buildChangeDetail can be found in change-requests, work-packages, and projects controller messages. 

## Screenshots
- I had some issues with actually seeing the changes but the helper function logic appears correct and is implemented in the right places.
- 
![image](https://user-images.githubusercontent.com/108558702/194967609-664c9984-c698-48db-bf7c-2de0eb821212.png)

Closes #226

2022-10-11 04:43 UTC, RChandler234 approved these changes

2022-10-12 14:35 UTC, anthonybernardi approved these changes
great work!

2022-10-12 14:42 UTC, anthonybernardi requested changes
actually turns out there are more places that need to use this function, they just use the word "edited" and not "changed" so we didn't find them before:

`projects.utils.ts`: lines 241 and 365
`work-packages.utils.ts`: lines 108, 128, and 234

2022-10-13 03:45 UTC, anthonybernardi approved these changes
lgtm lets gooo

2022-10-13 03:48 UTC, merged