#310 adjusted the crId field in project edits to be empty instead of -1
Northeastern-Electric-Racing/FinishLine pull request #328
Opened 2022-10-12 23:51 UTC by ethankong150

## Changes

changed the default project edit crID field to be empty instead of -1

## Notes

n/a

## Test Cases

check if the field can't be negative
check if the field remains empty when refreshing
check that a value has to be manually added to the field

## Screenshots

![Screenshot (122)](https://user-images.githubusercontent.com/90352511/195468106-4f9a14b1-f71a-4a5b-8ae2-a14edb0c89c9.png)
![Screenshot (124)](https://user-images.githubusercontent.com/90352511/195468132-06baaf51-64b7-4d02-a762-9c49c198e647.png)

![Screenshot (123)](https://user-images.githubusercontent.com/90352511/195468122-f9598c9f-14c3-4995-ac38-6d73ef8202
![Screenshot (125)](https://user-images.githubusercontent.com/90352511/195468143-0746dfad-3918-4231-9ca6-793321ff3829.png)
0d.png)

## To Do

nah we chillin

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2022-10-13 01:50 UTC, Ari-S-123 approved these changes

2022-10-13 03:24 UTC, anthonybernardi requested changes

2022-10-13 03:24 UTC, anthonybernardi commented on src/frontend/src/pages/ProjectDetailPage/ProjectEditContainer/ProjectEditContainer.tsx
> +  const [crId, setCrId] = useState(query.get('crId') || NaN);
not a fan of `NaN`, you can just do empty string then you'll have to change one line below

2022-10-21 03:12 UTC, anthonybernardi approved these changes
awesome!

2022-10-21 03:13 UTC, merged