#142: teams and user settings
Northeastern-Electric-Racing/FinishLine pull request #349
Opened 2022-10-16 21:55 UTC by anthonybernardi

teams and user settings

2022-10-17 04:23 UTC, RChandler234 requested changes

2022-10-17 04:23 UTC, RChandler234 commented on src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx
> +      <Grid container>{workPackages.isLoading ? <LoadingIndicator /> : fullDisplay}</Grid>
![image](https://user-images.githubusercontent.com/29521172/196088568-2a100f14-b4b0-40ec-82ec-5df0789c0728.png)

The version with the grid doesn't have the box we have on prod; we probably wanna keep some kind of separators between the work packages

2022-10-17 04:23 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ImplementedChangesList.tsx
> +            </Tooltip>
Could you make the tooltip bigger, it's kinda small/ hard to read on my screen

2022-10-17 04:23 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ActivationDetails.tsx
> +      </Grid>
![image](https://user-images.githubusercontent.com/29521172/196088900-f8a33be0-3cef-4fb1-af36-3abbdfa653e7.png)
Prod looks like this with the spaces in between, you can get the same effect by making the actual info in their own grid items. I think it'd be worth making the change bc this looks a bit cramped

2022-10-22 20:43 UTC, anthonybernardi commented
<img width="1556" alt="Screen Shot 2022-10-22 at 4 33 21 PM" src="https://user-images.githubusercontent.com/63663597/197361629-c1365bca-e029-45f6-a2fa-51c5d5437dbb.png">
<img width="979" alt="Screen Shot 2022-10-22 at 4 42 05 PM" src="https://user-images.githubusercontent.com/63663597/197361637-4a0f1209-fa22-4b49-9eec-da9f24330527.png">
<img width="651" alt="Screen Shot 2022-10-22 at 4 42 56 PM" src="https://user-images.githubusercontent.com/63663597/197361642-4a8134fb-d293-4bca-be7c-f4e28bd7340d.png">

2022-10-23 00:51 UTC, merged