#142 m UI migration reid 2
Northeastern-Electric-Racing/FinishLine pull request #350
Opened 2022-10-16 23:05 UTC by RChandler234

## Changes

Switched over ChangeRequestDetailsView.tsx, doesn't fix everything on that page fyi just read the code

Closes # (issue #)

2022-10-28 00:15 UTC, anthonybernardi requested changes

2022-10-28 00:15 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
> +    <Container>
get rid of this container, that's why it's indented so much. just do <> </>

2022-10-28 00:15 UTC, anthonybernardi commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
> +      <Grid container spacing={1}>
the details don't really look good at any size. check out the pr i did because i did some spacing in that and it looks good i think

2022-10-28 00:15 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
> +        <Grid container spacing={1}>
change request details dont look right when you go to extra small mode

2022-11-03 01:05 UTC, Ari-S-123 approved these changes

2022-11-04 22:28 UTC, anthonybernardi approved these changes
still don't really love the details but good enough for now

2022-11-05 04:10 UTC, merged