#252 test getSingleProject endpoint
Northeastern-Electric-Racing/FinishLine pull request #364
Opened 2022-10-20 00:47 UTC by a-geng

## Changes
Tests for getSingleProject endpoint

## Test Cases
- fails given invalid project wbs
- fails when associated webselement doesnt exist
- works

Closes #252

2022-10-20 00:51 UTC, glacierA requested changes
nice job! rename a few things then we can merge it in.

2022-10-20 00:51 UTC, glacierA commented on src/backend/tests/test-data/projects.test-data.ts
> +export const plz = {
change this lol

2022-10-20 00:51 UTC, glacierA commented on src/frontend/package.json
> -    "@types/react-query": "^1.2.9",
don't commit package.json

2022-10-20 00:51 UTC, glacierA commented on src/backend/tests/projects.test.ts
> +  test('getSingleProject fails when associated webselement doesnt exist', async () => {
webselement?

2022-10-21 03:00 UTC, glacierA approved these changes
lgtm

2022-10-21 03:39 UTC, anthonybernardi approved these changes
nice job!

2022-10-21 03:39 UTC, anthonybernardi commented on src/backend/tests/projects.test.ts
> +    mockProjectTransformer.mockReturnValue({ message: 'projectTransformer called' });
clever!

2022-10-21 03:40 UTC, merged