356-created-sendSlackCRReviewNotification
Northeastern-Electric-Racing/FinishLine pull request #374
Opened 2022-10-20 22:21 UTC by ryanhowe28

## Changes

Added sendSlackCRReviewNotification in the utils class
Added a call for the method in change-request.controllers at the end of the reviewChangeRequest method

## Notes

Not sure if I called the user who submitted the change request correctly. Lines 207/208 in change-requests.controllers. 
const person works but I don't think I should be pulling from the body. The line that is commented out (207) gives me an error when I try to use person.userSettings (line 210) and says that type user does not have a field userSettings. 

## To Do

_Any remaining things that need to get done_

- [ ] correctly implement function
- [ ] test function

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)
#356

2022-10-22 19:56 UTC, anthonybernardi requested changes
looks pretty good, main change is just to make sure you get the user from the db correctly.

Also make sure to name your branch with the # and same with your commit messages (i.e., "#356: changed something" or branch name: "#356-cr-review-slack-notification")

2022-10-22 19:56 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +  const person = body.submitter;
the commented out line is more correct, you need to get the person from prisma using the submitterId, then include the usersettings in that object

2022-10-22 19:56 UTC, anthonybernardi commented on src/backend/src/utils/change-requests.utils.ts
> +  settings: UserSettings,
may as well just pass in the slackId instead of the whole settings object

2022-10-22 19:56 UTC, anthonybernardi commented on src/backend/src/utils/change-requests.utils.ts
> +  const btnText = `View CR Review#${crId}`;
```suggestion
  const btnText = `View CR #${crId}`;
```

2022-10-30 15:52 UTC, Ari-S-123 approved these changes

2022-11-17 19:29 UTC, anthonybernardi reviewed
tiny thing

2022-11-17 19:29 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +  if (personSettings) {
```suggestion
  if (personSettings && personSettings.slackId) {
```

2022-11-18 20:57 UTC, anthonybernardi approved these changes
nice

2022-11-18 20:58 UTC, merged