#325 - If a Work Package is not active then as per the UI checkboxes …
Northeastern-Electric-Racing/FinishLine pull request #404
Opened 2022-10-28 04:37 UTC by sho-r1024

…*should* be disabled, tests still necessary

## Changes

I added a `isDisabled` prop to the CheckList component which would determine whether the checkbox is disabled or not by being what the `disabled` attribute of the checkbox was set to. I also went in and made sure that the checklist in `WorkPackageViewContainer.tsx` had its values disabled based on the project status. 

## Notes

While the UI seems to reflect the new changes, the jest tests do not seem to detect that an item is disabled when `isDisabled` is set to true. This is the only roadblock I have and there is a good chance I'm constructing the tests incorrectly.

## Test Cases

**So far only the enabled test case seems to work on jest, however both test cases seem to work on the website.**

 - Test items have `isDisabled` set to false.
 - Test items have `isDisabled` set to true

## Screenshots

Here's the checkboxes disabled in an inactive WP: 

![image](https://user-images.githubusercontent.com/97998577/198503115-f18bc72d-442d-4b22-adbb-d2838e418f6b.png)

Here they are enabled in an active WP:

![image](https://user-images.githubusercontent.com/97998577/198503276-6da2323c-7929-4485-86fe-5244d928401d.png)

## To Do

_Any remaining things that need to get done_

- [ ] Verify the jest tests are all working, fix any errors I may be making with these tests.

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #325

2022-10-28 04:38 UTC, sho-r1024 commented
Not all checks will pass as there is a test that I left in there that doesn't pass.

2022-11-04 04:21 UTC, jonathan-chen10 requested changes
Looking pretty good, just a few small changes you can check out :)

2022-11-04 04:21 UTC, jonathan-chen10 commented on src/frontend/src/tests/components/CheckList.test.tsx
> +import { check } from 'prettier';
Lint check doesn't like likes 16 and 17, you never used these imports so remove these 2 lines

2022-11-04 04:21 UTC, jonathan-chen10 commented on src/frontend/src/tests/components/CheckList.test.tsx
> +    for (var c of checkboxes as Array<HTMLElement>) {
User `const` instead of `var`. Also I don't think you need `as Array<HTMLElement>` -- does it still work if you removed that?

2022-11-05 00:35 UTC, jonathan-chen10 reviewed
lgtm!

2022-11-05 04:20 UTC, RChandler234 approved these changes
lgtm 🔥

2022-11-05 15:33 UTC, jonathan-chen10 approved these changes
Great work!

2022-11-05 21:26 UTC, anthonybernardi approved these changes
nice! love the tests too

2022-11-05 21:26 UTC, merged