#409 Allow project leads to check description bullets
Northeastern-Electric-Racing/FinishLine pull request #413
Opened 2022-11-07 22:02 UTC by Peyton-McKee

## Changes

Added another check to see if the project lead is editing the description bullets even if they are a member 

## Test Cases

Case A: Member who is project lead checking description bullet 

<img width="956" alt="Screen Shot 2022-11-07 at 4 59 30 PM" src="https://user-images.githubusercontent.com/113635669/200424650-ec1273c7-9d4e-4544-97fb-749d4077c90f.png">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #409  (issue #)

2022-11-07 22:52 UTC, Ari-S-123 requested changes

2022-11-07 22:52 UTC, Ari-S-123 commented on src/backend/src/utils/description-bullets.utils.ts
> +  console.log(leader);
Should this console.log still be here?

2022-11-07 22:53 UTC, Peyton-McKee commented on src/backend/src/utils/description-bullets.utils.ts
> +  console.log(leader);
u didnt see anything

2022-11-07 22:55 UTC, Ari-S-123 submitted a review, later dismissed

2022-11-08 23:56 UTC, anthonybernardi requested changes
can u also add the project manager pls

2022-11-11 19:14 UTC, anthonybernardi requested changes
definitely not prettier formatted

2022-11-15 02:30 UTC, anthonybernardi approved these changes

2022-11-15 02:30 UTC, merged