#400: Project Edit Form
Northeastern-Electric-Racing/FinishLine pull request #424
Opened 2022-11-09 23:14 UTC by anthonybernardi

## Changes

Changed the entire form page to use react hook forms which is a lot better and it fully works. I did absolutely no work to make it look nice though. This was already a ton of work so I might not want to do too much of that but idk

## Notes

Made a custom react hook text field component which is super useful. Also just ignored the EditableText component thing since so much of it needed to be replace for React Hook Forms. Unfortunately, that leads to some features going away like pressing enter makes a new text box and stuff like that (although we can work on readding that later)

## Screenshots

![Screen Shot 2022-11-09 at 6 12 51 PM](https://user-images.githubusercontent.com/63663597/200962009-b9a36182-32ad-4b4f-890e-b13539bbf530.png)
![Screen Shot 2022-11-09 at 6 13 01 PM](https://user-images.githubusercontent.com/63663597/200962037-5e65a7e6-660e-4ac6-9fe7-981f51462944.png)

## To Do

- finish the yup schema and make it show the errors somehow

Closes #398 
Closes #399 
Closes #400

2022-11-10 23:10 UTC, RChandler234 requested changes
Love all the small stuff you cleaned up, splitting out the ProjectEditContainer into separate files where possible is the main comment and also just making the project details section look better. Also if you could put some space between the submit and cancel buttons at the bottom, or do it overlayed like it was before. Looks a lot better than it did already!

This is a picture of the old project edit form for reference:
![image](https://user-images.githubusercontent.com/29521172/201225190-01f18554-8a48-4d67-8716-8a9072c23006.png)

2022-11-10 23:10 UTC, RChandler234 commented on src/frontend/src/components/ReactHookTextField.tsx
> +const ReactHookTextField: React.FC<ReactHookTextFieldProps> = ({
Love this

2022-11-13 20:18 UTC, anthonybernardi commented on src/frontend/src/pages/ProjectDetailPage/ProjectEditContainer/ProjectEditContainer.tsx
> +const buildEditableBulletList = (
tbh just wanted to see how short i could get it with react hook forms and also didn't really care

2022-11-13 21:52 UTC, anthonybernardi commented
New pictures: 
![Screen Shot 2022-11-13 at 4 50 53 PM](https://user-images.githubusercontent.com/63663597/201546360-1aec679f-9d63-4c19-a679-7a1b43c8c7f7.png)
![Screen Shot 2022-11-13 at 4 50 57 PM](https://user-images.githubusercontent.com/63663597/201546361-0b5563aa-6050-427c-9faa-33fdf7f2661c.png)
![Screen Shot 2022-11-13 at 4 51 05 PM](https://user-images.githubusercontent.com/63663597/201546362-53fabce5-92c5-4224-8999-07023c22fc72.png)
![Screen Shot 2022-11-13 at 4 51 08 PM](https://user-images.githubusercontent.com/63663597/201546363-8a28c233-dcf8-497b-a91a-e46b660cf0a8.png)

2022-11-14 00:55 UTC, RChandler234 requested changes

2022-11-14 00:55 UTC, RChandler234 commented on src/frontend/src/layouts/PageBlock.tsx
> +        <Box sx={{ display: 'flex', flexDirection: 'row', mb: 1 }}>
what does mb do again?

2022-11-14 00:55 UTC, RChandler234 commented on src/frontend/src/components/ReactHookEditableList.tsx
> +            <TextField required sx={{ width: 9 / 10 }} {...register(`${name}.${i}.detail`)} />
need to add autoComplete = "off" like you have in ReactHookTextField

2022-11-14 01:04 UTC, anthonybernardi commented on src/frontend/src/layouts/PageBlock.tsx
> +        <Box sx={{ display: 'flex', flexDirection: 'row', mb: 1 }}>
margin bottom

2022-11-14 06:33 UTC, RChandler234 approved these changes

2022-11-14 22:29 UTC, merged