#280: Changed to MUI Button. Uses NER attributes, but cannot use NERButton.
Northeastern-Electric-Racing/FinishLine pull request #427
Opened 2022-11-10 19:14 UTC by nezamj03

Closes #280 

@callmejim1226 @anthonybernardi @RChandler234

2022-11-10 20:45 UTC, RChandler234 requested changes

2022-11-10 20:45 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
>          title={'Change Requests'}
Can you add a little space between the pageTitle and the table? You should be able to wrap the PageTitle in a div and use the style prop on that like the sx property on the mui button to set MarginBottom to like 10-20 or smthn, whatever looks best. Lmk if that doesn't make sense

2022-11-11 02:08 UTC, RChandler234 approved these changes
🔥

2022-11-11 21:32 UTC, callmejim1226 approved these changes
LGTM! Great job!

2022-11-14 00:08 UTC, merged