#195 work package progress for Stage Gate CRs
Northeastern-Electric-Racing/FinishLine pull request #452
Opened 2022-11-17 17:33 UTC by Peyton-McKee

## Changes

Added a backend block that prohibits people from making change request if there are unchecked deliverables or expected activities

## Notes

Wondering What were gonna make front end look like

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

Gray out button on front end/ give feedback to user

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #195  (issue #)

2022-11-17 19:37 UTC, anthonybernardi requested changes
no frontend change?

2022-11-17 19:37 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +    if (uncheckedEADBs.length === 0 && uncheckedDSDB.length === 0) {
shouldnt it be if the length is not 0 then there are some that are unchecked?

2022-11-17 19:37 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +    const uncheckedEADBs = wbsElement.workPackage?.expectedActivities.map(checkDBChecked);
i think this code is too dense. need to find a way to break it down more and name it better. also needs some commenting

```
const uncheckedExpectedActivitiy = expectedActivities.indexOf((ea) => ea.dateTimeChecked === null);
if uncheckedExpectedActivitiy !== -1 => error
```

then the same for deliverables

2022-11-18 21:03 UTC, anthonybernardi requested changes
we should also add the disabled part to the review button for the CR too because what if someone checks all the bullets, makes the CR, then unchecks, then reviews

2022-11-18 21:03 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackagePage.tsx
>    if (isLoading) return <LoadingIndicator />;
add if (isLoading || !data) ... then you can put your whole block after this

2022-11-18 21:03 UTC, anthonybernardi commented on src/backend/src/utils/change-requests.utils.ts
> -
why

2022-11-18 21:03 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +  // const wbsWorkPackage = wbsElement.workPackage;
should this be commented?

2022-11-18 21:07 UTC, Peyton-McKee commented on src/backend/src/utils/change-requests.utils.ts
> -
oops

2022-11-29 14:30 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +export const checkForUncheckedDescriptionBullets = (
this should be in the desc bullets utils file

also whats the point of this if you're not even using hte list and just checking one value of the input?

2022-11-29 14:31 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +      const uncheckedExpectedActivitiy = wpExpectedActivities.map(checkForUncheckedDescriptionBullets);
you can use the Array.some method https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some which is basically an ormap

2022-11-29 14:36 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx
> +    const checkForUncheckedDescriptionBullets = (value: DescriptionBullet, index: number, array: DescriptionBullet[]) => {
same thing about this function not really making sense

2022-11-29 14:36 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx
> +  const { isLoading, isError, data, error } = useSingleWorkPackage(cr.wbsNum);
what if it's a project?

2022-11-29 14:36 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx
> +    if (isError || !data) return <ErrorPage message={error?.message} />;
!data means it's still loading, not an error

2022-12-07 02:39 UTC, Ari-S-123 approved these changes

2022-12-08 03:09 UTC, anthonybernardi requested changes
this doesn't work because we do the change request updating on line 157 when it should be the last thing we do so move that to the end

2022-12-08 03:09 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +
delete this line

2022-12-08 03:09 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +      //checks for any unchecked expected activities, if there are any it will return an error
add a line before

2022-12-08 03:09 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +  const wp = await prisma.work_Package.findUnique({
if we're reviewing a cr for a project this will fail because it wont exist

2022-12-08 03:09 UTC, anthonybernardi commented on src/backend/src/controllers/change-requests.controllers.ts
> +    if (wp) {
this whole block should be before the shouldchangestatus line

2022-12-12 22:44 UTC, anthonybernardi approved these changes
amazing work

2022-12-12 22:44 UTC, merged