#359 W TeamsSpecificPage
Northeastern-Electric-Racing/FinishLine pull request #478
Opened 2022-12-06 19:17 UTC by Peyton-McKee

## Changes

Added react hook for single team, route for team by url, team specific page component and associated view, and api call. 

## Notes

## Screenshots
<img width="523" alt="Screen Shot 2022-12-06 at 2 13 55 PM" src="https://user-images.githubusercontent.com/113635669/206001539-514a77ff-1269-4ded-9ce3-d33048432216.png">

<img width="1728" alt="Screen Shot 2022-12-06 at 2 13 43 PM" src="https://user-images.githubusercontent.com/113635669/206001356-45faf95b-c70c-47e0-aa1f-c3eb19c7bfe3.png">
76e9a-760c-4d92-b000-e7f6c8a79f2a.png">

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #359  (issue #)

2022-12-07 02:30 UTC, Ari-S-123 requested changes
Decrease the horizontal space between the lead/members and the actual names, like in the mockup.

2022-12-08 03:14 UTC, anthonybernardi requested changes

2022-12-08 03:14 UTC, anthonybernardi commented on src/frontend/src/pages/TeamsPage/TeamSpecificPage.tsx
> +  interface ParamTypes {
move to before the component

2022-12-08 03:14 UTC, anthonybernardi commented on src/frontend/src/pages/TeamsPage/TeamSpecificPage.tsx
> +
delete line

2022-12-08 03:14 UTC, anthonybernardi commented on src/frontend/src/pages/TeamsPage/TeamSpecificPage.tsx
> +            <p>{data.description}</p>
instead of <p>, I installed a package called <ReactMarkdown> or something like that that will render this using markdown

2022-12-08 03:14 UTC, anthonybernardi commented on src/frontend/src/pages/TeamsPage/TeamSpecificPage.tsx
> +                  {data.members.map((member, idx) => {
data.members.map(member => fullNamePipe(member)).join(',')

2022-12-08 21:25 UTC, Ari-S-123 submitted a review, later dismissed

2022-12-13 00:07 UTC, merged