#469 - more visual cleanup
Northeastern-Electric-Racing/FinishLine pull request #523
Opened 2023-01-05 06:43 UTC by RChandler234

## Changes

Starting with a couple small things (fixing version number, team summary blocks, and size of collapsed pageblocks). Tried making the default scrollbar for the whole app look cooler, but wasn't having much luck. Gonna keep going through the rest as I have time.

## Screenshots

![image](https://user-images.githubusercontent.com/29521172/210718024-9c8744ab-931c-4343-af66-5f5f91dc8979.png)
![image](https://user-images.githubusercontent.com/29521172/210718080-606b4c32-38fb-479d-a666-355a83797521.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #469  (issue #)

2023-01-06 00:36 UTC, anthonybernardi requested changes
nice!

2023-01-06 00:36 UTC, anthonybernardi commented on src/frontend/src/layouts/Sidebar/Sidebar.tsx
> +      <Typography className={styles.versionNumber}>v.3.5.0</Typography>
this'll be 3.5.1 probably when we release next

2023-01-09 00:45 UTC, Ari-S-123 requested changes
![image](https://user-images.githubusercontent.com/80832201/211226927-6a1b2010-df42-47df-8d3d-2f3385f69805.png)

Can you make the project names not get cutoff somehow.

2023-01-09 04:41 UTC, RChandler234 commented
> ![image](https://user-images.githubusercontent.com/80832201/211226927-6a1b2010-df42-47df-8d3d-2f3385f69805.png)
> 
> Can you make the project names not get cutoff somehow.

Truncating was the solution to make all the cards the same size, if you can think of another solution I can make the change, but this was the easiest fix I/James could come up with for now

2023-01-11 17:55 UTC, anthonybernardi reviewed
amazing. looks so much better. those 8 pixels on the page block honestly make a huge difference

2023-01-11 17:55 UTC, anthonybernardi commented on src/frontend/src/layouts/Sidebar/Sidebar.tsx
> +      <Typography className={styles.versionNumber}>v.3.5.1</Typography>
i dont see this on my screen for some reason (also now it'll be 3.5.3 when this gets released probably)

2023-01-13 04:06 UTC, jamescd18 approved these changes
LGTM

2023-01-13 13:33 UTC, anthonybernardi approved these changes
lovely

2023-01-13 13:33 UTC, merged