#534 display error message
Northeastern-Electric-Racing/FinishLine pull request #537
Opened 2023-01-10 23:15 UTC by Peyton-McKee

## Changes

Display error when something other than a wbs number is passed into other project

## Notes

we dont have a check to see whether or not the wbs number actually references anything, potentially for a future ticket we could have it link to the actual project that it references. 

## Screen

<img width="819" alt="Screen Shot 2023-01-10 at 6 09 12 PM" src="https://user-images.githubusercontent.com/113635669/211681714-83f672d7-2320-4dda-aa66-5dc52017beab.png">
shots

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #534 (issue #)

2023-01-12 18:03 UTC, Ari-S-123 submitted a review, later dismissed

2023-01-12 18:04 UTC, Ari-S-123 reviewed
![image](https://user-images.githubusercontent.com/80832201/212144362-5cdb48b8-2d8c-4bd6-b258-a74cccfea561.png)

Is the why and the explanation not supposed to be aligned?

2023-01-14 16:29 UTC, anthonybernardi requested changes
looks very ugly (because of the sx I think) plz fix

2023-01-17 14:13 UTC, anthonybernardi approved these changes
nice!

2023-01-17 14:13 UTC, merged