#101 - Error Toast/Error Banner Example
Northeastern-Electric-Racing/FinishLine pull request #548
Opened 2023-01-17 20:47 UTC by Ari-S-123

## Changes

Added example of error toast/error banner

## Screenshots

![Screenshot 2023-01-17 154310](https://user-images.githubusercontent.com/80832201/213008773-7cb5da61-7a38-476c-8928-a2ede6ad44a4.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #101

2023-01-17 21:04 UTC, anthonybernardi requested changes
nice! i like it a lot visually. I think to avoid duplicated code though we need some kind of custom component and maybe even a custom hook for it

2023-01-18 04:27 UTC, RChandler234 requested changes

2023-01-18 04:27 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx
> +        <Dialog open={modalShow} onClose={onHide} style={{ color: 'black' }}>
Could you make the Toast duration a lil longer, also just so this PR demonstrates how to use the duration prop

2023-01-18 04:27 UTC, RChandler234 commented on src/frontend/src/components/Toast.tsx
> +  autoHideDuration?: number;
add a comment that this is in milliseconds

2023-01-20 02:20 UTC, RChandler234 submitted a review, later dismissed

2023-01-20 21:58 UTC, anthonybernardi requested changes
the issue with this implementation is that if we want two alerts on the same page, they'll be in separate snackbars which means they will overlay each other. not sure the best way to fix this... maybe separating snackbar and alert into custom stuff? or some way to have a list of alerts within the Toast component?

what if it's like

```
<Toast
...
alerts={[ { message: 'a', type: 'error', open: showAlert1, handleClose: () => setShowAlert1(false) } ]}
/>
```

so the prop is of that type and that? I have no idea if this is a good idea and i wonder if it's something react will get mad about. i feel like there has to be an easier way to do this and im just way overthinking it

2023-01-22 20:22 UTC, anthonybernardi approved these changes
very clean

2023-01-22 20:22 UTC, merged