#613 Added my name to credits
Northeastern-Electric-Racing/FinishLine pull request #725
Opened 2023-01-26 02:03 UTC by jessicaapeng

## Changes

_Explanation of changes goes here_

## Notes

_Any other notes go here_

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

<img width="1426" alt="Screen Shot 2023-01-25 at 9 02 46 PM" src="https://user-images.githubusercontent.com/77088781/214741300-1cd172d7-1dbc-4a6c-b538-e76b4a97aceb.png">

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #613 (issue #)

2023-01-26 16:51 UTC, Peyton-McKee requested changes
Great Work! One small change in your code! Also, it looks like you forgot to fill out your PR. Make sure to tell us what you changed in the changes section and delete any sections you dont end up using!

2023-01-26 16:51 UTC, Peyton-McKee commented on src/frontend/src/pages/CreditsPage/CreditsPage.tsx
>    ];
make sure to delete the yarn out of your color string, also there shouldnt be a space at the end either!

2023-02-02 17:16 UTC, anthonybernardi requested changes

2023-02-02 17:16 UTC, anthonybernardi commented on src/frontend/src/pages/CreditsPage/CreditsPage.tsx
> +    { name: 'Jessica Peng', color: '#2b9e49' }
need a comma here

2023-02-19 20:31 UTC, closed without merging