#549 Fixed color of change requests button on default and on hover
Northeastern-Electric-Racing/FinishLine pull request #733
Opened 2023-01-26 03:48 UTC by Sybaru

## Changes

Updated the "new change request" button to match the color of NER red and added hover functionality

## Screenshots
![image](https://user-images.githubusercontent.com/55457750/214753965-155d2778-e4b6-4cd9-b289-5123a74a78ad.png)

![image](https://user-images.githubusercontent.com/55457750/214754327-c619110f-637a-458c-9606-afd0e5a51a14.png)

## Checklist

Please request reviewers and ping on slack only after you've gone through this whole checklist.

Closes #549

2023-01-26 15:55 UTC, z-roth approved these changes
looks good!

2023-01-27 15:33 UTC, RChandler234 requested changes
Can you copy the styling that you're using here into the NERButton Component(just replace what's currently there), and then call the NER button here (should be able to use the same props, just without the styling). Ari's right that this looks better, so I wanna have it update everywhere we're using this type of button as well

2023-01-27 19:48 UTC, Ari-S-123 approved these changes

2023-01-30 00:56 UTC, RChandler234 approved these changes
LGTM 🔥

2023-01-30 00:56 UTC, merged