switched to MUI icons && aligned them
Northeastern-Electric-Racing/FinishLine pull request #734
Opened 2023-01-26 04:50 UTC by JasperTheDog

## Changes

Swapped from using fortawesome icons to Material UI Icons.
Made the necessary import changes.
Added stack tag formatting for alignment.

## Screenshots
1) Before
![before](https://user-images.githubusercontent.com/15187574/214760532-c208eeb1-7d1b-4591-b305-a095096f4687.jpg)

1) After
![after](https://user-images.githubusercontent.com/15187574/214760537-ccfaf887-9433-4d8e-bd99-97c6d34df2b6.jpg)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

2023-01-26 18:42 UTC, ryanhowe28 requested changes

2023-01-26 18:42 UTC, ryanhowe28 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
> +//import { faFilePowerpoint, faFolderOpen, faList, faListOl } from '@fortawesome/free-solid-svg-icons';
remove commented line

2023-01-27 15:07 UTC, RChandler234 requested changes
Can you use the CoPresent Icon for the slide deck instead of the current one? Should be good to merge after that change

2023-01-31 16:25 UTC, RChandler234 approved these changes
Looks good to me!

2023-01-31 16:57 UTC, ryanhowe28 approved these changes

2023-01-31 16:57 UTC, ryanhowe28 reviewed
Looks great!

2023-02-01 13:36 UTC, anthonybernardi approved these changes
nice work!!

2023-02-01 13:36 UTC, merged