#678: Remove any type from WBSDetails
Northeastern-Electric-Racing/FinishLine pull request #758
Opened 2023-01-29 23:14 UTC by shreesinghal

## Changes
Removed "any" type and replaced it with "unknown" + corresponding error msg

## Checklist
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # 678

2023-01-29 23:32 UTC, Ari-S-123 requested changes

2023-01-29 23:32 UTC, Ari-S-123 commented on src/frontend/src/pages/WBSDetails.tsx
> +import { SystemUpdateOutlined } from '@mui/icons-material';
You have unused imports

2023-02-01 17:52 UTC, shreesinghal commented
I removed the last import statement previously on line 11 because it was not used. 
Please check if any more imports should be removed.

2023-02-01 18:21 UTC, Ari-S-123 approved these changes

2023-02-01 18:39 UTC, ryanhowe28 approved these changes

2023-02-02 17:11 UTC, anthonybernardi approved these changes
nice!

2023-02-02 17:11 UTC, merged