Removed the any type from ProjectsTable.tsx
Northeastern-Electric-Racing/FinishLine pull request #767
Opened 2023-01-30 16:05 UTC by walker-sean

## Changes

I removed the 'any' type from the ProjectsTable.tsx file, replaced with a created interface

## Checklist

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)
#666

2023-01-30 20:14 UTC, callmejim1226 commented on src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
> +  interface BaseColDef {
Great work here! Can we just have this interface located above the render name? So just put this interface above line 19.

2023-01-30 20:26 UTC, callmejim1226 requested changes
Great work for your first ticket! Just a small & quick comment on locating the interface. After you resolve it, I'll request Anthony to review this PR and ask him to merge it!

2023-01-30 20:31 UTC, walker-sean commented
@callmejim1226 I've resolved the location for the interface!

2023-01-30 23:26 UTC, Ari-S-123 submitted a review, later dismissed

2023-02-01 13:26 UTC, anthonybernardi reviewed
nice!

2023-02-01 13:27 UTC, merged