#747 Removed userID from payload in handleCreate function
Northeastern-Electric-Racing/FinishLine pull request #768
Opened 2023-01-30 20:53 UTC by walker-sean

## Changes

Removed userId from the payload in the handleCreate function in RiskLog.tsx so that userId is no longer unnecessarily sent to the backend

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)
#747

2023-01-31 23:08 UTC, callmejim1226 approved these changes
Looks good to me! Great job!

2023-02-01 13:04 UTC, anthonybernardi requested changes
sorry, didn't mention this in the ticket but you need to remove it from the route in the risks.routes.ts file

(if you try to create a risk on the website right now it errors)

2023-02-02 01:31 UTC, walker-sean commented
I removed 'createdById' from the create route. I'm assuming this is the scope of the ticket. Some form of 'userId' exists in other routes, but they dont seem to relate to creating.

2023-02-02 01:58 UTC, callmejim1226 approved these changes
The change in risks.routes.ts looks good to me. Great work!

2023-02-02 17:10 UTC, anthonybernardi approved these changes
nice!

2023-02-02 17:10 UTC, merged