#672 removed any
Northeastern-Electric-Racing/FinishLine pull request #798
Opened 2023-02-02 01:45 UTC by asobolina

## Changes

One instance of any is removed. 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #672

2023-02-02 01:48 UTC, Peyton-McKee requested changes
Some tiny changes

2023-02-02 01:48 UTC, Peyton-McKee commented on src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
> +
delete these two empty lines so that theres only one between the import and the const

2023-02-02 01:49 UTC, Peyton-McKee commented on src/frontend/src/utils/tables.ts
> +  }
ig my comment didnt go through you also need a new line here

2023-02-02 02:02 UTC, asobolina commented
all set

2023-02-02 16:17 UTC, Ari-S-123 requested changes
Could you delete the identical interface in `ProjectsTable.tsx` and make that file use your interface from utils instead?

2023-02-16 16:40 UTC, anthonybernardi approved these changes

2023-02-16 16:40 UTC, merged