#714 Updated cancel and submit buttons on the edit work package page
Northeastern-Electric-Racing/FinishLine pull request #802
Opened 2023-02-02 01:56 UTC by Sybaru

## Changes
Changed the buttons of the submit and cancel to NERSuccessButton and NERFailButton. Also put the cancel on the left and the submit on the right.

## Screenshots

![image](https://user-images.githubusercontent.com/55457750/216212001-d6b7ace9-9cb6-4b3f-98bf-60790ded6287.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #714

2023-02-02 17:15 UTC, RChandler234 commented
we want the buttons in the bottom right corner of the screen to be standard with the rest of the forms @Sybaru

2023-02-03 04:27 UTC, z-roth approved these changes
Looks good! Great work!

2023-02-03 15:36 UTC, RChandler234 requested changes

2023-02-03 15:36 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
> +        <NERSuccessButton variant="contained" type="submit" sx={{ mx: 2 }}>
mx should be 1 on both of these to be standard with how we're doing the rest of these buttons

2023-02-04 21:27 UTC, RChandler234 approved these changes

2023-02-06 02:53 UTC, merged