#715: Changed Buttons to NER Buttons in CreateWorkPackagePage
Northeastern-Electric-Racing/FinishLine pull request #808
Opened 2023-02-02 02:16 UTC by EthanMoskowitz

## Changes

I changed the buttons on the Create work package page to the NER buttons so that every button is consistent.

## Screenshots

<img width="1399" alt="Screen Shot 2023-02-01 at 9 04 44 PM" src="https://user-images.githubusercontent.com/44037183/216213411-8399b2da-6e49-485a-b853-5a5c767188a5.png">

<img width="215" alt="Screen Shot 2023-02-01 at 9 06 20 PM" src="https://user-images.githubusercontent.com/44037183/216213399-12424bc3-3465-47de-8aec-891226c6f78c.png">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #715

2023-02-03 05:33 UTC, glacierA approved these changes
LGTM!

2023-02-03 15:34 UTC, RChandler234 requested changes

2023-02-03 15:34 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +          <NERSuccessButton variant="contained" color="primary" type="submit" disabled={!allowSubmit}>
don't need color prop anymore since we're using the custom components

2023-02-03 15:34 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +          <NERFailButton variant="outlined" color="secondary" onClick={onCancel}>
same don't need color prop here

2023-02-03 15:34 UTC, RChandler234 commented on src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
> +          </NERFailButton>
cancel should be on the left, and create should be on the right. Also they should both be in the bottom right of the page to be consistent with the rest of these types of buttons

2023-02-06 05:22 UTC, RChandler234 approved these changes
Lgtm!

2023-02-07 19:38 UTC, merged