#662: finished ticket, users now properly sorted
Northeastern-Electric-Racing/FinishLine pull request #819
Opened 2023-02-02 22:16 UTC by andrewstsai

## Changes

Users on dev login lists now sorted depending on their role, last name, first name, and user id with decreasing priority

## Notes

Copied over rankUserRole to shared folder so it could be used for frontend

## Test Cases

- Case A
- Edge case
- ...

## Screenshots
 
<img width="301" alt="pr" src="https://user-images.githubusercontent.com/113949854/216461520-7ff232ab-af27-4892-8eba-e189933638c7.png">

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #662

2023-02-02 22:32 UTC, Peyton-McKee requested changes
Great Work! In addition to these comments you need to delete the rankUserRole from the backend and instead whereever it was called use the shared function

2023-02-02 22:32 UTC, Peyton-McKee commented on src/shared/src/rank-user-role.ts
> +  };
need new line here.

2023-02-02 22:32 UTC, Peyton-McKee commented on src/frontend/src/pages/LoginPage/LoginDev.tsx
>              .sort((a, b) => a.userId - b.userId)
no need to sort by userId.

2023-02-05 22:49 UTC, Peyton-McKee approved these changes
LGTM

2023-02-06 02:52 UTC, anthonybernardi approved these changes
very clean!

2023-02-06 02:52 UTC, merged