#250 test get single work package endpoint
Northeastern-Electric-Racing/FinishLine pull request #823
Opened 2023-02-03 19:56 UTC by JasperTheDog

## Changes

Added 3 test for checking that exceptions are properly handled by the function getSingleWorkPackage, using jest spyOn

## Notes

I am not sure how to craft the result for the working test

## Test Cases
Done: a project wbs number is given
Done: the work package does not exist
Done: the project does not exist
Need Help: it works as intended 

## To Do

- [ ] Create data for example return result when function works properly
- [ ] Finish test for function working properly

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)

Ticket #250

2023-02-04 17:49 UTC, ryanhowe28 commented on src/backend/tests/work-packages.test.ts
> +  //   const result = await WorkPackageService.getSingleWorkPackage({ carNumber: 1, projectNumber: 1, workPackageNumber: 1 });
Wouldn't passing in 1.1.1 throw an error like your first test? You have to pass in the values that would return you prismaWorkPackage1

2023-02-16 16:48 UTC, anthonybernardi requested changes
nice work! small things then good to go

2023-02-16 16:48 UTC, anthonybernardi commented on src/backend/src/transformers/work-packages.transformer.ts
> -  } as WorkPackage;
i think you deleted this by accident while fixing merge conflicts

2023-02-16 16:48 UTC, anthonybernardi commented on src/backend/tests/work-packages.test.ts
> +    jest.spyOn(prisma.work_Package, 'findFirst').mockResolvedValue(null);
you don't need this test, it's not testing anything new

2023-02-17 23:18 UTC, closed without merging