#817 dynamically change the dropdown width based on the contents
Northeastern-Electric-Racing/FinishLine pull request #858
Opened 2023-02-10 01:37 UTC by Aaryan1203

Changes the Gantt dropdown filters to adjust their width based on the contents

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/76594216/217978287-843d1e0b-17ba-46fd-9522-458a965c08d2.png">

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #817

2023-02-10 23:05 UTC, Peyton-McKee requested changes
Great Work! The only thing Im concerned about is that this doesnt wrap the text if it gets too large. So we might have teams with really long names and the menu could get really big and potentially get cut off on smaller screens. Maybe we need to add like a max width for it as well and wrap the text if it gets too long.

2023-02-11 01:39 UTC, Ari-S-123 requested changes
The box highlighted in red above the dropdowns need to match the width of the dropdown.

2023-02-13 21:22 UTC, Peyton-McKee requested changes
You need to make it so that the menu items are the same width as the select, not the other way around. (know we talked about it on slack just having it here so its reviewed)

2023-02-15 00:23 UTC, Peyton-McKee approved these changes
lgtm if were gonna truncate by character amount

2023-02-15 04:09 UTC, RChandler234 approved these changes
lgtm 🔥

2023-02-16 16:39 UTC, merged