#752: changed save/cancel buttons in RiskLog
Northeastern-Electric-Racing/FinishLine pull request #864
Opened 2023-02-14 17:22 UTC by vonbuelow

## Changes

Changed the save/cancel buttons in the RiskLog component to use the NERSuccessButton/NERFailButton component rather than just the plain MUI button

## Test Cases

- yarn test:frontend 

## Screenshots

![Screenshot_20230206_104319](https://user-images.githubusercontent.com/118306244/218809865-2c42e617-4877-4e15-9e58-ad635a2c6398.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (752)

2023-02-15 06:03 UTC, tigerhippo commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/RiskLog.tsx
> +              Closesx=
Is there a specific reason why you said 'Closesx=' and not 'Closes'?

2023-02-15 06:03 UTC, tigerhippo commented
@RChandler234 please also review this, I could have missed stuff

2023-02-16 01:53 UTC, tigerhippo commented
Looks good + ready to merge!

2023-02-16 03:23 UTC, RChandler234 requested changes

2023-02-16 03:23 UTC, RChandler234 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/RiskLog.tsx
> +              Closes
Should say 'Close'

2023-02-16 22:25 UTC, anthonybernardi approved these changes
awesome!

2023-02-16 22:26 UTC, merged