#826 - Chane Request Delete Modal
Northeastern-Electric-Racing/FinishLine pull request #868
Opened 2023-02-15 03:36 UTC by Ari-S-123

## Changes

Change Requests can now be deleted.

## Notes

Need clarification on permissions.

## Screenshots

![Screenshot_20230214_102334](https://user-images.githubusercontent.com/80832201/218921476-3c225917-fe73-4dcc-aabd-282f37af6eb7.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #826

2023-02-15 16:27 UTC, anthonybernardi requested changes
awesome!
- the error in the console happens because it invalidates the change requests query after you delete it which then requeries for the now deleted one which errors. im not sure i care that much about it tbh
- should only be when the change request hasn't been reviewed yet so we should turn the review button into a dropdown for the submitter only I think

2023-02-15 16:27 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequestView.tsx
> +  cr: ChangeRequest;
changeRequest

2023-02-15 16:27 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequestView.tsx
> +  const crIDTester = (crId: string | undefined) => {
`const changeRequestIdTester = (crId: string | undefined) => crId && crId == cr.crId.toString()

2023-02-16 04:13 UTC, RChandler234 requested changes

2023-02-16 04:13 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequest.tsx
> +      throw new Error(error);
why are you throwing an error after catching one?

2023-02-16 04:13 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequestView.tsx
> +          />
Could you use the reacthooktextfieldcomponent for this?

2023-02-16 04:13 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequestView.tsx
> +        </NERFailButton>
We should ask james ab the colors for these, a bit weird since success is a delete

2023-02-16 04:13 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequestView.tsx
> +        <Typography sx={{ fontWeight: 'bold' }}>This action cannot be undone!</Typography>
Make the spacing of all the text more like the mock in the epic

2023-02-16 04:13 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/DeleteChangeRequestView.tsx
> +                  placeholder="Enter Change Request ID here"
ask james ab this as well, not sure what wording would be best

2023-02-16 04:13 UTC, RChandler234 commented on src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
> +        </MenuItem>
I think these are supposed to have a divider between them like the other two delete dropdowns

2023-02-16 05:20 UTC, jamescd18 requested changes
Lovely first stab! Some UI / design feedback:
- Can we pls have a X to close on the top right of the dialog? Same behavior as cancel.
- Delete submit button should be disabled while the text field is either empty or contains the incorrect phrase
- I don't think the input field needs to be so large and wide since CR ID is typically just 4 digits. I'd suggest making it full width to the width of the dialog, but don't make the text field be the reason the dialog is larger than needed.
- The bold "this action cannot be undone" appears to have more spacing below than it should and no spacing above where it should. It should appear as though it is the header to a second paragraph in the dialog, per mockups.
- Can you show some screenshots of responsive dialog sizing?
- divider line between action menu items

2023-02-17 03:28 UTC, jamescd18 requested changes
Can we remove that white line below the modal title? It's weird and I know it was in the mocks but we don't want it

2023-02-17 15:01 UTC, anthonybernardi commented
james this looks so much worse now

2023-02-17 16:19 UTC, jamescd18 submitted a review, later dismissed
LGTM

2023-02-21 03:50 UTC, anthonybernardi approved these changes
beautiful

2023-02-21 03:50 UTC, merged