#831 Removed redirectQueryArgs so user is not brought to undefined page
Northeastern-Electric-Racing/FinishLine pull request #869
Opened 2023-02-15 05:29 UTC by walker-sean

## Changes

I removed the const redirectQueryArgs and removed it from the redirect for users that need to login manually, stopping them from being brought to a 404 page.

## Notes

I don't see another use for redirectQueryArgs, but if there does happen to be another use, deleting it fully could have consequences.

## Screenshots

<img width="497" alt="Screen Shot 2023-02-15 at 12 21 19 AM" src="https://user-images.githubuse
<img width="498" alt="Screen Shot 2023-02-15 at 12 21 27 AM" src="https://user-images.githubusercontent.com/114596410/218940653-bfa293b5-710d-4e47-9a0d-f2b7b79f1134.png">
rcontent.com/11459
<img width="499" alt="Screen Shot 2023-02-15 at 12 21 53 AM" src="https://user-images.githubusercontent.com/114596410/218940689-02c4c9f6-939a-4b3a-94c1-76e683dd978a.png">
6410/218940640-4a810957-fe
<img width="1440" alt="Screen Shot 2023-02-15 at 12 22 12 AM" src="https://user-images.githubusercontent.com/114596410/218940700-3ead99bb-200c-4239-b642-1a56ecd116a0.png">
b7-4697-8087-90c324d43fd1.png">
<img width="1440" alt="Screen Shot 2023-02-15 at 12 22 15 AM" src="https://user-images.githubusercontent.com/114596410/218940708-e7b85174-b1a1-411e-9105-4fc68384a629.png">
<img width="1440" alt="Screen Shot 2023-02-15 at 12 22 20 AM" src="https://user-images.githubusercontent.com/114596410/218940715-7db13843-54b4-446b-a7b9-5c7a28a09132.png">

## Checklist

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #)
#831

2023-02-16 00:47 UTC, jonathan-chen10 requested changes
Good work so far Sean. I think we can fix this bug specifically without removing the entire login URL redirect feature. For context, in #223 we decided to embed redirect info in the URL like `/login?page=projects` in order for anyone who accesses this link to be able to get to the right page after logging in. 

redirectQueryArgs grabs information about the current page from `history.location` to make it work, but it's not producing quite the right result, which is why the empty path `/`  ends up as `?page=undefined`. Instead of removing this feature altogether, we want to keep it while fixing the specific bug.

2023-02-16 00:47 UTC, jonathan-chen10 commented on src/frontend/src/app/AppPublic.tsx
> -          search: redirectQueryArgs,
We want to keep this because it embeds the current page into the login URL so after logging in we can get back to the current page.

2023-02-22 21:12 UTC, walker-sean commented
Now, there should be no query strings sent only when login redirects to the home page.

2023-02-26 20:51 UTC, callmejim1226 approved these changes
Looks good to me! The app runs successfully without errors and confirmed that no undefined page loads up in homepage after logging out through my local machine. 

Great job!

2023-02-27 17:51 UTC, merged