#800-removed all instances of React.FC
Northeastern-Electric-Racing/FinishLine pull request #871
Opened 2023-02-16 00:00 UTC by glacierA

## Changes
***DRAFT***
As title says, removed all instances of React.FC in favor of either explicitly listing children as React.ReactNode's or replacing inline-definitions of type React.FC with arrow functions returning JSX.Elements.

Closes #800

2023-02-24 22:45 UTC, RChandler234 requested changes
ganttpage.tsx, navtopbar.tsx, wbsstatus.tsx, loadingindicator.tsx, DetailDisplay.tsx - make sure all of these pages are also changed over, and make sure that any files in the GanttPackage Folder aren't changed at all, that's just a package Ari found to use for the gantt chart, so I don't wanna change it at all

2023-02-24 22:45 UTC, RChandler234 commented on src/frontend/src/app/AppAuthenticated.tsx
> +const AppAuthenticated = (): JSX.Element => {
either add JSX.Element everywhere or don't use it anywhere. We want it to be standard

2023-03-11 20:08 UTC, Ari-S-123 requested changes
Lots of merge conflicts.

2023-03-24 23:21 UTC, RChandler234 commented
Will be worked on again at a later time

2023-03-24 23:21 UTC, closed without merging