#822: Changed button to NERButton
Northeastern-Electric-Racing/FinishLine pull request #887
Opened 2023-02-17 16:24 UTC by isaac-levine

## Changes

Changed button code to
<NERButton variant="contained" onClick={() => setDisplaySnark(displaySnark + 1)}>
  {displaySnark < snark.length ? snark[displaySnark] : '>:('}
</NERButton>

## Notes

Not sure if this is what it's supposed to look like?

## Screenshots

![credits-page-button](https://user-images.githubusercontent.com/80065258/219708555-b9ff7336-3047-40f0-9b08-29cf80cb6a3d.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [X] All commits are tagged with the ticket number
- [X] No linting errors / newline at end of file warnings
- [X] All code follows repository-configured prettier formatting
- [X] No merge conflicts
- [X] All checks passing
- [X] Screenshots of UI changes (see Screenshots section)
- [X] Remove any non-applicable sections of this template
- [X] Assign the PR to yourself
- [X] No `yarn.lock` changes (unless dependencies have changed)
- [X] Request reviewers & ping on Slack
- [X] PR is linked to the ticket (fill in the closes line below)

Closes #822

2023-02-17 16:28 UTC, Ari-S-123 requested changes
Why do you have 36,466 additions to `package.json`?

2023-02-23 03:26 UTC, z-roth requested changes
can we revert the package-lock and yarn.lock back? we shouldn't have to change them

2023-02-24 02:02 UTC, z-roth approved these changes
looks good! great work!

2023-02-24 16:24 UTC, Ari-S-123 approved these changes

2023-02-25 00:27 UTC, merged