#787: moved admin tools to user menu
Northeastern-Electric-Racing/FinishLine pull request #896
Opened 2023-02-18 20:19 UTC by ryanhowe28

## Changes

Moved admin tools to the user menu

## Screenshots
![image](https://user-images.githubusercontent.com/102765855/219892949-91852e7d-755d-45d5-a5ea-0434e01a6cec.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #787

2023-02-18 22:47 UTC, RChandler234 requested changes
make sure to add in the AdminPanelSettings, like the ticket says; also not sure if we want the admin tools menu item to look like logout, probably want it to look like the settings

2023-02-19 00:09 UTC, jamescd18 requested changes
yep, agreed with Reid. Should look like settings and should go above logout.

2023-02-20 17:59 UTC, RChandler234 requested changes

2023-02-20 17:59 UTC, RChandler234 commented on src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx
> +  );
rename this to AdminTools = () => (MenuItem...);
and then you can call it as <AdminTools/> down where you have adminTools
does the same thing, just looks a lil better in code

2023-02-22 04:28 UTC, RChandler234 approved these changes

2023-02-22 04:29 UTC, merged