#790 edit task endpoint
Northeastern-Electric-Racing/FinishLine pull request #902
Opened 2023-02-19 21:38 UTC by ibarra000

This PR depends on https://github.com/Northeastern-Electric-Racing/FinishLine/issues/789 being merged.

## Changes
Created editTask endpoint

## Notes

I'm getting some errors in the test data.
I added in checks that make sure the title and notes are within the proper word limits.

## Test Cases

- Successful task edit
- Unsuccessful task edit (invalid permissions, task deleted, task doesn't exist, title word limit, notes word limit ) 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # 790

2023-02-21 14:04 UTC, Peyton-McKee requested changes
Great work! Can u also post screenshots of manual tests pls.

2023-02-21 14:04 UTC, Peyton-McKee commented on src/backend/src/services/tasks.services.ts
> +    if (!isUnderWordCount(notes, 150)) throw new HttpException(400, 'Notes must be less than 250 words');
These numbers dont match up, think its supposed to be 250

2023-02-21 18:11 UTC, Peyton-McKee requested changes

2023-02-21 18:11 UTC, Peyton-McKee commented on src/backend/tests/tasks.test.ts
> +  afterEach(() => {
You can delete this function we do it at the top

2023-02-27 03:35 UTC, Peyton-McKee requested changes
One tiny thing that i see

2023-02-27 03:35 UTC, Peyton-McKee commented on src/backend/src/routes/tasks.routes.ts
> +  body('deadline'),
validate this as a date please

2023-02-27 17:25 UTC, anthonybernardi requested changes

2023-02-27 17:25 UTC, anthonybernardi commented on src/backend/src/services/tasks.services.ts
> +    if (user.role === Role.GUEST) throw new AccessDeniedException();
can we use the has edit task permissions function created by Parth pls

2023-02-27 17:31 UTC, merged