#635-Replaced-alert()-with-useToast()-in-ReviewChangeRequest
Northeastern-Electric-Racing/FinishLine pull request #908
Opened 2023-02-21 15:12 UTC by aidanroche3

## Changes

Replaced all instances of alert() with useToast() in ReviewChangeRequest

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #635

2023-02-21 17:06 UTC, Ari-S-123 approved these changes

2023-02-21 17:12 UTC, Ari-S-123 requested changes

2023-02-21 17:12 UTC, Ari-S-123 commented on src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequest.tsx
> +      toast.error(error);
```
if (error instanceof Error) {
    toast.error(error.message);
}
```

2023-02-21 18:40 UTC, anthonybernardi reviewed
nice!

2023-02-21 18:40 UTC, anthonybernardi commented on src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequest.tsx
>        throw new Error(error);
we shouldn't throw the error after catching it, that crashes the page

2023-02-22 02:15 UTC, callmejim1226 approved these changes
Other than Ari's and Anthony's comments, all looks good to me! Nice job!

2023-02-28 23:36 UTC, Ari-S-123 approved these changes

2023-03-01 02:27 UTC, callmejim1226 approved these changes
Looks good to me!

2023-03-01 18:01 UTC, merged