#882 Editing WP Status should no longer be allowed
Northeastern-Electric-Racing/FinishLine pull request #912
Opened 2023-02-21 20:06 UTC by nezamj03

## Changes

Removed Status from form, from payload, and from route, controller, and service.

## Screenshots

<img width="1359" alt="Screen Shot 2023-02-21 at 3 06 03 PM" src="https://user-images.githubusercontent.com/87815804/220447199-78190abe-5763-41ef-a2d0-c6c71d0c6d58.png">

## To Do

_Any remaining things that need to get done_

- [ ] write tests for edit WP

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #882

2023-02-21 21:08 UTC, anthonybernardi requested changes
this doesn't compile for me because you need to update the calls about status in the seed data and possible other places

2023-02-21 21:08 UTC, anthonybernardi commented on src/backend/src/services/work-packages.services.ts
> -    status?: WbsElementStatus;
this stuff is definitely still needed, this is how we get work packages of a certain status

2023-02-21 21:08 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx
> -          <StatusSelect />
need to delete StatusSelect the component too

2023-02-26 20:36 UTC, RChandler234 requested changes
![image](https://user-images.githubusercontent.com/29521172/221435657-0afded1d-de15-4731-8a8f-4e43420f4fb3.png)
make sure the spacing looks good on these (make sure there's a little gap between project lead and project manager, and you can probably fit stage select where status select used to be)

2023-02-26 20:36 UTC, RChandler234 commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditDetails.tsx
> -              <FormLabel>Project Manager</FormLabel>
add the form labels back in for project lead and manager

2023-02-27 16:27 UTC, anthonybernardi approved these changes
awesome!!

2023-02-27 16:28 UTC, merged