Edit task assignees
Northeastern-Electric-Racing/FinishLine pull request #914
Opened 2023-02-22 03:40 UTC by ninest

## Changes

Create the edit task assignees endpoint.

## Test Cases

(not done yet)

- Successful edit
- Unsuccessful edit (invalid permissions, task deleted, task doesn't exist, assignees don't exist)

## To Do

- [ ] Write tests

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #791

2023-02-23 19:05 UTC, anthonybernardi requested changes
awesome work! very small stuff

2023-02-23 19:05 UTC, anthonybernardi commented on src/backend/tests/tasks.test.ts
> +          userId: 2
this object should probably be `[{ userId: superman.userId }, { userId: wonderwoman.userId }]` to avoid hardcoding problems if the data ever changes

2023-02-25 00:03 UTC, ninest commented on src/backend/src/routes/tasks.routes.ts
> +tasksRouter.post('/:taskId/edit-assignees', body('assignees').isArray(), TasksController.editTaskAssignees);
Done, `intMinZero(body('assignees.*'))`

2023-02-27 16:55 UTC, anthonybernardi approved these changes
awesome work!

2023-02-27 16:55 UTC, merged