#712: Change CreateProjectPage to use NER Buttons
Northeastern-Electric-Racing/FinishLine pull request #919
Opened 2023-02-23 02:50 UTC by vonbuelow

## Changes

Changed the save/cancel buttons in the CreateProjectPage component to use the NERSuccessButton/NERFailButton component rather than just the plain MUI button. Cancel on the left and submit on the right. 

## Test Cases

- yarn test:frontend

## Screenshots

![Screenshot_20230222_092940](https://user-images.githubusercontent.com/118306244/220810594-8247e2f9-f80e-455a-b624-4ab26524db40.png)

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #712

2023-02-24 06:20 UTC, tigerhippo reviewed
The code looks fine, just send me a screenshot of your tests failing.

2023-02-24 14:39 UTC, Ari-S-123 requested changes

2023-02-24 14:42 UTC, Ari-S-123 requested changes

2023-02-24 14:42 UTC, Ari-S-123 commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +          <NERSuccessButton variant="contained" type="submit" sx={{ mx: 1 }}>
`disabled={!allowSubmit}`

2023-02-24 17:16 UTC, Ari-S-123 approved these changes

2023-02-25 01:09 UTC, RChandler234 requested changes

2023-02-25 01:09 UTC, RChandler234 commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
>          <Box display="flex" gap={2} sx={{ mt: 2 }}>
remove gap = {2} here it's adding another 2 px gap between the buttons, so it's 4 px apart total

2023-02-25 01:09 UTC, RChandler234 commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
>          </Box>
these buttons should be in the bottom right corner of the form to be consistent with the rest of the forms

2023-03-07 22:33 UTC, Ari-S-123 submitted a review, later dismissed

2023-03-09 02:43 UTC, RChandler234 requested changes

2023-03-09 02:43 UTC, RChandler234 commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +          <Box display="flex" sx={{ mt: 2 }}>
you don't need the grid, just put the justifyContent="flex-end" on the Box component, and it should do the same thing

2023-03-09 21:20 UTC, RChandler234 approved these changes
LGTM!!

2023-03-09 21:20 UTC, merged