#762 - rough draft implementation add task UI
Northeastern-Electric-Racing/FinishLine pull request #929
Opened 2023-02-25 23:03 UTC by RChandler234

## Changes

Added in add new task flow.

## Notes

Went ahead and got started on this one since we want to release this Wednesday, but this is still a draft PR. Please feel free to leave review, suggestions, or do some of it yourself cause we need to get this one done asap.

Got most of the ui stuff done today, still need to get some of the edit modes done (particularly the multiselect autocomplete for the assignees, and some sort of datepicker for the deadline)

Also the delete task button isn't hooked up, just waiting on the backend PR to be done for that.

## Screenshots

![image](https://user-images.githubusercontent.com/29521172/221383569-e96dbf0e-3341-4d92-bba1-e6e9673a3c6f.png)

## To Do

- [ ] Get datepicker working for deadline
- [ ] Get multiselect working for assignees
- [ ] finish few details of create hookup
- [ ] hookup delete endpoint once that's done

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #762

2023-02-27 17:23 UTC, anthonybernardi requested changes
delete endpoint is done so you can do that part now too

one thing is that if the page only shows 5 tasks, and there are 5 tasks and you press create, it starts the creation thingy on the next page without taking you to the next page

also i can type in the actions cell


i think i would just prefer a modal lmao

2023-02-27 17:23 UTC, anthonybernardi commented on src/frontend/src/apis/tasks.api.ts
> +export const createSingleTask = (wbsNum: WbsNumber, payload: any) => {
we want to move away from these any payload blocks and pass in the actual parameters

2023-02-27 17:23 UTC, anthonybernardi commented on src/frontend/src/apis/tasks.api.ts
> +export const createSingleTask = (wbsNum: WbsNumber, payload: any) => {
also documentation

2023-02-27 17:23 UTC, anthonybernardi commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
> +      <TaskList tasks={proj.tasks} currentProject={proj.wbsNum} />
currentProjectWbsNumber

2023-03-01 04:22 UTC, RChandler234 commented
merged in peyton's branch, also the change in editworkpackage is because transforming the date that way causes a bug where it can set the date to the next day (since it was using utc time not our current time)

2023-03-01 04:42 UTC, RChandler234 commented
moved the create task to the top of the task list so you don't have to click onto the next page to see it

2023-03-01 17:16 UTC, anthonybernardi approved these changes
500 line file is gross but code looks solid, if we fix that error im good with this

2023-03-01 23:59 UTC, merged