#422 delete wp modal
Northeastern-Electric-Racing/FinishLine pull request #935
Opened 2023-02-27 07:39 UTC by nezamj03

## Changes

In a WP page, the delete button is added into the dropdown, where a modal will prompt confirmation of deletion.

## Screenshots
<img width="1335" alt="Screen Shot 2023-02-27 at 2 34 50 AM" src="https://user-images.githubusercontent.com/87815804/221501811-4cf57b11-4a1a-4263-b7ee-d55a0820ee93.png">
<img width="1356" alt="Screen Shot 2023-02-27 at 2 35 20 AM" src="https://user-images.githubusercontent.com/87815804/221501899-5359c903-605c-489d-8f4d-bcc59e8b77b7.png">
<img width="1440" alt="Screen Shot 2023-02-27 at 2 35 38 AM" src="https://user-images.githubusercontent.com/87815804/221501955-bcdb1fc4-cf45-4953-aaea-f71629abec47.png">
<img width="701" alt="Screen Shot 2023-02-27 at 2 35 49 AM" src="https://user-images.githubusercontent.com/87815804/221502001-ab5e1770-b934-420b-be1a-4efc8b66194c.png">
<img width="595" alt="Screen Shot 2023-02-27 at 2 36 11 AM" src="https://user-images.githubusercontent.com/87815804/221502072-4adaa428-bc07-4fb6-9933-3b1df5fb7db4.png">
<img width="1340" alt="Screen Shot 2023-02-27 at 2 37 07 AM" src="https://user-images.githubusercontent.com/87815804/221502228-2857e807-3258-42f1-b513-424f4b53258d.png">
<img width="1440" alt="Screen Shot 2023-02-27 at 2 38 28 AM" src="https://user-images.githubusercontent.com/87815804/221502478-98b09088-9efb-4c9e-bbe9-89d648f1a261.png">

## To Do

_Any remaining things that need to get done_

- testing

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #422

2023-02-27 15:45 UTC, Peyton-McKee requested changes
Looks great!

2023-02-27 15:45 UTC, Peyton-McKee commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackage.tsx
> +      if (error instanceof Error) {
I dont think u need this cast

2023-02-27 15:45 UTC, Peyton-McKee commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackagePage.tsx
> +  const isAdmin = auth.user?.role === 'ADMIN' || auth.user?.role === 'APP_ADMIN';
Probably should validate auth.user in the isloading if statement then move these two things after

2023-02-27 16:51 UTC, anthonybernardi requested changes
awesome! looks great to me

2023-02-27 16:51 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackage.tsx
> +      if (error instanceof Error) {
you do

2023-02-27 16:51 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackageView.tsx
> +  // const workPackageWbsTester = (wbsNum: string | undefined) => true;
delete

2023-02-27 16:51 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
> +  const deleteBtn = (
deleteButton

2023-02-27 16:51 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
>    const editBtn = (
can u change this to editButton pls

2023-02-27 16:51 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
>          {createCRBtn}
and this to createChangeRequestButton

2023-02-28 15:00 UTC, anthonybernardi requested changes
nice

2023-02-28 15:00 UTC, anthonybernardi commented on src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackage.tsx
> +    await mutateAsync(wbsNumber).catch((error) => {
this won't work, do something like this:
```
    try {
      const wbsNumber = validateWBS(wbsNum);
      await mutateAsync(wbsNumber);
      handleClose();
      history.goBack();
      toast.success(`Project #${wbsPipe(wbsNumber)} Deleted Successfully!`);
    } catch (e) {
      if (error instanceof Error) {
        toast.error(error.message);
      }
    }
```

2023-03-01 15:46 UTC, anthonybernardi approved these changes

2023-03-01 15:46 UTC, merged