#707 Removed use of any in projects.api
Northeastern-Electric-Racing/FinishLine pull request #938
Opened 2023-02-28 01:57 UTC by Lomloam

## Changes

Replaced any with CreateSingleObjectPayload and EditSingleObjectPayload, both interfaces

## Notes

Also replaced two instances of any in project.hooks where editSingleObject and createSingleObject were involved

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes # 707

2023-02-28 02:21 UTC, Peyton-McKee requested changes
Great Work! Just some naming conventions and make sure to remove the anys on the hooks!

2023-02-28 02:21 UTC, Peyton-McKee commented on src/frontend/src/apis/projects.api.ts
> +export const editSingleProject = (payload: EditSingleObjectPayload) => {
editSingleProject

2023-02-28 02:21 UTC, Peyton-McKee commented on src/frontend/src/hooks/projects.hooks.ts
> +  return useMutation<{ message: string }, Error, any>(
make this any of type CreateSingleProjectPayload

2023-02-28 02:21 UTC, Peyton-McKee commented on src/frontend/src/hooks/projects.hooks.ts
>    const queryClient = useQueryClient();
make this editSingleProjectPayload

2023-02-28 02:21 UTC, Peyton-McKee commented on src/frontend/src/utils/types.ts
> +export interface EditSingleObjectPayload {
projectPayload

2023-03-02 16:58 UTC, Peyton-McKee approved these changes
lgtm

2023-03-16 00:13 UTC, anthonybernardi approved these changes
awesome

2023-03-16 00:13 UTC, merged