Map task list tab to URL
Northeastern-Electric-Racing/FinishLine pull request #951
Opened 2023-03-02 02:21 UTC by ninest

## Changes

Map MUI task list tab to URL in the projects page.

## Notes

_Any other notes go here_

## Screenshots

Default to in-progress tab: 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/34677361/222314029-edff9d71-b1c6-420d-8a15-417f000ce6e9.png">

Clicking on tabs: 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/34677361/222314052-e3cbf9a2-0061-4061-bb6b-1abae519afdc.png">

<img width="693" alt="image" src="https://user-images.githubusercontent.com/34677361/222314068-71f0a757-0ffb-4eea-8b78-803d74ae73f1.png">

Reloading:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/34677361/222314117-2ddf7fed-f03b-484b-af4a-8328a5d3dbd5.png">

## To Do

- [ ] Allow user to switch between tabs using browser forward/back buttons

## Checklist

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #878

2023-03-02 02:27 UTC, ninest commented
If the user presses the browser's back button, the URL changes but the tab doesn't. This is fixed with this `useEffect`:

```tsx
const tabUrlValues = ['in-backlog', 'in-progress', 'done'];
const match = useRouteMatch<{ wbsNum: string; tabValueString: string }>('/projects/:wbsNum/:tabValueString');
const tabValueString = match?.params?.tabValueString;
...

const { pathname } = useLocation();
useEffect(() => {
  const newTabValue: number = tabUrlValues.indexOf(tabValueString ?? 'in-progress');
  setValue(newTabValue);
}, [pathname]);
```

2023-03-04 14:21 UTC, Ari-S-123 requested changes

2023-03-04 14:21 UTC, Ari-S-123 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx
> +  const match = useRouteMatch<{ wbsNum: string; tabValueString: string }>('/projects/:wbsNum/:tabValueString');
`${routes.PROJECTS}`

2023-03-09 16:36 UTC, Ari-S-123 requested changes

2023-03-09 16:36 UTC, Ari-S-123 commented on src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
We should not be disabling eslint anywhere.

2023-03-21 19:25 UTC, anthonybernardi approved these changes
awesome!!

2023-03-21 19:29 UTC, merged