#925-improve-layout-of-form-fields
Northeastern-Electric-Racing/FinishLine pull request #957
Opened 2023-03-02 21:44 UTC by NeilSatsangi

## Changes

Made project name wider
Put project name, car number, team, and CR ID in one line in that order
Made project summary full width
Added fields for links, goals, features, other constraints, and rules
Right aligned create and cancel buttons and swapped there places

## Notes

All frontend tests are still passing 

## Screenshots

<img width="1512" alt="Screen Shot 2023-03-02 at 4 42 08 PM" src="https://user-images.githubusercontent.com/79616221/222562579-8a535c7c-f084-4155-8e13-0eea5bdc0a64.png">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # 925

2023-03-03 18:04 UTC, Peyton-McKee requested changes
Great work here! So this ticket is actually more in delth than it should be in that we dont actually support adding goals, constraints, rules or links yet in our backend so you can just remove those fields. Also I think we should stick with two fields per line, so title and car number can be on the same line and then crID and team can be on another one

2023-03-03 20:20 UTC, NeilSatsangi commented
<img width="1512" alt="Screen Shot 2023-03-03 at 3 19 18 PM" src="https://user-images.githubusercontent.com/79616221/222820822-06caa533-a5c0-4016-92a2-49ef62ab04bf.png">
This is what it looks like now. Let me know if this is what you had in mind or if there is anything else you need me to edit

> Great work here! So this ticket is actually more in delth than it should be in that we dont actually support adding goals, constraints, rules or links yet in our backend so you can just remove those fields. Also I think we should stick with two fields per line, so title and car number can be on the same line and then crID and team can be on another one

2023-03-03 20:41 UTC, NeilSatsangi commented
<img width="1512" alt="Screen Shot 2023-03-03 at 3 41 21 PM" src="https://user-images.githubusercontent.com/79616221/222825032-ad090c67-72c1-450f-bba0-c1262c7eefe4.png">

2023-03-03 20:50 UTC, ryanhowe28 reviewed
It all looks a little smushed together, can you see what it looks like with some space in between each row of fields? Let me know if you agree

2023-03-04 01:25 UTC, NeilSatsangi commented
<img width="1512" alt="Screen Shot 2023-03-03 at 8 25 14 PM" src="https://user-images.githubusercontent.com/79616221/222868099-68c23a70-6d53-480b-9bc3-6e1f8ed248f3.png">
Let me know if this looks better or if you had something else in mind.

2023-03-05 05:53 UTC, Peyton-McKee requested changes
I like the ingenuity with creating two grid containers and adding a large margin bottom, but there are props in the mui grid documentation that allow you to add spacing in one container if you look through my comments, one of them has the link

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +        <Grid container sx={{ marginBottom: '24px' }}>
I am nearly certain you do not want this marginBottom here, but I may be totally wrong.

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +            <FormControl sx={{ width: '95%' }}>
these form controls should have the fullwidth attribute and then add padding instead of having them take up less of the grid

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +            <FormControl sx={{ width: '100%' }}>
I like the fullwidth prop but they do the same thing

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +        <Grid container sx={{ marginBottom: '24px' }}>
this should all be in one grid container, there are styles that/ props that add spacing between parts of a grid. https://mui.com/material-ui/react-grid/

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +            <FormControl sx={{ width: '95%' }}>
same thing as what i said above

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +            <FormControl sx={{ width: '100%' }}>
also same thing with fullwidth but its up to you🤷‍♂️

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +        <Grid item xs={12} md={3}>
this grid item is not in a container you accidently ended the grid container in the line above

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +        <Grid item xs={12} md={3}>
also you should delete the md prop because we always want this to take up the fullwidth of the grid

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +          <FormControl sx={{ width: '100%' }}>
same thing as fullwidth above

2023-03-05 05:53 UTC, Peyton-McKee commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +          <SubmitButton variant="contained" color="primary" type="submit" disabled={!allowSubmit}>
change these buttons to NER buttons please.

2023-03-23 01:37 UTC, NeilSatsangi commented
<img width="1512" alt="Screen Shot 2023-03-22 at 9 20 12 PM" src="https://user-images.githubusercontent.com/79616221/227074265-22d4a690-b766-4a88-8386-74d164497186.png">
Implemented all the requested changes based on the feedback. Let me know if there's anything else that needs to be done.

2023-03-23 17:53 UTC, ryanhowe28 submitted a review, later dismissed
Looks amazing

2023-03-27 15:36 UTC, NeilSatsangi commented
I rearranged things based on your feedback James. Let me know if this is what you had envisioned. I've also attached screenshots below of different size windows. The dynamic sizing seems to be working correctly. Let me know if anything else needs to be done!
<img width="1512" alt="Screen Shot 2023-03-27 at 11 35 00 AM" src="https://user-images.githubusercontent.com/79616221/227990064-cdb562c1-7831-4d28-84db-bf5a11968d32.png">
<img width="1138" alt="Screen Shot 2023-03-27 at 11 35 12 AM" src="https://user-images.githubusercontent.com/79616221/227990129-8384524d-42a6-4365-b887-af6f2352258c.png">
<img width="718" alt="Screen Shot 2023-03-27 at 11 35 24 AM" src="https://user-images.githubusercontent.com/79616221/227990179-257ffb4f-b35e-478e-86c0-51a4b4a92ca6.png">
<img width="612" alt="Screen Shot 2023-03-27 at 11 35 44 AM" src="https://user-images.githubusercontent.com/79616221/227990286-97e93f74-7cf0-4753-9de7-a5d37eb2d736.png">

2023-03-27 17:51 UTC, jamescd18 requested changes
Much better! A few more suggestions though. 

Seeing it in the screenshot, I now think that car number should come before team. 

I think it would be best to have the project name and project summary inputs not be side by side. Instead, have them take up the full width with project name coming first and then project summary below. 

For the smallest screens where the input field label spills onto multiple lines, I think it might look better to have the field cols be set so it doesn't go smaller than the width of the label text. 

It's totally fine at those smaller screen sizes to have fields just be two in one row instead of 3. It's all about making the fields arranged in a pleasing UI at every possible size.

2023-03-27 17:51 UTC, jamescd18 commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +            <FormControl fullWidth sx={{}}>
```suggestion
            <FormControl fullWidth>
```

2023-03-27 17:51 UTC, jamescd18 commented on src/frontend/src/pages/CreateProjectPage/CreateProjectFormView.tsx
> +            <FormControl fullWidth sx={{}}>
```suggestion
            <FormControl fullWidth>
```

2023-03-27 21:08 UTC, NeilSatsangi commented
I see what you mean about the dynamic sizing. I have updated it so that when the window reaches a certain size the top row shifts from 3 boxes to 2 and the team box slides down to the next row. I have attached some screenshots so you can see what that looks like. Let me know if anything else needs to be done. 
<img width="1549" alt="Screen Shot 2023-03-27 at 5 04 51 PM" src="https://user-images.githubusercontent.com/79616221/228066323-4f5e16cc-f091-4fab-b907-024effdfe1f6.png">
<img width="1110" alt="Screen Shot 2023-03-27 at 5 05 07 PM" src="https://user-images.githubusercontent.com/79616221/228066366-614463dc-7ebf-4610-a0d6-72996d0e0d34.png">
<img width="865" alt="Screen Shot 2023-03-27 at 5 05 17 PM" src="https://user-images.githubusercontent.com/79616221/228066397-33da11ac-531e-4d70-af74-eea3ea448f89.png">
<img width="834" alt="Screen Shot 2023-03-27 at 5 05 44 PM" src="https://user-images.githubusercontent.com/79616221/228066488-da2a230e-f038-4d0c-8950-15dd83d45c65.png">

2023-03-27 21:31 UTC, jamescd18 requested changes
Beautiful! I also forgot to mention one tiny thing: empty SX objects can just be deleted

2023-03-27 21:34 UTC, jamescd18 approved these changes
LGTM!

2023-03-27 23:33 UTC, anthonybernardi approved these changes
cool

2023-03-27 23:54 UTC, RChandler234 approved these changes
Good Job!

2023-03-27 23:56 UTC, merged