#961 fix logout button
Northeastern-Electric-Racing/FinishLine pull request #972
Opened 2023-03-05 22:00 UTC by Peyton-McKee

## Changes

So when we moved the menu item inside of the google logout, we forgot to add the onclick={renderProps.onclick) function, so we never actually called the google logout button. Now we do and it works (i dont think trickster mode works on dev but does that really matter?)

## Screenshots
<img width="1239" alt="Screen Shot 2023-03-05 at 4 59 58 PM" src="https://user-images.githubusercontent.com/113635669/222988337-90246336-4c2f-4e49-aa9f-7753fe7431b3.png">

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #961 (issue #)

2023-03-05 22:26 UTC, anthonybernardi requested changes
bless

2023-03-05 22:26 UTC, anthonybernardi commented on src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx
> +      clientId={process.env.REACT_APP_GOOGLE_AUTH_CLIENT_ID!}
y change

2023-03-05 22:26 UTC, anthonybernardi commented on src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx
> -        {process.env.NODE_ENV === 'development' ? <DevLogout /> : <ProdLogout />}
can u go back to the development one because otherwise local logout doesnt work for me for some reason

2023-03-05 22:26 UTC, anthonybernardi commented on src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
> +      console.log('test');
delete

2023-03-06 02:27 UTC, RChandler234 requested changes

2023-03-06 02:27 UTC, RChandler234 commented on src/frontend/src/pages/SettingsPage/Settings.tsx
> +                    render={(renderProps) => <NERSwitch id="trick-switch" sx={{ m: 1 }} onClick={renderProps.onClick} />}
trickster mode is not signing me out

2023-03-06 02:27 UTC, RChandler234 commented on src/frontend/src/pages/SettingsPage/Settings.tsx
> +                    render={(renderProps) => <NERSwitch id="trick-switch" sx={{ m: 1 }} onClick={renderProps.onClick} />}
looks like it's a cors error or something in the console

2023-03-06 03:20 UTC, RChandler234 approved these changes

2023-03-06 04:27 UTC, anthonybernardi approved these changes

2023-03-06 04:27 UTC, merged